# -*- coding: utf-8 -*-
"""构建考研 / 四级 / 六级 / 八级 / 雅思 / 托福 / 出国流水 词书（含例句，供 TTS 生成音频）。

设计依据（市场调研结论）：
- 考研大纲 5500 词，但真题高频仅约 1500 词（复现率 60%+）；作文常用约 800 词需精准拼写
- 四级约 4500 核心、六级约 6000（重「一词多义/熟词僻义」而非词量）
- 雅思无大纲词表，按四单项分块；托福按学科分块
=> 不做全量罗列，按「高频核心 + 考点分组」建词书，每词配真题式例句。

输出：data/vocab_<key>.json，schema 与现有词书一致（可直接被 build_vocab.py 归一化）
  { product, version, note, level, stage, mod, books:[{id,title,units:[{id,title,words:[...]}]}] }

用法：python tools/build_exam_books.py
"""
import io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(HERE), 'data')

# ============================================================
# 词条：(word, phonetic, pos, meaning, sentence, sentenceCn, tag)
# 分组依据：真题高频 + 考点属性（熟词僻义/写作提分/逻辑连接等）
# ============================================================

# ---------- 考研：按真题功能分块（熟词僻义/态度词/逻辑词/作文词/搭配） ----------
KY = [
 ("高频动词", [
  ("abandon","/əˈbændən/","v.","放弃；抛弃","They had to abandon the project due to lack of funds.","由于资金不足，他们不得不放弃该项目。","写作替换"),
  ("accelerate","/əkˈseləreɪt/","v.","加速；促进","Government policies may accelerate economic recovery.","政府政策可能加速经济复苏。","高频"),
  ("accommodate","/əˈkɒmədeɪt/","v.","容纳；适应；提供住宿","The new campus can accommodate up to 20,000 students.","新校区最多可容纳两万名学生。","听力高频"),
  ("adhere","/ədˈhɪə/","v.","坚持；黏附","All members must adhere to the principles of the union.","所有成员必须遵守工会章程。","阅读高频"),
  ("alleviate","/əˈliːvieɪt/","v.","减轻；缓解","New measures were taken to alleviate poverty in rural areas.","为缓解农村贫困，采取了新措施。","写作提分"),
  ("allocate","/ˈæləkeɪt/","v.","分配；分派","The university allocated more funds to scientific research.","学校为科学研究分配了更多资金。","图表题"),
  ("amend","/əˈmend/","v.","修订；修改","The constitution was amended to protect minority rights.","宪法被修订以保护少数群体权利。","阅读高频"),
  ("analogy","/əˈnælədʒi/","n.","类比；类推","The essay draws an analogy between brain and computer.","这篇文章将大脑与计算机作类比。","写作提分"),
  ("anticipate","/ænˈtɪsɪpeɪt/","v.","预期；预料","Analysts anticipate a sharp rise in inflation next quarter.","分析师预计下季度通胀将大幅上升。","新闻高频"),
  ("apparent","/əˈpærənt/","adj.","明显的；表面的","It soon became apparent that the theory was flawed.","很快就明显看出该理论存在缺陷。","熟词僻义"),
  ("arbitrary","/ˈɑːbɪtrəri/","adj.","任意的；武断的","The selection process must not be arbitrary.","选拔过程不应带有随意性。","学术词"),
  ("articulate","/ɑːˈtɪkjuleɪt/","v.","清晰表达","She was able to articulate her argument precisely.","她能清晰而精确地表达自己的论点。","口语高分"),
  ("assess","/əˈses/","v.","评估；评定","Researchers assessed the impact of sleep on memory.","研究者评估了睡眠对记忆的影响。","图表题"),
  ("assume","/əˈsjuːm/","v.","假定；承担","We should not assume that correlation implies causation.","我们不应假定相关意味着因果。","逻辑词"),
  ("attribute","/əˈtrɪbjuːt/","v.","归因于","The author attributes the decline to policy failure.","作者把衰退归因于政策失误。","翻译高频"),
  ("coherent","/kəʊˈhɪərənt/","adj.","连贯的；一致的","A coherent argument requires clear evidence.","连贯的论证需要清晰的证据。","学术词"),
  ("commodity","/kəˈmɒdəti/","n.","商品；日用品","Rice is a staple commodity in many Asian countries.","大米在许多亚洲国家是主要商品。","图表题"),
  ("compensate","/ˈkɒmpenseɪt/","v.","补偿；弥补","Extra practice can compensate for weak spoken English.","额外练习可以弥补口语薄弱的不足。","写作提分"),
  ("comprehensive","/ˌkɒmprɪˈhensɪv/","adj.","综合的；全面的","The paper offers a comprehensive review of the field.","该论文对该领域作了全面综述。","学术词"),
  ("comprise","/kəmˈpraɪz/","v.","包含；由…组成","The committee comprises twelve members from five universities.","委员会由来自五所大学的十二名成员组成。","阅读高频"),
  ("conceive","/kənˈsiːv/","v.","构思；设想","It is hard to conceive of a fairer solution.","很难设想出一个更公平的方案。","熟词僻义"),
  ("conform","/kənˈfɔːm/","v.","遵守；符合","All products must conform to safety standards.","所有产品必须符合安全标准。","阅读高频"),
  ("constitute","/ˈkɒnstɪtjuːt/","v.","构成；组成","Women constitute nearly half of the workforce.","女性占劳动力的近一半。","图表题"),
  ("contaminate","/kənˈtæmɪneɪt/","v.","污染；弄脏","Industrial waste contaminated the river upstream.","工业废水污染了上游的河流。","写作替换"),
  ("contradict","/ˌkɒntrəˈdɪkt/","v.","反驳；与…矛盾","The new findings contradict earlier assumptions.","新发现与早先的假设相矛盾。","阅读高频"),
  ("convey","/kənˈveɪ/","v.","传达；运送","Body language conveys emotion more than words do.","肢体语言比言语更能传达情感。","写作提分"),
  ("crucial","/ˈkruːʃl/","adj.","至关重要的","Timing is crucial in this kind of negotiation.","这类谈判中时机至关重要。","写作替换"),
  ("cultivate","/ˈkʌltɪveɪt/","v.","培养；耕作","Schools should cultivate students' critical thinking.","学校应培养学生的批判性思维。","写作提分"),
  ("dedicate","/ˈdedɪkeɪt/","v.","奉献；致力于","She dedicated her career to rural education.","她把一生献给了乡村教育。","写作提分"),
  ("derive","/dɪˈraɪv/","v.","获得；源自","Many students derive great satisfaction from volunteering.","许多学生从志愿服务中获得极大的满足。","阅读高频"),
  ("deteriorate","/dɪˈtɪəriəreɪt/","v.","恶化；变坏","Air quality has deteriorated sharply in recent years.","近年来空气质量急剧恶化。","新闻高频"),
  ("devote","/dɪˈvəʊt/","v.","致力于；献身","The magazine devotes an issue to climate change.","该杂志用一期专门讨论气候变化。","阅读高频"),
  ("diminish","/dɪˈmɪnɪʃ/","v.","减少；削弱","Interest in print media has steadily diminished.","人们对纸质媒体的兴趣持续减弱。","图表题"),
  ("discrepancy","/dɪsˈkrepənsi/","n.","差异；不一致","There is a discrepancy between the two datasets.","两套数据之间存在差异。","学术词"),
  ("dispose","/dɪˈspəʊz/","v.","处理；处置","Factories must dispose of waste responsibly.","工厂必须负责任地处理废弃物。","熟词僻义"),
  ("diverse","/daɪˈvɜːs/","adj.","多样的；不同的","The city has an increasingly diverse population.","这座城市的人口日益多元。","写作替换"),
  ("dominate","/ˈdɒmɪneɪt/","v.","支配；占主导","A few large firms dominate the market.","少数几家大公司主导着市场。","图表题"),
  ("elaborate","/ɪˈlæbərət/","adj.","精心制作的；v. 详述","Could you elaborate on that point?","你能详细说明那一点吗？","口语高分"),
  ("eliminate","/ɪˈlɪmɪneɪt/","v.","消除；淘汰","The policy aims to eliminate tax evasion.","该政策旨在消除逃税现象。","写作替换"),
  ("embrace","/ɪmˈbreɪs/","v.","拥抱；欣然接受","Firms that embrace automation tend to grow faster.","积极接纳自动化的公司往往增长更快。","新闻高频"),
  ("emerge","/iˈmɜːdʒ/","v.","出现；显露","New evidence emerged during the trial.","试验期间出现了新的证据。","新闻高频"),
  ("emphasize","/ˈemfəsaɪz/","v.","强调；着重","The author emphasizes the role of habits in learning.","作者强调习惯在学习中的作用。","写作提分"),
  ("empirical","/ɪmˈpɪrɪkl/","adj.","经验的；实证的","The claim lacks empirical support.","这一说法缺乏实证支持。","学术词"),
  ("endorse","/ɪnˈdɔːs/","v.","支持；赞同","Trade unions endorsed the proposed reform.","工会支持这项改革提案。","阅读高频"),
  ("enhance","/ɪnˈhɑːns/","v.","提高；增强","Regular exercise enhances cognitive performance.","规律运动能提升认知表现。","写作替换"),
  ("entitle","/ɪnˈtaɪtl/","v.","使有权；给…命名","Passengers are entitled to a full refund.","旅客有权获得全额退款。","听力高频"),
  ("equivalent","/ɪˈkwɪvələnt/","adj.","等同的；n. 等价物","There is no equivalent word in English.","英语中没有对应的词。","熟词僻义"),
  ("erode","/ɪˈrəʊd/","v.","侵蚀；削弱","Repeated scandals eroded public trust.","接连的丑闻侵蚀了公众信任。","写作提分"),
  ("essential","/ɪˈsenʃl/","adj.","必要的；本质的","Sleep is essential for memory consolidation.","睡眠对记忆巩固至关重要。","写作替换"),
  ("evaluate","/ɪˈvæljueɪt/","v.","评估；评价","We must evaluate the policy on its outcomes.","我们必须根据结果评估该政策。","学术词"),
  ("evoke","/ɪˈvəʊk/","v.","唤起；引起","The story evoked memories of his childhood.","这个故事唤起了他童年的回忆。","文学词"),
  ("exceed","/ɪkˈsiːd/","v.","超过；胜过","Sales exceeded expectations by 20 percent.","销售超出预期百分之二十。","图表题"),
  ("exclude","/ɪkˈskluːd/","v.","排除；不包括","The sample excludes part-time workers.","样本不包括兼职人员。","图表题"),
  ("exert","/ɪɡˈzɜːt/","v.","施加；运用","Teachers exert a lasting influence on students.","教师对学生有持久的影响。","学术词"),
  ("facilitate","/fəˈsɪlɪteɪt/","v.","促进；使便利","The app facilitates communication between doctors and patients.","这款应用促进了医患沟通。","写作替换"),
  ("fluctuate","/ˈflʌktʃueɪt/","v.","波动；起伏","Oil prices fluctuated wildly throughout the year.","油价全年剧烈波动。","图表题"),
  ("formulate","/ˈfɔːmjuleɪt/","v.","制定；系统阐述","The committee formulated a new set of rules.","委员会制定了一套新规则。","学术词"),
  ("fundamental","/ˌfʌndəˈmentl/","adj.","基本的；根本的","There is a fundamental difference between the two theories.","两种理论存在根本差异。","写作替换"),
  ("generate","/ˈdʒenəreɪt/","v.","产生；生成","The policy generated fierce public debate.","该政策引发了激烈的公众辩论。","写作提分"),
  ("hinder","/ˈhɪndə/","v.","阻碍；妨碍","Poor Internet access hinders online learning.","网络接入不畅阻碍了在线学习。","写作替换"),
  ("hypothesis","/haɪˈpɒθəsɪs/","n.","假设；假说","The data did not support their original hypothesis.","数据不支持他们最初的假设。","学术词"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明；举例说明","The chart illustrates changes in energy use.","图表说明了能源使用量的变化。","图表题"),
  ("implement","/ˈɪmplɪment/","v.","实施；执行","It took three years to implement the reform.","实施这项改革花了三年时间。","新闻高频"),
  ("implication","/ˌɪmplɪˈkeɪʃn/","n.","含义；可能的影响","The findings have important policy implications.","这些发现具有重要的政策含义。","学术词"),
  ("incentive","/ɪnˈsentɪv/","n.","激励；动机","Tax breaks act as an incentive to invest.","税收减免起到了鼓励投资的作用。","经济学词"),
  ("incorporate","/ɪnˈkɔːpəreɪt/","v.","纳入；包含","The curriculum now incorporates digital literacy.","课程现已纳入数字素养。","写作提分"),
  ("indicate","/ˈɪndɪkeɪt/","v.","表明；指示","The survey indicates strong public support.","调查表明公众强烈支持。","图表题"),
  ("inevitable","/ɪnˈevɪtəbl/","adj.","不可避免的","Some degree of conflict is inevitable.","一定程度的冲突是不可避免的。","写作提分"),
  ("infer","/ɪnˈfɜː/","v.","推断；推理","From these figures we can infer a downward trend.","从这些数字我们可以推断出下降趋势。","阅读高频"),
  ("initiate","/ɪˈnɪʃieɪt/","v.","发起；开始","The university initiated a mentoring programme.","该大学发起了一项导师计划。","新闻高频"),
  ("innovation","/ˌɪnəˈveɪʃn/","n.","创新；革新","Innovation drives long-term economic growth.","创新推动长期经济增长。","写作替换"),
  ("integrate","/ˈɪntɪgreɪt/","v.","整合；使一体化","The system integrates data from many sources.","该系统整合了来自多种来源的数据。","学术词"),
  ("intricate","/ˈɪntrɪkət/","adj.","错综复杂的","The regulation has intricate implications for small firms.","该规定对小企业有错综复杂的影响。","写作提分"),
  ("intrinsic","/ɪnˈtrɪnzɪk/","adj.","内在的；本质的","Intrinsic motivation lasts longer than rewards.","内在动机比奖励持续得更久。","学术词"),
  ("justify","/ˈdʒʌstɪfaɪ/","v.","证明…正当；辩护","Nothing can justify such a waste of resources.","任何理由都无法为如此浪费资源辩解。","写作提分"),
  ("legitimate","/lɪˈdʒɪtɪmət/","adj.","合法的；合理的","Privacy is a legitimate concern in this debate.","隐私是这场辩论中合理关切的问题。","熟词僻义"),
  ("magnitude","/ˈmæɡnɪtjuːd/","n.","巨大；重要性","Few grasped the magnitude of the disaster.","很少有人意识到这场灾难的严重性。","新闻高频"),
  ("manifest","/ˈmænɪfest/","v.","表明；adj. 明显的","The crisis manifested as a sharp drop in sales.","危机表现为销量急剧下降。","熟词僻义"),
  ("margin","/ˈmɑːdʒɪn/","n.","页边；差额；边缘","The company operates on a thin profit margin.","这家公司利润微薄。","熟词僻义"),
  ("mediate","/ˈmiːdieɪt/","v.","调解；斡旋","The UN mediated talks between the two sides.","联合国在双方之间进行了调解。","新闻高频"),
  ("mitigate","/ˈmɪtɪɡeɪt/","v.","减轻；缓和","Planting trees helps mitigate the effects of flooding.","植树有助于减轻洪水的影响。","写作提分"),
  ("modify","/ˈmɒdɪfaɪ/","v.","修改；调整","Lawmakers modified the bill after criticism.","议员在批评后修改了法案。","新闻高频"),
  ("monitor","/ˈmɒnɪtə/","v.","监测；监督","Doctors monitor blood pressure daily.","医生每天监测血压。","听力高频"),
  ("notion","/ˈnəʊʃn/","n.","观念；想法","The notion that talent is fixed has been challenged.","天赋固定不变的观念受到了挑战。","熟词僻义"),
  ("objective","/əbˈdʒektɪv/","adj.","客观的；n. 目标","Researchers must remain objective in their analysis.","研究者必须保持分析客观。","学术词"),
  ("obscure","/əbˈskjʊə/","adj.","晦涩的；v. 使模糊","The manual is full of obscure jargon.","这本手册充满晦涩术语。","熟词僻义"),
  ("offset","/ˈɒfset/","v.","抵消；弥补","Higher sales offset the rise in material costs.","销售额上升抵消了材料成本的上涨。","图表题"),
  ("optimal","/ˈɒptɪməl/","adj.","最佳的；最优的","The optimal temperature for growth is 25 degrees.","生长的最佳温度是二十五度。","学术词"),
  ("paradigm","/ˈpærədaɪm/","n.","范式；典范","The discovery caused a paradigm shift in physics.","这一发现促成了物理学的范式转变。","学术词"),
  ("perceive","/pəˈsiːv/","v.","察觉；认为","Consumers perceive the brand as premium.","消费者认为该品牌属于高端。","学术词"),
  ("persist","/pəˈsɪst/","v.","坚持；持续","If symptoms persist, consult a doctor.","若症状持续，请咨询医生。","听力高频"),
  ("phenomenon","/fəˈnɒmɪnən/","n.","现象","This social phenomenon is not new.","这种社会现象并不新鲜。","学术词"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","That sounds plausible, but we lack evidence.","这听起来合理，但我们缺乏证据。","阅读高频"),
  ("practitioner","/prækˈtɪʃənə/","n.","从业者；执业者","Medical practitioners must keep records.","医疗从业者必须保存记录。","学术词"),
  ("precede","/prɪˈsiːd/","v.","先于；在…之前","A short summary precedes each chapter.","每章之前都有简短摘要。","阅读高频"),
  ("preliminary","/prɪˈlɪmɪnəri/","adj.","初步的","Preliminary results look encouraging.","初步结果看起来令人鼓舞。","学术词"),
  ("presume","/prɪˈzjuːm/","v.","推测；假定","We presume the plan will change.","我们推测这个计划会变。","熟词僻义"),
  ("prevalent","/ˈprevələnt/","adj.","普遍的；流行的","This view is prevalent among economists.","这种观点在经济学家中很普遍。","学术词"),
  ("prohibit","/prəˈhɪbɪt/","v.","禁止","The law prohibits smoking in public places.","法律禁止在公共场所吸烟。","听力高频"),
  ("prominent","/ˈprɒmɪnənt/","adj.","突出的；著名的","She is a prominent scholar in the field.","她是该领域的著名学者。","写作提分"),
  ("prompt","/prɒmpt/","v.","促使；adj. 迅速的","Rising costs prompted many firms to relocate.","成本上升促使许多公司搬迁。","新闻高频"),
  ("proponent","/prəˈpəʊnənt/","n.","支持者","Proponents argue the benefits outweigh the risks.","支持者认为收益大于风险。","阅读高频"),
  ("prosperity","/prɒˈsperəti/","n.","繁荣；兴旺","Trade brought decades of prosperity to the port.","贸易为该港口带来了数十年的繁荣。","经济学词"),
  ("radical","/ˈrædɪkl/","adj.","根本的；激进的","The company underwent radical restructuring.","公司经历了彻底的重组。","熟词僻义"),
  ("reciprocal","/rɪˈsɪprəkl/","adj.","互惠的；相互的","The agreement is reciprocal between the two nations.","该协议是两国之间的互惠安排。","学术词"),
  ("reinforce","/ˌriːɪnˈfɔːs/","v.","加强；强化","The findings reinforce earlier conclusions.","这些发现强化了此前的结论。","学术词"),
  ("reluctant","/rɪˈlʌktənt/","adj.","不情愿的","Many firms are reluctant to share data.","许多公司不愿分享数据。","新闻高频"),
  ("render","/ˈrendə/","v.","使成为；提供","The injury rendered him unable to walk.","这伤使他无法行走。","熟词僻义"),
  ("resilience","/rɪˈzɪliəns/","n.","韧性；恢复力","The tests measured the material's resilience.","测试测量了材料的韧性。","写作提分"),
  ("retain","/rɪˈteɪn/","v.","保留；保持","Students retain information better when they teach others.","学生教别人时信息保留得更好。","学术词"),
  ("reveal","/rɪˈviːl/","v.","揭示；透露","The audit revealed serious accounting errors.","审计揭露了严重的会计差错。","新闻高频"),
  ("rigorous","/ˈrɪɡərəs/","adj.","严格的；严谨的","The drug passed rigorous clinical trials.","该药物通过了严格的临床试验。","学术词"),
  ("scarce","/skeəs/","adj.","稀少的；不足的","Fresh water is becoming increasingly scarce.","淡水正变得越来越稀缺。","图表题"),
  ("scope","/skəʊp/","n.","范围；余地","The study falls outside the scope of this paper.","该研究超出了本文范围。","熟词僻义"),
  ("scrutiny","/ˈskruːtəni/","n.","仔细审查","The plan came under intense public scrutiny.","该计划受到公众的严格审视。","新闻高频"),
  ("skeptical","/ˈskeptɪkl/","adj.","怀疑的","Researchers remain skeptical about the claim.","研究者对该说法仍持怀疑态度。","阅读高频"),
  ("solidarity","/ˌsɒlɪˈdærəti/","n.","团结；休戚与共","The disaster forged a sense of solidarity among neighbors.","灾难在邻里之间铸就了团结感。","写作提分"),
  ("sophisticated","/səˈfɪstɪkeɪtɪd/","adj.","复杂精密的；老练的","The lab uses sophisticated imaging equipment.","实验室使用精密的成像设备。","写作提分"),
  ("speculate","/ˈspekjuleɪt/","v.","推测；投机","It would be wrong to speculate without evidence.","没有证据就妄加推测是错误的。","学术词"),
  ("stagnant","/ˈstæɡnənt/","adj.","停滞的","Wages remained stagnant for a decade.","工资停滞了十年。","经济学词"),
  ("stimulate","/ˈstɪmjuleɪt/","v.","刺激；激励","Tax cuts stimulate consumer spending.","减税刺激了消费者支出。","经济学词"),
  ("subsequent","/ˈsʌbsɪkwənt/","adj.","随后的","Subsequent studies confirmed the finding.","随后的研究证实了这一发现。","学术词"),
  ("subsidy","/ˈsʌbsədi/","n.","补贴；津贴","The government cut agricultural subsidies.","政府削减了农业补贴。","经济学词"),
  ("sustain","/səˈsteɪn/","v.","维持；支撑","The economy cannot sustain such rapid growth.","经济无法维持如此快速的增长。","写作提分"),
  ("tackle","/ˈtækl/","v.","应对；处理","The government is trying to tackle youth unemployment.","政府正努力解决青年失业问题。","写作替换"),
  ("tedious","/ˈtiːdiəs/","adj.","冗长乏味的","Data entry is tedious but essential.","数据录入枯燥却必不可少。","听力场景"),
  ("tentative","/ˈtentətɪv/","adj.","暂定的；试探性的","They reached a tentative agreement.","他们达成了初步协议。","学术词"),
  ("thereby","/ˌðeəˈbaɪ/","adv.","从而；因此","The policy raised income, thereby reducing poverty.","该政策提高了收入，从而减少了贫困。","逻辑词"),
  ("threshold","/ˈθreʃhəʊld/","n.","门槛；临界点","Income above this threshold is taxed at a higher rate.","高于此门槛的收入按更高税率征税。","图表题"),
  ("transmit","/trænsˈmɪt/","v.","传输；传播","The virus can be transmitted through droplets.","这种病毒可通过飞沫传播。","新闻高频"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱；损害","The scandal undermined public confidence in the media.","丑闻削弱了公众对媒体的信任。","写作提分"),
  ("unveil","/ʌnˈveɪl/","v.","公布；揭幕","The museum unveiled a rare exhibition.","博物馆公布了一场罕见展览。","新闻高频"),
  ("utilize","/ˈjuːtəlaɪz/","v.","利用","Farmers utilize weather forecasts to plan planting.","农民利用天气预报安排种植。","写作替换"),
  ("valid","/ˈvælɪd/","adj.","有效的；正当的","The experiment lacks a valid control group.","该实验缺少有效的对照组。","学术词"),
  ("verify","/ˈverɪfaɪ/","v.","核实；证实","Journalists should verify claims before publishing.","记者应在发表前核实说法。","学术词"),
  ("viable","/ˈvaɪəbl/","adj.","可行的；能存活的","Solar power is now a viable alternative.","太阳能如今已成为可行的替代方案。","写作提分"),
  ("vigorous","/ˈvɪɡərəs/","adj.","有力的；精力充沛的","The minister made a vigorous defence of the policy.","部长为该政策作了有力辩护。","写作提分"),
  ("vulnerable","/ˈvʌlnərəbl/","adj.","脆弱的；易受伤的","Elderly people are especially vulnerable to the flu.","老年人尤其易受流感侵袭。","写作提分"),
  ("yield","/jiːld/","v.","产生；屈服；n. 产量","The experiment yielded unexpected results.","实验产生了意想不到的结果。","熟词僻义"),
 ]),
 ("熟词僻义陷阱", [
  ("address","/əˈdres/","v./n.","处理；地址","The government must address the housing shortage.","政府必须解决住房短缺问题。","高频陷阱"),
  ("appreciate","/əˈpriːʃieɪt/","v.","意识到；增值","It is hard to appreciate the risk involved.","很难意识到其中涉及的风险。","高频陷阱"),
  ("assume","/əˈsjuːm/","v.","承担；呈现（某种样子）","The plan will assume a new form after reform.","改革后该计划将呈现新形态。","高频陷阱"),
  ("conduct","/kənˈdʌkt/","v.","实施；指挥","The university conducted a large-scale survey.","该大学开展了一项大规模调查。","高频陷阱"),
  ("consequence","/ˈkɒnsɪkwəns/","n.","结果；重要性","They were unaware of the consequences.","他们没有意识到后果。","高频陷阱"),
  ("consider","/kənˈsɪdə/","v.","考虑；认为","Many experts consider the evidence unreliable.","许多专家认为该证据不可靠。","高频陷阱"),
  ("discipline","/ˈdɪsəplɪn/","n.","学科；纪律","Economics is an interdisciplinary discipline.","经济学是一门交叉学科。","高频陷阱"),
  ("draft","/drɑːft/","n./v.","草稿；起草","He drafted the report in just two days.","他仅用两天就起草了报告。","高频陷阱"),
  ("exhibit","/ɪɡˈzɪbɪt/","v.","展出；n. 展品","The museum will exhibit the recovered painting.","博物馆将展出那幅失而复得的画作。","高频陷阱"),
  ("feature","/ˈfiːtʃə/","n.","特点；v. 以…为特色","The latest model features a larger screen.","最新型号的特点是屏幕更大。","高频陷阱"),
  ("firm","/fɜːm/","n./adj.","公司；坚定的","His tone was firm but not unfriendly.","他的语气坚定但不生硬。","高频陷阱"),
  ("issue","/ˈɪʃuː/","n.","问题；期号","Water scarcity is a pressing global issue.","缺水是紧迫的全球性问题。","高频陷阱"),
  ("lead","/liːd/","v./n.","导致；领先","Poor sleep can lead to impaired memory.","睡眠不足会导致记忆力受损。","高频陷阱"),
  ("match","/mætʃ/","v./n.","匹配；比赛","The programme matches students with mentors.","该项目为学生匹配导师。","高频陷阱"),
  ("medium","/ˈmiːdiəm/","n.","媒介；中等的","Television remains a powerful medium.","电视仍是一种强大的媒介。","高频陷阱"),
  ("minute","/maɪˈnjuːt/","n.","当心（= moment）","Wait a minute before deciding.","决定前先稍等一下。","高频陷阱"),
  ("objective","/əbˈdʒektɪv/","n.","目标","Our immediate objective is to cut costs.","我们眼前的目标是削减成本。","高频陷阱"),
  ("party","/ˈpɑːti/","n.","党；聚会","Both parties agreed to the deal.","两党都同意了该协议。","高频陷阱"),
  ("power","/ˈpaʊə/","n.","权力；能量","The country is a major nuclear power.","该国是主要核国家。","高频陷阱"),
  ("present","/ˈpreznt/","v./adj.","呈现；出席的","The findings are presented in Table 2.","研究结果列于表二。","高频陷阱"),
  ("principal","/ˈprɪnsəpl/","adj./n.","主要的；校长","Our principal concern is cost.","我们主要关心的是成本。","高频陷阱"),
  ("reserve","/rɪˈzɜːv/","v./n.","预订；储备","The venue is reserved for the ceremony.","场地已为典礼预订。","高频陷阱"),
  ("second","/ˈsekənd/","adj./v.","第二的；支持","Supporters seconded the motion.","支持者附议了该动议。","高频陷阱"),
  ("sound","/saʊnd/","adj./v.","健全的；听起来","His argument does not sound very convincing.","他的论点听起来不太有说服力。","高频陷阱"),
  ("state","/steɪt/","n./v.","状态；陈述","Please state your reasons clearly.","请清楚陈述你的理由。","高频陷阱"),
  ("term","/tɜːm/","n.","术语；学期","In economic terms, this is a real gain.","从经济角度看，这是真正的收益。","高频陷阱"),
 ]),
 ("逻辑与态度词", [
  ("consequently","/ˈkɒnsɪkwəntli/","adv.","因此；结果","The policy failed; consequently, sales dropped.","政策失败了，因此销量下降。","逻辑词"),
  ("conversely","/ˈkɒnvɜːsli/","adv.","相反地","Conversely, small firms benefited from the change.","相反，小公司从这一变化中获益。","逻辑词"),
  ("despite","/dɪˈspaɪt/","prep.","尽管","Despite the evidence, he maintained his claim.","尽管有证据，他仍坚持自己的主张。","逻辑词"),
  ("furthermore","/ˌfɜːðəˈmɔː/","adv.","此外","Furthermore, the plan ignores cost entirely.","此外，该计划完全无视成本。","逻辑词"),
  ("hence","/hens/","adv.","因此","The data are incomplete; hence the cautious conclusion.","数据不完整，因此结论谨慎。","逻辑词"),
  ("however","/haʊˈevə/","adv.","然而","The method is simple; however, it is slow.","方法很简单，但很慢。","逻辑词"),
  ("nevertheless","/ˌnevəðəˈles/","adv.","尽管如此","The task is hard; nevertheless, it is rewarding.","这项任务很难，但值得。","逻辑词"),
  ("nonetheless","/ˌnʌnðəˈles/","adv.","尽管如此","The criticism was harsh; nonetheless it was useful.","批评尖锐，但仍然有用。","逻辑词"),
  ("moreover","/mɔːrˈəʊvə/","adv.","而且","Moreover, the results apply to other countries too.","而且这些结果也适用于其他国家。","逻辑词"),
  ("nevertheless","/ˌnevəðəˈles/","adv."," nevertheless（让步）","The evidence is strong; nevertheless the claim fails.","证据充分，但该主张仍站不住脚。","逻辑词"),
  ("objective","/əbˈdʒektɪv/","adj.","客观的","An objective assessment requires neutral judges.","客观评估需要中立的评判者。","态度词"),
  ("skeptical","/ˈskeptɪkl/","adj.","持怀疑的","Scientists remain skeptical about the theory.","科学家对该理论仍持怀疑态度。","态度词"),
  ("supportive","/səˈpɔːtɪv/","adj.","支持的","Most committee members were supportive of the plan.","多数委员支持该计划。","态度词"),
  ("critical","/ˈkrɪtɪkl/","adj.","批判的；关键的","The author is critical of the current system.","作者对现行体制持批判态度。","态度词"),
  ("enthusiastic","/ɪnˌθjuːziˈæstɪk/","adj.","热情的","She was enthusiastic about the new project.","她对新项目充满热情。","态度词"),
  ("reluctant","/rɪˈlʌktənt/","adj.","不情愿的","He was reluctant to admit the error.","他不愿承认错误。","态度词"),
  ("indifferent","/ɪnˈdɪfrənt/","adj.","冷漠的","The audience remained indifferent throughout.","观众始终反应冷淡。","态度词"),
  ("ambiguous","/æmˈbɪɡjuəs/","adj.","模棱两可的","The wording of the contract is ambiguous.","合同的措辞模棱两可。","态度词"),
  ("arbitrary","/ˈɑːbɪtrəri/","adj.","武断的","That explanation seems arbitrary.","那种解释显得很武断。","态度词"),
  ("profound","/prəˈfaʊnd/","adj.","深刻的","The book had a profound influence on me.","这本书对我影响深远。","评价词"),
 ]),
 ("写作提分替换词", [
  ("crucial","/ˈkruːʃl/","adj.","关键的","This factor is crucial to success.","这一因素对成功至关重要。","替换 important"),
  ("significant","/sɪɡˈnɪfɪkənt/","adj.","显著的","There was a significant rise in applications.","申请人数显著上升。","替换 important"),
  ("substantial","/səbˈstænʃl/","adj.","大量的；实质的","The government allocated substantial funding.","政府拨付了大量资金。","替换 many"),
  ("compelling","/kəmˈpelɪŋ/","adj.","令人信服的","She made a compelling case for reform.","她提出了令人信服的改革理由。","替换 convincing"),
  ("rigorous","/ˈrɪɡərəs/","adj.","严谨的","The study used a rigorous methodology.","该研究采用了严谨的方法。","替换 careful"),
  ("nuanced","/ˈnjuːɑːnst/","adj.","细致入微的","The issue demands a nuanced response.","这个问题需要细致入微的回应。","替换 detailed"),
  ("plausible","/ˈplɔːzəbl/","adj.","合理的","That is a plausible but unproven theory.","那是个合理但未证实的理论。","替换 possible"),
  ("unprecedented","/ʌnˈpresɪdentɪd/","adj.","前所未有的","The city saw unprecedented growth.","这座城市经历了前所未有的增长。","替换 new"),
  ("inevitable","/ɪnˈevɪtəbl/","adj.","不可避免的","Conflict was inevitable in such conditions.","在那种条件下冲突不可避免。","替换 certain"),
  ("feasible","/ˈfiːzəbl/","adj.","可行的","The plan is technically feasible.","该计划在技术上可行。","替换 possible"),
  ("sustainable","/səˈsteɪnəbl/","adj.","可持续的","We need a sustainable energy model.","我们需要可持续的能源模式。","替换 lasting"),
  ("proactive","/ˌprəʊˈæktɪv/","adj.","主动的","Be proactive rather than reactive.","要主动出击而非被动应付。","写作加分"),
  ("cohesive","/kəʊˈhiːsɪv/","adj.","有凝聚力的","The essay lacks a cohesive structure.","这篇文章缺乏连贯的结构。","写作加分"),
  ("conversely","/ˈkɒnvɜːsli/","adv.","相反","Some praised it; conversely, others criticized it.","有人称赞；相反，也有人批评。","逻辑连接"),
  ("thereby","/ˌðeəˈbaɪ/","adv.","从而","Costs fell, thereby boosting profits.","成本下降，从而提高了利润。","逻辑连接"),
  ("notwithstanding","/ˌnɒtwiðˈstændɪŋ/","prep.","尽管","Notwithstanding the risks, he proceeded.","尽管有风险，他仍继续进行。","高分词"),
  ("albeit","/ɔːlˈbiːɪt/","conj.","虽然","The plan helped, albeit modestly.","该计划有帮助，尽管效果有限。","高分词"),
  ("insofar","/ˌɪnsəʊˈfɑː/","adv.","在…范围内","This applies insofar as the law permits.","在法律允许的范围内适用。","高分词"),
 ]),
]

# ---------- 四级 CET-4：六大板块 ----------
CET4 = [
 ("高频动词", [
  ("accommodate","/əˈkɒmədeɪt/","v.","容纳；适应","The hotel can accommodate 300 guests.","这家酒店可容纳三百位客人。","高频"),
  ("acquire","/əˈkwaɪə/","v.","获得；学到","Children acquire language through natural exposure.","儿童通过自然接触习得语言。","高频"),
  ("adapt","/əˈdæpt/","v.","适应；改编","It takes time to adapt to a new environment.","适应新环境需要时间。","高频"),
  ("adopt","/əˈdɒpt/","v.","采纳；收养","The school adopted a new teaching method.","学校采纳了一种新的教学方法。","高频"),
  ("analyse","/ˈænəlaɪz/","v.","分析","Let us analyse the causes of the accident.","让我们分析事故的原因。","写作替换"),
  ("apply","/əˈplaɪ/","v.","申请；应用","She applied for a scholarship abroad.","她申请了出国留学的奖学金。","熟词僻义"),
  ("approve","/əˈpruːv/","v.","批准；赞成","The board approved the new budget.","董事会批准了新预算。","高频"),
  ("assume","/əˈsjuːm/","v.","假定","Don't assume everyone agrees with you.","不要假定所有人都同意你。","熟词僻义"),
  ("attach","/əˈtætʃ/","v.","附上；重视","Please attach your resume to the email.","请将简历附在邮件中。","熟词僻义"),
  ("attempt","/əˈtempt/","v./n.","尝试","He failed the exam twice before passing.","他两次考试不及格后才通过。","高频"),
  ("benefit","/ˈbenɪfɪt/","n./v.","益处；受益","Regular exercise benefits both body and mind.","规律运动对身心都有益。","熟词僻义"),
  ("boost","/buːst/","v./n.","促进；增长","Tourism boosted the local economy.","旅游业促进了当地经济。","写作替换"),
  ("calculate","/ˈkælkjuleɪt/","v.","计算；估计","Calculate the total before paying.","付款前请先计算总额。","高频"),
  ("challenge","/ˈtʃælɪndʒ/","n./v.","挑战","Learning a language is a real challenge.","学一门语言是真正的挑战。","熟词僻义"),
  ("conduct","/kənˈdʌkt/","v.","实施；指挥","Researchers conducted a two-year study.","研究者进行了为期两年的研究。","高频"),
  ("confirm","/kənˈfɜːm/","v.","确认","Please confirm your booking by email.","请通过邮件确认您的预订。","熟词僻义"),
  ("consider","/kənˈsɪdə/","v.","考虑","We are considering several options.","我们正在考虑几个方案。","高频"),
  ("contribute","/kənˈtrɪbjuːt/","v.","贡献；投稿","Regular exercise contributes to good health.","规律运动有助于健康。","写作替换"),
  ("convince","/kənˈvɪns/","v.","说服","He convinced me to change my mind.","他说服我改变了主意。","高频"),
  ("declare","/dɪˈkleə/","v.","宣布；申报","Customs officials declared the goods.","海关人员宣布了这些货物。","熟词僻义"),
  ("deliver","/dɪˈlɪvə/","v.","递送；发表","The speech was delivered without notes.","演讲脱稿进行。","熟词僻义"),
  ("demand","/dɪˈmɑːnd/","n./v.","需求；要求","Demand for electric cars keeps rising.","电动车的需求持续上升。","熟词僻义"),
  ("demonstrate","/ˈdemənstreɪt/","v.","证明；演示","The data demonstrate a clear trend.","数据证明了明显的趋势。","写作提分"),
  ("determine","/dɪˈtɜːmɪn/","v.","决定；查明","Genes partly determine our height.","基因部分决定我们的身高。","熟词僻义"),
  ("develop","/dɪˈveləp/","v.","发展；培养","He developed a habit of reading daily.","他养成了每天阅读的习惯。","高频"),
  ("discover","/dɪˈskʌvə/","v.","发现","Scientists discovered a new species.","科学家发现了一个新物种。","高频"),
  ("display","/dɪˈspleɪ/","v./n.","展示；显示","The chart displays sales by region.","图表展示了各地区销售额。","写作替换"),
  ("divide","/dɪˈvaɪd/","v.","划分；分开","The class is divided into four groups.","班级被分成四组。","高频"),
  ("establish","/ɪˈstæblɪʃ/","v.","建立","The company was established in 1990.","该公司成立于一九九零年。","写作替换"),
  ("estimate","/ˈestɪmeɪt/","v./n.","估计","Experts estimate the cost at one million.","专家估计成本为一百万。","图表题"),
  ("examine","/ɪɡˈzæmɪn/","v.","检查；审查","Researchers examined the data twice.","研究者两次检查了数据。","写作替换"),
  ("expand","/ɪkˈspænd/","v.","扩大","The firm plans to expand overseas.","公司计划向海外扩张。","写作替换"),
  ("explore","/ɪkˈsplɔː/","v.","探索","We explore several options in the paper.","我们在论文中探讨了若干方案。","写作替换"),
  ("gain","/ɡeɪn/","n./v.","获得；增加","He gained valuable experience abroad.","他在国外获得了宝贵经验。","熟词僻义"),
  ("generate","/ˈdʒenəreɪt/","v.","产生","The policy generated heated debate.","该政策引发了激烈辩论。","写作替换"),
  ("identify","/aɪˈdentɪfaɪ/","v.","识别；确认","Researchers identified three risk factors.","研究者确认了三个风险因素。","写作提分"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明；举例","Let me illustrate this with an example.","让我用一个例子说明。","写作提分"),
  ("impress","/ɪmˈpres/","v.","使印象深刻","Her speech impressed everyone.","她的演讲给所有人留下深刻印象。","高频"),
  ("improve","/ɪmˈpruːv/","v.","改善","Reading widely improves your writing.","广泛阅读能改善你的写作。","写作替换"),
  ("include","/ɪnˈkluːd/","v.","包括","The price includes breakfast.","价格含早餐。","熟词僻义"),
  ("increase","/ɪnˈkriːs/","v./n.","增加","Sales increased by 15 percent.","销售增长了百分之十五。","图表题"),
  ("indicate","/ˈɪndɪkeɪt/","v.","表明","The survey indicates growing interest.","调查显示兴趣在增长。","图表题"),
  ("influence","/ˈɪnfluəns/","n./v.","影响","Parents influence children deeply.","父母对孩子影响深远。","写作替换"),
  ("introduce","/ˌɪntrəˈdjuːs/","v.","介绍；引进","The company introduced a new policy.","公司推行了新政策。","写作替换"),
  ("maintain","/meɪnˈteɪn/","v.","维持；保养","It is hard to maintain motivation alone.","独自保持动力很难。","写作替换"),
  ("manage","/ˈmænɪdʒ/","v.","管理；设法做到","He managed to finish on time.","他设法按时完成了。","高频"),
  ("measure","/ˈmeʒə/","v./n.","测量；措施","The government took measures to cut costs.","政府采取措施削减成本。","熟词僻义"),
  ("obtain","/əbˈteɪn/","v.","获得","You must obtain permission first.","你必须先获得许可。","写作替换"),
  ("occur","/əˈkɜː/","v.","发生；想到","The idea occurred to me suddenly.","这个想法突然出现在我脑海。","熟词僻义"),
  ("participate","/pɑːˈtɪsɪpeɪt/","v.","参加","Students may participate in the debate.","学生可以参加辩论。","写作替换"),
  ("perform","/pəˈfɔːm/","v.","执行；表演","The team performed well under pressure.","团队在压力下表现出色。","熟词僻义"),
  ("possess","/pəˈzes/","v.","拥有","He possesses a rare kind of patience.","他拥有一种罕见的耐心。","写作替换"),
  ("prevent","/prɪˈvent/","v.","阻止","Exercise prevents many health problems.","运动能预防许多健康问题。","写作替换"),
  ("produce","/prəˈdjuːs/","v.","生产；产生","The factory produces recycled paper.","这家工厂生产再生纸。","写作替换"),
  ("promote","/prəˈməʊt/","v.","促进；晋升","Exercise promotes both health and happiness.","运动促进健康与快乐。","写作替换"),
  ("provide","/prəˈvaɪd/","v.","提供","The hotel provides free Wi-Fi.","酒店提供免费无线网络。","写作替换"),
  ("realize","/ˈrɪəlaɪz/","v.","意识到；实现","She realized her mistake quickly.","她很快意识到了错误。","熟词僻义"),
  ("receive","/rɪˈsiːv/","v.","收到","Did you receive my email?","你收到我的邮件了吗？","熟词僻义"),
  ("recognize","/ˈrekəɡnaɪz/","v.","认出；承认","He recognized the difficulty of the task.","他认识到任务的困难。","熟词僻义"),
  ("recommend","/ˌrekəˈmend/","v.","推荐","Can you recommend a good hotel?","你能推荐一家好酒店吗？","口语高频"),
  ("reduce","/rɪˈdjuːs/","v.","减少","We should reduce food waste.","我们应当减少食物浪费。","写作替换"),
  ("reflect","/rɪˈflekt/","v.","反映；反思","The result reflects months of effort.","结果反映了数月的努力。","熟词僻义"),
  ("regard","/rɪˈɡɑːd/","v.","认为；n. 关注","I regard him as a reliable partner.","我认为他是可靠的伙伴。","写作提分"),
  ("reject","/rɪˈdʒekt/","v.","拒绝","The committee rejected our proposal.","委员会否决了我们的提案。","写作替换"),
  ("relate","/rɪˈleɪt/","v.","关联；叙述","These two findings relate closely.","这两项发现密切相关。","写作替换"),
  ("release","/rɪˈliːs/","v./n.","发布；释放","The company released its annual report.","公司发布了年度报告。","熟词僻义"),
  ("replace","/rɪˈpleɪs/","v.","取代","Machines cannot fully replace humans.","机器无法完全取代人类。","写作替换"),
  ("require","/rɪˈkwaɪə/","v.","需要；要求","The task requires patience.","这项任务需要耐心。","高频"),
  ("respond","/rɪˈspɒnd/","v.","回应","She responded calmly to the criticism.","她冷静地回应了批评。","写作替换"),
  ("restrict","/rɪˈstrɪkt/","v.","限制","The policy restricts online gaming time.","该政策限制网游时间。","写作替换"),
  ("reveal","/rɪˈviːl/","v.","揭示","The survey revealed a surprising fact.","调查揭示了一个意外的事实。","写作提分"),
  ("schedule","/ˈʃedjuːl/","n./v.","日程；安排","The train is on schedule.","火车正点。","熟词僻义"),
  ("secure","/sɪˈkjʊə/","adj./v.","安全的；获得","She secured a place at a good school.","她获得了一所好学校的名额。","熟词僻义"),
  ("seek","/siːk/","v.","寻求","He is seeking a solution to the problem.","他正在寻求解决办法。","写作替换"),
  ("sensitive","/ˈsensətɪv/","adj.","敏感的","This topic is politically sensitive.","这个话题在政治上很敏感。","写作提分"),
  ("serve","/sɜːv/","v.","服务；供应","The restaurant serves breakfast until ten.","这家餐厅供应早餐到十点。","熟词僻义"),
  ("settle","/ˈsetl/","v.","解决；定居","They settled the dispute peacefully.","他们和平解决了纠纷。","写作替换"),
  ("significant","/sɪɡˈnɪfɪkənt/","adj.","显著的","There was a significant drop in sales.","销量显著下降。","写作提分"),
  ("solve","/sɒlv/","v.","解决","Education can solve many social problems.","教育能解决许多社会问题。","写作替换"),
  ("spread","/spred/","v.","传播；蔓延","The rumor spread quickly online.","谣言在网上迅速传播。","熟词僻义"),
  ("stress","/stres/","n./v.","压力；强调","Teachers often stress the importance of review.","老师常强调复习的重要性。","熟词僻义"),
  ("succeed","/səkˈsiːd/","v.","成功；接替","Few succeed without repeated failure.","很少有人不经历失败就成功。","写作替换"),
  ("suggest","/səˈdʒest/","v.","建议；暗示","I suggest we start earlier.","我建议我们早点出发。","熟词僻义"),
  ("supply","/səˈplaɪ/","v./n.","供应","The company supplies parts to car makers.","公司为汽车厂商供应零部件。","熟词僻义"),
  ("support","/səˈpɔːt/","v./n.","支持","The data support his conclusion.","数据支持他的结论。","写作替换"),
  ("survive","/səˈvaɪv/","v.","幸存；存活","Few small shops survived the crisis.","危机中只有少数小店幸存。","熟词僻义"),
  ("tend","/tend/","v.","倾向于","People tend to remember stories better.","人们倾向于更好地记住故事。","写作替换"),
  ("transfer","/trænsˈfɜː/","v./n.","转移；换乘","She transferred to another department.","她调到了另一个部门。","熟词僻义"),
  ("treat","/triːt/","v.","对待；治疗","Teachers should treat every student fairly.","老师应公平对待每个学生。","写作替换"),
  ("trust","/trʌst/","n./v.","信任","Trust takes years to build.","信任需要多年才能建立。","熟词僻义"),
  ("urge","/ɜːdʒ/","v./n.","敦促；冲动","Doctors urge people to exercise regularly.","医生敦促人们经常锻炼。","写作提分"),
  ("vary","/ˈveəri/","v.","变化；不同","Opinions vary from person to person.","观点因人而异。","写作替换"),
  ("witness","/ˈwɪtnəs/","v./n.","目击；见证","We witnessed a rapid change.","我们见证了一次迅速的变化。","熟词僻义"),
 ]),
 ("高频名词", [
  ("abundance","/əˈbʌndəns/","n.","丰富；充裕","There is an abundance of natural resources.","自然资源丰富。","图表题"),
  ("academic","/ˌækəˈdemɪk/","adj./n.","学术的；学者","Her academic performance improved greatly.","她的学业表现大幅提高。","高频"),
  ("access","/ˈækses/","n./v.","通道；访问权","Students have free access to the library.","学生可免费使用图书馆。","熟词僻义"),
  ("achievement","/əˈtʃiːvmənt/","n.","成就","Winning the award was a great achievement.","获奖是一项了不起的成就。","写作替换"),
  ("advantage","/ədˈvɑːntɪdʒ/","n.","优势；好处","Speaking two languages is a big advantage.","会两门语言是很大优势。","写作替换"),
  ("affect","/əˈfekt/","v.","影响","Weather affects our mood strongly.","天气强烈影响着我们的情绪。","熟词僻义"),
  ("alternative","/ɔːlˈtɜːnətɪv/","n./adj.","替代品；可供选择的","Cycling is a cheap alternative to driving.","骑车是开车的一种便宜替代方式。","写作替换"),
  ("approach","/əˈprəʊtʃ/","n./v.","方法；接近","We need a fresh approach to the problem.","我们需要用新方法处理这个问题。","写作提分"),
  ("aspect","/ˈæspekt/","n.","方面","Consider every aspect before deciding.","决定前要考虑每个方面。","写作替换"),
  ("assistance","/əˈsɪstəns/","n.","帮助","Financial assistance is available to students.","学生可获得经济援助。","听力高频"),
  ("attempt","/əˈtempt/","n.","尝试","His first attempt at driving failed.","他第一次学开车失败了。","熟词僻义"),
  ("benefit","/ˈbenɪfɪt/","n.","好处","The benefits of exercise are widely known.","运动的好处广为人知。","写作替换"),
  ("budget","/ˈbʌdʒɪt/","n./v.","预算","We must stick to the budget.","我们必须坚持预算。","熟词僻义"),
  ("campaign","/kæmˈpeɪn/","n.","运动；战役","The government launched an anti-smoking campaign.","政府发起了一场禁烟运动。","新闻高频"),
  ("career","/kəˈrɪə/","n.","职业；生涯","A career change can be challenging.","转换职业可能很有挑战。","熟词僻义"),
  ("circumstance","/ˈsɜːkəmstəns/","n.","情况；环境","Under no circumstances should you quit.","在任何情况下你都不该放弃。","熟词僻义"),
  ("community","/kəˈmjuːnəti/","n.","社区","The whole community joined the clean-up.","整个社区都参加了清洁行动。","写作替换"),
  ("competition","/ˌkɒmpəˈtɪʃn/","n.","竞争；比赛","The competition was extremely intense.","竞争异常激烈。","写作替换"),
  ("consequence","/ˈkɒnsɪkwəns/","n.","后果","He accepted the consequences calmly.","他冷静地承担了后果。","熟词僻义"),
  ("contract","/ˈkɒntrækt/","n.","合同","Please read the contract carefully.","请仔细阅读合同。","熟词僻义"),
  ("crisis","/ˈkraɪsɪs/","n.","危机","The country is facing a housing crisis.","该国正面临住房危机。","新闻高频"),
  ("culture","/ˈkʌltʃə/","n.","文化","Food is an important part of culture.","食物是文化的重要组成部分。","写作替换"),
  ("decline","/dɪˈklaɪn/","v./n.","下降；婉拒","Sales declined for three straight months.","销售连续三个月下降。","图表题"),
  ("demand","/dɪˈmɑːnd/","n.","需求","Demand for online courses keeps growing.","对在线课程的需求持续增长。","图表题"),
  ("development","/dɪˈveləpmənt/","n.","发展；开发","The city's development has been rapid.","这座城市发展迅速。","图表题"),
  ("difference","/ˈdɪfrəns/","n.","差异","The difference between them is minimal.","他们之间的差别很小。","写作替换"),
  ("education","/ˌedʒuˈkeɪʃn/","n.","教育","Education should be equally accessible.","教育应当人人可及。","写作替换"),
  ("effect","/ɪˈfekt/","n.","影响；效果","The medicine had a mild effect.","这药效果温和。","熟词僻义"),
  ("effort","/ˈefət/","n.","努力","With sustained effort you will improve.","持续努力你会进步。","写作替换"),
  ("environment","/ɪnˈvaɪrənmənt/","n.","环境","We must protect the environment.","我们必须保护环境。","写作替换"),
  ("equipment","/ɪˈkwɪpmənt/","n.","设备（不可数）","The lab bought new equipment.","实验室购置了新设备。","语法点"),
  ("event","/ɪˈvent/","n.","事件；活动","The conference is a major event.","这场会议是重大活动。","熟词僻义"),
  ("evidence","/ˈevɪdəns/","n.","证据（不可数）","There is no evidence to support that.","没有证据支持那一点。","语法点"),
  ("experience","/ɪkˈspɪəriəns/","n./v.","经验；经历","Work experience matters a lot here.","工作经验在这里很重要。","熟词僻义"),
  ("factor","/ˈfæktə/","n.","因素","Cost is the decisive factor.","成本是决定性因素。","写作替换"),
  ("failure","/ˈfeɪljə/","n.","失败","Failure teaches valuable lessons.","失败带来宝贵教训。","写作替换"),
  ("feature","/ˈfiːtʃə/","n.","特点","The main feature of the app is simplicity.","这款应用的主要特点是简洁。","写作替换"),
  ("figure","/ˈfɪɡə/","n.","数字；人物","The figures speak for themselves.","数字本身说明问题。","图表题"),
  ("function","/ˈfʌŋkʃn/","n./v.","功能；运转","The button has a dual function.","这个按钮有双重功能。","熟词僻义"),
  ("goal","/ɡəʊl/","n.","目标","Set a clear goal and stick to it.","设定明确目标并坚持。","写作替换"),
  ("growth","/ɡrəʊθ/","n.","增长","The company recorded steady growth.","公司实现了稳定增长。","图表题"),
  ("income","/ˈɪnkʌm/","n.","收入","Their income doubled in five years.","他们的收入五年翻了一番。","图表题"),
  ("industry","/ˈɪndəstri/","n.","工业；行业","The tourism industry recovered slowly.","旅游业缓慢复苏。","图表题"),
  ("influence","/ˈɪnfluəns/","n.","影响力","Teachers have lasting influence on students.","教师对学生有持久影响。","写作替换"),
  ("knowledge","/ˈnɒlɪdʒ/","n.","知识（不可数）","Knowledge grows when shared.","知识越分享越增长。","写作替换"),
  ("labor","/ˈleɪbə/","n.","劳动；劳动力","Labor costs rose by ten percent.","劳动力成本上涨了百分之十。","图表题"),
  ("level","/ˈlevl/","n.","水平；级别","The level of English has improved.","英语水平提高了。","熟词僻义"),
  ("limit","/ˈlɪmɪt/","n./v.","限制","There is a time limit on the test.","考试有时间限制。","熟词僻义"),
  ("measure","/ˈmeʒə/","n.","措施","The government took strong measures.","政府采取了有力措施。","写作替换"),
  ("method","/ˈmeθəd/","n.","方法","This method saves both time and money.","这个方法既省时又省钱。","写作替换"),
  ("opportunity","/ˌɒpəˈtjuːnəti/","n.","机会","Don't miss this opportunity.","别错过这个机会。","写作替换"),
  ("percentage","/pəˈsentɪdʒ/","n.","百分比","A high percentage of students passed.","很高比例的学生通过了。","图表题"),
  ("period","/ˈpɪəriəd/","n.","时期；一段时间","The period from 2010 to 2015 was stable.","二零一零到二零一五年这段时期很稳定。","图表题"),
  ("policy","/ˈpɒləsi/","n.","政策","The new policy takes effect in May.","新政策五月生效。","新闻高频"),
  ("population","/ˌpɒpjuˈleɪʃn/","n.","人口","The population aged rapidly over the decade.","这十年人口迅速老龄化。","图表题"),
  ("process","/ˈprəʊses/","n.","过程","Learning is a slow process.","学习是一个缓慢的过程。","写作替换"),
  ("progress","/ˈprəʊɡres/","n./v.","进步","He has made remarkable progress.","他取得了显著进步。","写作替换"),
  ("purpose","/ˈpɜːpəs/","n.","目的","The purpose of the study is clear.","这项研究的目的很明确。","写作替换"),
  ("quality","/ˈkwɒləti/","n.","质量；品质","Quality matters more than quantity.","质量比数量更重要。","写作替换"),
  ("rate","/reɪt/","n.","比率；速度","The unemployment rate fell slightly.","失业率略有下降。","图表题"),
  ("reason","/ˈriːzn/","n.","原因；理由","The main reason is a lack of practice.","主要原因是缺乏练习。","写作替换"),
  ("research","/rɪˈsɜːtʃ/","n./v.","研究","Recent research supports this view.","近期研究支持这一观点。","学术词"),
  ("resource","/rɪˈsɔːs/","n.","资源","Water is a limited resource.","水是有限的资源。","图表题"),
  ("result","/rɪˈzʌlt/","n.","结果","The result surprised everyone.","结果让每个人都很惊讶。","熟词僻义"),
  ("role","/rəʊl/","n.","作用；角色","Teachers play a key role in development.","教师在发展中起关键作用。","写作替换"),
  ("sense","/sens/","n.","感觉；意义","The word has a double sense here.","这个词在这里有双重含义。","熟词僻义"),
  ("series","/ˈsɪəriːz/","n.","系列","A series of reforms was introduced.","进行了一系列改革。","熟词僻义"),
  ("significance","/sɪɡˈnɪfɪkəns/","n.","重要性","He explained the significance of the discovery.","他解释了这一发现的重要性。","学术词"),
  ("situation","/ˌsɪtʃuˈeɪʃn/","n.","情况","The situation has improved since then.","情况自那以后已经改善。","写作替换"),
  ("solution","/səˈluːʃn/","n.","解决办法","There is no easy solution to poverty.","贫困没有简单的解决办法。","写作替换"),
  ("source","/sɔːs/","n.","来源","Always cite your sources.","务必注明你的资料来源。","学术词"),
  ("standard","/ˈstændəd/","n./adj.","标准","The standard is set by the government.","标准由政府制定。","熟词僻义"),
  ("stress","/stres/","n.","压力","Students face great academic stress.","学生们面临很大的学业压力。","熟词僻义"),
  ("structure","/ˈstrʌktʃə/","n.","结构","The essay has a clear structure.","这篇文章结构清晰。","写作替换"),
  ("success","/səkˈses/","n.","成功","Success comes from steady effort.","成功来自持续努力。","写作替换"),
  ("suggestion","/səˈdʒestʃən/","n.","建议","Thank you for your helpful suggestions.","感谢你有帮助的建议。","口语高频"),
  ("system","/ˈsɪstəm/","n.","系统","The education system needs reform.","教育系统需要改革。","写作替换"),
  ("target","/ˈtɑːɡɪt/","n./v.","目标；针对","We have reached our sales target.","我们达到了销售目标。","图表题"),
  ("technology","/tekˈnɒlədʒi/","n.","技术","Technology has transformed education.","技术改变了教育。","写作替换"),
  ("term","/tɜːm/","n.","术语；学期","In academic terms, the result is significant.","从学术角度看，这个结果很重要。","熟词僻义"),
  ("theme","/θiːm/","n.","主题","The theme of the speech is hope.","演讲的主题是希望。","写作替换"),
  ("threat","/θret/","n.","威胁","Pollution poses a serious threat.","污染构成严重威胁。","写作替换"),
  ("trend","/trend/","n.","趋势","The trend is clearly upward.","趋势明显上升。","图表题"),
  ("value","/ˈvæljuː/","n./v.","价值；重视","We value your feedback highly.","我们高度重视你的反馈。","写作替换"),
  ("variety","/vəˈraɪəti/","n.","多样性；种类","A variety of books are on display.","展出了种类繁多的书籍。","写作替换"),
  ("view","/vjuː/","n./v.","观点；看待","In my view, the plan is workable.","在我看来，这个计划可行。","写作替换"),
 ]),
 ("高频形容词与副词", [
  ("accurate","/ˈækjərət/","adj.","准确的","Please give an accurate account.","请给出准确的描述。","写作提分"),
  ("actual","/ˈæktʃuəl/","adj.","实际的；真正的","The actual cost was much higher.","实际成本高得多。","熟词僻义"),
  ("annual","/ˈænjuəl/","adj.","每年的","The annual report comes out in March.","年报三月出版。","图表题"),
  ("apparent","/əˈpærənt/","adj.","明显的","It soon became apparent that he was right.","很快就明显看出他是对的。","熟词僻义"),
  ("appropriate","/əˈprəʊpriət/","adj.","适当的","Choose words appropriate to the audience.","选择适合听众的用词。","写作提分"),
  ("basic","/ˈbeɪsɪk/","adj.","基本的","We only covered basic concepts.","我们只讲了基本概念。","写作替换"),
  ("brief","/briːf/","adj.","简短的","He gave a brief introduction.","他作了简短介绍。","写作替换"),
  ("certain","/ˈsɜːtn/","adj.","确定的；某些","I am certain of the result.","我确信这个结果。","熟词僻义"),
  ("clear","/klɪə/","adj./v.","清楚的；清除","Make your answer clear and brief.","答案要清楚简要。","写作替换"),
  ("common","/ˈkɒmən/","adj.","常见的；共同的","This is a common mistake.","这是个常见错误。","写作替换"),
  ("complex","/ˈkɒmpleks/","adj.","复杂的","The issue is more complex than it seems.","问题比看上去复杂。","写作替换"),
  ("crucial","/ˈkruːʃl/","adj.","至关重要的","The first step is crucial.","第一步至关重要。","写作替换"),
  ("direct","/dəˈrekt/","adj./v.","直接的；指导","Take a direct route to the office.","直接走那条路去办公室。","熟词僻义"),
  ("efficient","/ɪˈfɪʃnt/","adj.","高效的","This is a more efficient method.","这是更高效的方法。","写作替换"),
  ("enormous","/ɪˈnɔːməs/","adj.","巨大的","The project required enormous effort.","该项目需要巨大的努力。","写作替换"),
  ("essential","/ɪˈsenʃl/","adj.","必要的","Water is essential to life.","水对生命至关重要。","写作替换"),
  ("familiar","/fəˈmɪliə/","adj.","熟悉的","Are you familiar with this software?","你熟悉这个软件吗？","口语高频"),
  ("frequent","/ˈfriːkwənt/","adj.","频繁的","He is a frequent visitor here.","他是这里的常客。","熟词僻义"),
  ("gradual","/ˈɡrædʒuəl/","adj.","逐渐的","There has been gradual progress.","已经取得逐步进展。","写作替换"),
  ("immediate","/ɪˈmiːdiət/","adj.","立即的","We need an immediate response.","我们需要立即回应。","口语高频"),
  ("independent","/ˌɪndɪˈpendənt/","adj.","独立的","She is financially independent.","她经济独立。","写作替换"),
  ("main","/meɪn/","adj.","主要的","What is the main reason for this?","这是什么的主要原因？","写作替换"),
  ("minor","/ˈmaɪnə/","adj.","次要的","These are only minor differences.","这些只是小差别。","熟词僻义"),
  ("moderate","/ˈmɒdərət/","adj.","适度的；温和的","Moderate exercise is enough.","适度运动就足够了。","写作替换"),
  ("obvious","/ˈɒbviəs/","adj.","明显的","The answer is obvious to everyone.","答案对每个人都是显而易见的。","写作替换"),
  ("permanent","/ˈpɜːmənənt/","adj.","永久的","He took a permanent position.","他获得了一个长期职位。","熟词僻义"),
  ("possible","/ˈpɒsəbl/","adj.","可能的","Come as soon as possible.","尽快来。","口语高频"),
  ("practical","/ˈpræktɪkl/","adj.","实用的","We need practical solutions.","我们需要实用的解决方案。","写作替换"),
  ("previous","/ˈpriːviəs/","adj.","先前的","Please refer to the previous chapter.","请参阅上一章。","熟词僻义"),
  ("primary","/ˈpraɪməri/","adj.","主要的；初级的","Our primary goal is safety.","我们的首要目标是安全。","写作替换"),
  ("private","/ˈpraɪvət/","adj.","私人的","This is a private matter.","这是私事。","熟词僻义"),
  ("proper","/ˈprɒpə/","adj.","适当的","Use proper tools for the job.","用合适的工具做这件事。","写作替换"),
  ("recent","/ˈriːsnt/","adj.","最近的","In recent years, habits have changed.","近年来习惯发生了变化。","图表题"),
  ("relevant","/ˈreləvənt/","adj.","相关的","Please include relevant examples.","请给出相关的例子。","写作提分"),
  ("reliable","/rɪˈlaɪəbl/","adj.","可靠的","He is a reliable teammate.","他是可靠的队友。","写作替换"),
  ("significant","/sɪɡˈnɪfɪkənt/","adj.","显著的","There was a significant improvement.","有显著的改善。","写作替换"),
  ("similar","/ˈsɪmələ/","adj.","相似的","Their views are similar to ours.","他们的观点与我们相似。","熟词僻义"),
  ("simple","/ˈsɪmpl/","adj.","简单的","The rule is simple to follow.","这条规则很好遵守。","写作替换"),
  ("specific","/spəˈsɪfɪk/","adj.","具体的","Could you be more specific?","你能更具体一点吗？","口语高频"),
  ("sudden","/ˈsʌdn/","adj.","突然的","There was a sudden change in policy.","政策突然变了。","熟词僻义"),
  ("suitable","/ˈsuːtəbl/","adj.","合适的","This film is suitable for children.","这部电影适合儿童观看。","口语高频"),
  ("typical","/ˈtɪpɪkl/","adj.","典型的","It is a typical example.","这是个典型的例子。","写作替换"),
  ("unique","/juˈniːk/","adj.","独特的","Every child is unique.","每个孩子都是独特的。","写作替换"),
  ("urgent","/ˈɜːdʒənt/","adj.","紧急的","This is an urgent matter.","这是件紧急的事。","口语高频"),
  ("valuable","/ˈvæljuəbl/","adj.","宝贵的","Your advice is very valuable.","你的建议非常宝贵。","写作替换"),
  ("various","/ˈveəriəs/","adj.","各种各样的","We tried various approaches.","我们尝试了各种方法。","写作替换"),
  ("voluntary","/ˈvɒləntri/","adj.","自愿的","Participation is entirely voluntary.","参与完全自愿。","图表题"),
  ("adequate","/ˈædɪkwət/","adj.","足够的","Make sure you get adequate sleep.","确保你有充足的睡眠。","写作替换"),
  ("approximate","/əˈprɒksɪmət/","adj.","大约的","The approximate cost is fifty yuan.","大约成本是五十元。","图表题"),
  ("flexible","/ˈfleksəbl/","adj.","灵活的","Our schedule is quite flexible.","我们的日程很灵活。","口语高频"),
  ("ideal","/aɪˈdɪəl/","adj.","理想的","This is an ideal place to study.","这是个理想的学习地点。","口语高频"),
  ("massive","/ˈmæsɪv/","adj.","巨大的","The project required massive investment.","该项目需要巨额投资。","新闻高频"),
  ("tiny","/ˈtaɪni/","adj.","微小的","A tiny mistake cost the team a prize.","一个小错误让团队错失奖项。","写作替换"),
 ]),
 ("写作提分词", [
  ("advocate","/ˈædvəkeɪt/","v./n.","提倡；支持者","Some advocate stricter gun laws.","有人主张更严格的枪支法。","写作提分"),
  ("allocate","/ˈæləkeɪt/","v.","分配","Allocate more time to revision.","多分配些时间复习。","图表题"),
  ("comprehensive","/ˌkɒmprɪˈhensɪv/","adj.","全面的","The report gives a comprehensive overview.","报告给出了全面的概述。","写作提分"),
  ("consequently","/ˈkɒnsɪkwəntli/","adv.","因此","The data was flawed; consequently, the claim failed.","数据有缺陷，因此该主张不成立。","逻辑词"),
  ("considerable","/kənˈsɪdərəbl/","adj.","相当大的","The project required considerable funding.","该项目需要相当多的资金。","图表题"),
  ("contradict","/ˌkɒntrəˈdɪkt/","v.","与…矛盾","The two reports contradict each other.","两份报告相互矛盾。","写作提分"),
  ("crucial","/ˈkruːʃl/","adj.","关键","Evidence is crucial to the argument.","证据对该论证至关重要。","写作提分"),
  ("cultivate","/ˈkʌltɪveɪt/","v.","培养","Schools should cultivate creativity.","学校应培养创造力。","写作提分"),
  ("demonstrate","/ˈdemənstreɪt/","v.","证明","The study demonstrates a clear link.","研究证明了明确的关联。","写作提分"),
  ("diminish","/dɪˈmɪnɪʃ/","v.","减少","Interest has diminished over the years.","多年来兴趣逐渐减弱。","图表题"),
  ("elaborate","/ɪˈlæbərət/","v.","详述","Could you elaborate on that?","你能详细说说吗？","口语提分"),
  ("eliminate","/ɪˈlɪmɪneɪt/","v.","消除","We must eliminate unnecessary steps.","我们必须去掉不必要的步骤。","写作提分"),
  ("emphasize","/ˈemfəsaɪz/","v.","强调","I cannot emphasize this enough.","我无法过分强调这一点。","写作提分"),
  ("enhance","/ɪnˈhɑːns/","v.","增强","Reading enhances vocabulary.","阅读能扩充词汇量。","写作提分"),
  ("ensure","/ɪnˈʃʊə/","v.","确保","Please ensure the door is locked.","请确保门已锁好。","口语高频"),
  ("evaluate","/ɪˈvæljueɪt/","v.","评估","We must evaluate the risks first.","我们必须先评估风险。","写作提分"),
  ("facilitate","/fəˈsɪlɪteɪt/","v.","促进","The tool facilitates collaboration.","该工具促进了协作。","写作提分"),
  ("generate","/ˈdʒenəreɪt/","v.","产生","The trend generated fierce debate.","这一趋势引发了激烈辩论。","写作提分"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明","The case illustrates the danger.","这个案例说明了危险所在。","写作提分"),
  ("implement","/ˈɪmplɪment/","v.","实施","The policy was implemented in stages.","该政策分阶段实施。","新闻高频"),
  ("indicate","/ˈɪndɪkeɪt/","v.","表明","Results indicate a steady rise.","结果表明稳定上升。","图表题"),
  ("interpret","/ɪnˈtɜːprɪt/","v.","解释","How do you interpret this data?","你如何解读这些数据？","学术词"),
  ("justify","/ˈdʒʌstɪfaɪ/","v.","证明…合理","Nothing justifies spending so much.","没有什么能证明花这么多是合理的。","写作提分"),
  ("maintain","/meɪnˈteɪn/","v.","坚持认为","He maintains that the theory is sound.","他坚持认为该理论是可靠的。","学术词"),
  ("minimize","/ˈmɪnɪmaɪz/","v.","最小化","We minimized the risk through testing.","我们通过测试把风险降到最低。","写作提分"),
  ("notion","/ˈnəʊʃn/","n.","观念","He rejected the notion of innate talent.","他反对天赋固有的观念。","熟词僻义"),
  ("perceive","/pəˈsiːv/","v.","察觉","Students often perceive exams as stressful.","学生常把考试视为压力源。","学术词"),
  ("pursue","/pəˈsjuː/","v.","追求；从事","She pursued a career in law.","她从事法律职业。","写作提分"),
  ("refine","/rɪˈfaɪn/","v.","改进","We refined the method after testing.","测试后我们改进了方法。","学术词"),
  ("reveal","/rɪˈviːl/","v.","揭示","The data revealed an unexpected pattern.","数据显示出一个意外的模式。","写作提分"),
  ("significant","/sɪɡˈnɪfɪkənt/","adj.","显著的","There is a significant difference.","存在显著差异。","图表题"),
  ("sustain","/səˈsteɪn/","v.","维持","We must sustain current momentum.","我们必须保持当前势头。","写作提分"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱","The scandal undermined public trust.","丑闻削弱了公众信任。","写作提分"),
  ("utilize","/ˈjuːtəlaɪz/","v.","利用","We should utilize existing resources.","我们应该利用现有资源。","写作提分"),
  ("verify","/ˈverɪfaɪ/","v.","核实","Please verify the figures before use.","使用前请核实数据。","学术词"),
 ]),
 ("听力场景高频", [
  ("aisle","/aɪl/","n.","过道","Could you take aisle 24 for me?","能麻烦您帮我拿 24 通道的吗？","机场"),
  ("baggage","/ˈbæɡɪdʒ/","n.","行李（不可数）","My baggage did not arrive.","我的行李没到。","机场"),
  ("boarding","/ˈbɔːdɪŋ/","n.","登机","Boarding begins at nine thirty.","九点半开始登机。","机场"),
  ("booking","/ˈbʊkɪŋ/","n.","预订","Please show your booking reference.","请出示您的预订编号。","酒店"),
  ("brochure","/ˈbrəʊʃə/","n.","宣传册","Take a brochure from the desk.","从前台取一本宣传册。","旅游"),
  ("currency","/ˈkʌrənsi/","n.","货币","Where can I exchange currency?","我在哪里换钱？","银行"),
  ("deposit","/dɪˈpɒzɪt/","n./v.","押金；存入","The hotel requires a deposit.","酒店要求押金。","银行"),
  ("destination","/ˌdestɪˈneɪʃn/","n.","目的地","We are heading to a small town.","我们要去一个小镇。","旅游"),
  ("discount","/ˈdɪskaʊnt/","n.","折扣","Is there a student discount?","有学生折扣吗？","购物"),
  ("itinerary","/aɪˈtɪnərəri/","n.","行程单","The tour includes a full itinerary.","旅行包含完整行程。","旅游"),
  ("luggage","/ˈlʌɡɪdʒ/","n.","行李（不可数）","Please keep your luggage with you.","请随身携带行李。","机场"),
  ("passport","/ˈpɑːspɔːt/","n.","护照","May I see your passport, please?","请出示您的护照好吗？","出入境"),
  ("platform","/ˈplætfɔːm/","n.","站台","The train leaves from platform three.","列车从三号站台发车。","车站"),
  ("receipt","/rɪˈsiːt/","n.","收据","Please keep the receipt for returns.","退货请保留收据。","购物"),
  ("reservation","/ˌrezəˈveɪʃn/","n.","预订","I have a reservation under Chen.","我有一个用陈预订的房间。","酒店"),
  ("schedule","/ˈʃedjuːl/","n.","时刻表","According to the schedule, it leaves at noon.","根据时刻表，十二点出发。","车站"),
  ("terminal","/ˈtɜːmɪnl/","n.","航站楼","Your flight departs from terminal two.","你的航班从二号航站楼起飞。","机场"),
  ("transfer","/trænsˈfɜː/","v./n.","转乘","You need a transfer at the next station.","你需要在下一站换乘。","车站"),
  ("warranty","/ˈwɒrənti/","n.","保修单","The device comes with a two-year warranty.","这台设备有两年保修。","购物"),
  ("appointment","/əˈpɔɪntmənt/","n.","预约","I have an appointment with Dr. Lee.","我预约了李医生。","医院"),
  ("prescription","/prɪˈskrɪpʃn/","n.","处方","You need a prescription for this drug.","这药需要处方。","医院"),
  ("symptom","/ˈsɪmptəm/","n.","症状","Describe your symptoms in detail.","详细描述你的症状。","医院"),
  ("insurance","/ɪnˈʃʊərəns/","n.","保险","Travel insurance covers cancellations.","旅行保险涵盖取消情形。","保险"),
  ("wage","/weɪdʒ/","n.","工资","The minimum wage rose in July.","最低工资在七月上涨了。","职场"),
  ("interview","/ˈɪntəvjuː/","n./v.","面试","I have an interview next Monday.","我下周一有个面试。","职场"),
  ("overtime","/ˈəʊvətaɪm/","n.","加班","He worked overtime all week.","他整周都在加班。","职场"),
  ("shift","/ʃɪft/","n.","轮班；转变","I work the night shift this month.","这个月我上夜班。","职场"),
  ("colleague","/ˈkɒliːɡ/","n.","同事","My colleagues are very supportive.","我的同事非常 supportive。","职场"),
 ]),
]

BOOKS = [
    {"key": "ky", "level": "ky", "name": "考研英语", "stage": "考研", "mod": "ky",
     "note": "考研大纲约 5500 词，真题高频约 1500 词（复现率 60%+）。本词书按真题功能分块：高频动词 / 熟词僻义陷阱 / 逻辑与态度词 / 写作提分替换词，均配真题式例句。",
     "groups": KY},
    {"key": "cet4", "level": "cet4", "name": "大学英语四级 CET-4", "stage": "四六级", "mod": "cet4",
     "note": "四级核心约 4500 词，侧重常见词的准确用法与基础学术场景。本词书覆盖：高频动词 / 高频名词 / 高频形容词与副词 / 写作提分词 / 听力场景高频。",
     "groups": CET4},
]

def build():
    out = {}
    for bk in BOOKS:
        books = []
        total = 0
        for gi, (gname, words) in enumerate(bk["groups"], 1):
            ws = []
            for wi, w in enumerate(words, 1):
                word, phonetic, pos, meaning, sent, sentcn, tag = w
                ws.append({
                    "id": "%s-g%d-w%d" % (bk["key"], gi, wi),
                    "word": word,
                    "phonetic": phonetic,
                    "pos": pos,
                    "meaning": meaning,
                    "tag": tag,
                    "freq": tag in ("高频", "写作替换", "写作提分", "替换 important") and "high" or "mid",
                    "sentence": sent,
                    "sentenceCn": sentcn,
                    "audio": "",       # 稍后由 TTS 脚本补齐
                })
            total += len(ws)
            books.append({
                "id": "%s-g%d" % (bk["key"], gi),
                "title": gname,
                "words": ws,
            })
        out[bk["key"]] = {
            "product": "%s · 词汇记忆" % bk["name"],
            "version": "1.0",
            "schema_version": "1.0",
            "note": bk["note"] + " 内容由 AI 整理，待人工校对。",
            "level": bk["level"],
            "stage": bk["stage"],
            "mod": bk["mod"],
            "books": [{"id": bk["key"], "title": bk["name"], "units": books}],
        }
        print("%-8s %-22s %2d 组 %4d 词" % (bk["key"], bk["name"], len(bk["groups"]), total))
    return out

def main():
    out = build()
    for key, data in out.items():
        p = os.path.join(DATA, "vocab_%s.json" % key)
        with io.open(p, "w", encoding="utf-8") as f:
            f.write(json.dumps(data, ensure_ascii=False, indent=1))
        # 校验
        with io.open(p, encoding="utf-8") as f:
            d = json.load(f)
        words = d["books"][0]["units"]
        n = sum(len(u["words"]) for u in words)
        ids = [w["id"] for u in words for w in u["words"]]
        noex = [w["word"] for u in words for w in u["words"] if not w["sentence"]]
        print("  -> %s (%.0f KB)  词 %d  例句缺失 %d  id 唯一 %s"
              % (os.path.basename(p), os.path.getsize(p) / 1024.0, n, len(noex),
                 "是" if len(set(ids)) == len(ids) else "否"))
        if noex:
            print("     缺例句: %s" % noex[:5])

if __name__ == "__main__":
    main()
