# -*- coding: utf-8 -*-
"""第二批考试词书：六级 CET-6 / 八级 TEM-8 / 雅思 IELTS / 托福 TOEFL / 出国生活流水。

分组依据（市场调研）：
- 六级：重「一词多义 / 熟词僻义 / 抽象高频 / 翻译与写作高级词 / 讲座新闻词 / 固定搭配」
- 八级：英美语言文学 + 翻译（TEM-8 考 deep 文学与翻译），词汇量小但深度高
- 雅思：无大纲词表，按四单项分块（阅读同义替换 / 图表 / 论证 / 口语 / 听力 / 话题词）
- 托福：材料来自固定学科池，按学科分块（学术通用 / 自然科学 / 人文社科 / 讲座信号词）
- 出国流水：生活场景（租房/ banking/就医/交通/购物/社交/求职），最强调"能用"

每词含音标、词性、多义释义、真题式例句、例句翻译、考点标签。
输出：data/vocab_<key>.json（与第一批同 schema，可直接被 build_vocab.py 归一化）

用法：python tools/build_exam_books2.py
"""
import io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(HERE), 'data')

# ============ 六级 CET-6 ============
CET6 = [
 ("抽象高频词", [
  ("abstract","/ˈæbstrækt/","adj./n.","抽象的；摘要","The abstract summarizes the main findings.","摘要概括了主要发现。","阅读高频"),
  ("accelerate","/əkˈseləreɪt/","v.","加速；促进","Rising demand accelerated innovation.","需求上升加速了创新。","图表题"),
  ("accumulate","/əˈkjuːmjəleɪt/","v.","积累；积聚","Dust accumulated on the unused shelves.","灰尘在闲置的货架上积聚。","图表题"),
  ("adhere","/ədˈhɪə/","v.","坚持；黏附","Participants must adhere to the rules.","参与者必须遵守规则。","阅读高频"),
  ("allocate","/ˈæləkeɪt/","v.","分配","The government allocated funds to rural schools.","政府向乡村学校分配了资金。","图表题"),
  ("ambiguous","/æmˈbɪɡjuəs/","adj.","模棱两可的","The wording of the clause is ambiguous.","该条款措辞模棱两可。","写作提分"),
  ("analogy","/əˈnælədʒi/","n.","类比","He drew an analogy between memory and storage.","他把记忆类比为存储。","写作提分"),
  ("anticipate","/ænˈtɪsɪpeɪt/","v.","预期","We anticipate a rebound in demand.","我们预期需求会回升。","新闻高频"),
  ("apparent","/əˈpærənt/","adj.","明显的；表面的","It became apparent that the data were biased.","数据存在偏差变得很明显。","熟词僻义"),
  ("arbitrary","/ˈɑːbɪtrəri/","adj.","任意的；武断的","The selection was arbitrary rather than random.","该选拔是武断的而非随机的。","学术词"),
  ("articulate","/ɑːˈtɪkjuleɪt/","v./adj.","清晰表达；口齿清楚的","She articulated her argument with precision.","她精确清晰地表达了论点。","口语高分"),
  ("assessment","/əˈsesmənt/","n.","评估","The assessment results will be published Friday.","评估结果将于周五公布。","听力高频"),
  ("attribute","/əˈtrɪbjuːt/","v.","归因于","She attributes her success to persistence.","她把成功归因于坚持。","翻译高频"),
  ("coherent","/kəʊˈhɪərənt/","adj.","连贯的；一致的","The report lacks a coherent structure.","该报告缺乏连贯结构。","学术词"),
  ("coincide","/ˌkəʊɪnˈsaɪd/","v.","同时发生；一致","The conference coincides with the holiday.","会议与假期时间重合。","熟词僻义"),
  ("commodity","/kəˈmɒdəti/","n.","商品","Commodity prices fluctuated last quarter.","上季度大宗商品价格波动。","图表题"),
  ("compensate","/ˈkɒmpenseɪt/","v.","补偿；弥补","Extra rest compensated for the lack of sleep.","额外休息弥补了睡眠不足。","写作替换"),
  ("comprehensive","/ˌkɒmprɪˈhensɪv/","adj.","全面的","A comprehensive survey was conducted.","进行了一项全面调查。","学术词"),
  ("comprise","/kəmˈpraɪz/","v.","包含；组成","The book comprises twelve chapters.","该书包含十二章。","阅读高频"),
  ("conceive","/kənˈsiːv/","v.","构思；设想","I can't conceive of a better solution.","我想不出更好的办法。","熟词僻义"),
  ("concurrent","/kənˈkʌrənt/","adj.","同时发生的","Two meetings were held concurrently.","两场会议同时举行。","熟词僻义"),
  ("conform","/kənˈfɔːm/","v.","遵守；符合","Products must conform to safety rules.","产品必须符合安全规定。","阅读高频"),
  ("consecutive","/kənˈsekjətɪv/","adj.","连续的","Sales fell for three consecutive years.","销售连续三年下滑。","图表题"),
  ("constitute","/ˈkɒnstɪtjuːt/","v.","构成","Women constitute half of the workforce.","女性占劳动力一半。","图表题"),
  ("contemporary","/kənˈtemprəri/","adj.","当代的；同时代的","Contemporary art attracts young visitors.","当代艺术吸引年轻参观者。","写作替换"),
  ("contradict","/ˌkɒntrəˈdɪkt/","v.","反驳；矛盾","The two witnesses contradict each other.","两位证人的说法互相矛盾。","阅读高频"),
  ("convey","/kənˈveɪ/","v.","传达","The chart conveys a clear upward trend.","图表传达出明显的上升趋势。","图表题"),
  ("correlate","/ˈkɒrəleɪt/","v.","相关","Sleep correlates with memory performance.","睡眠与记忆表现相关。","学术词"),
  ("crucial","/ˈkruːʃl/","adj.","至关重要的","The first three days are crucial.","最初三天至关重要。","写作替换"),
  ("cumulative","/ˈkjuːmjələtɪv/","adj.","累积的","The cumulative effect of small savings is large.","小额储蓄的累积效应很大。","图表题"),
  ("deteriorate","/dɪˈtɪəriəreɪt/","v.","恶化","Air quality deteriorated during the winter.","冬季空气质量恶化。","新闻高频"),
  ("diminish","/dɪˈmɪnɪʃ/","v.","减少；削弱","Interest in traditional media diminished.","对传统媒体的兴趣减弱。","图表题"),
  ("discrepancy","/dɪsˈkrepənsi/","n.","差异","There's a discrepancy between the two datasets.","两套数据存在差异。","学术词"),
  ("diverse","/daɪˈvɜːs/","adj.","多样的","The team includes diverse backgrounds.","团队包含多元背景。","写作替换"),
  ("elaborate","/ɪˈlæbərət/","adj./v.","精细的；详述","Could you elaborate on that point?","你能详细说明那点吗？","口语提分"),
  ("eliminate","/ɪˈlɪmɪneɪt/","v.","消除；淘汰","The system eliminates most manual errors.","该系统消除了大多数人为错误。","写作替换"),
  ("empirical","/ɪmˈpɪrɪkl/","adj.","实证的","The theory lacks empirical evidence.","该理论缺乏实证证据。","学术词"),
  ("equivalent","/ɪˈkwɪvələnt/","adj./n.","等同的；等价物","One mile is equivalent to 1.6 kilometers.","一英里等于 1.6 公里。","图表题"),
  ("erode","/ɪˈrəʊd/","v.","侵蚀；削弱","Scandals eroded institutional trust.","丑闻削弱了机构信任。","写作提分"),
  ("evaluate","/ɪˈvæljueɪt/","v.","评估","We must evaluate the long-term impact.","我们必须评估长期影响。","学术词"),
  ("exacerbate","/ɪɡˈzæsəbeɪt/","v.","使恶化；加剧","The drought exacerbated the food crisis.","干旱加剧了粮食危机。","写作替换"),
  ("fluctuate","/ˈflʌktʃueɪt/","v.","波动","Prices fluctuated between 2019 and 2021.","价格在 2019 到 2021 年间波动。","图表题"),
  ("formulate","/ˈfɔːmjuleɪt/","v.","制定；阐述","They formulated a new policy.","他们制定了新政策。","学术词"),
  ("fundamental","/ˌfʌndəˈmentl/","adj.","根本的","There is a fundamental flaw in the design.","设计存在根本缺陷。","写作替换"),
  ("generate","/ˈdʒenəreɪt/","v.","产生","The change generated fierce debate.","这一变化引发了激烈辩论。","写作替换"),
  ("hypothesis","/haɪˈpɒθəsɪs/","n.","假设","The data supported their hypothesis.","数据支持了他们的假设。","学术词"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明；举例","The case illustrates the risks involved.","该案例说明了涉及的风险。","写作提分"),
  ("implication","/ˌɪmplɪˈkeɪʃn/","n.","含义；影响","The findings have policy implications.","这些发现具有政策影响。","学术词"),
  ("incentive","/ɪnˈsentɪv/","n.","激励；动机","Incentives encourage faster output.","激励措施促使加快产出。","经济学词"),
  ("indicate","/ˈɪndɪkeɪt/","v.","表明","The survey indicates a shift in attitudes.","调查显示态度转变。","图表题"),
  ("inevitable","/ɪnˈevɪtəbl/","adj.","不可避免的","Some conflict is inevitable in any team.","任何团队中一定程度的冲突都不可避免。","写作提分"),
  ("infer","/ɪnˈfɜː/","v.","推断","We can infer the cause from these figures.","我们能从这些数字推断原因。","阅读高频"),
  ("integrate","/ˈɪntɪgreɪt/","v.","整合","The app integrates several data sources.","该应用整合了多个数据源。","学术词"),
  ("intrinsic","/ɪnˈtrɪnzɪk/","adj.","内在的；本质的","Intrinsic value matters more than price.","内在价值比价格更重要。","学术词"),
  ("justify","/ˈdʒʌstɪfaɪ/","v.","证明…正当","The results justify the extra cost.","结果证明额外成本是值得的。","写作提分"),
  ("legitimate","/lɪˈdʒɪtɪmət/","adj.","合理的；合法的","This is a legitimate concern.","这是个合理的关切。","熟词僻义"),
  ("magnitude","/ˈmæɡnɪtjuːd/","n.","重要性；巨大","Few understood the magnitude of the risk.","很少有人明白风险之大。","新闻高频"),
  ("manifest","/ˈmænɪfest/","v./adj.","表明；明显的","The effect manifested as lower sales.","效果表现为销量下降。","熟词僻义"),
  ("margin","/ˈmɑːdʒɪn/","n.","差额；边缘","Profit margins are slim in this sector.","该行业利润微薄。","熟词僻义"),
  ("mitigate","/ˈmɪtɪɡeɪt/","v.","减轻；缓和","Planting trees mitigates flooding.","植树能减轻洪水影响。","写作提分"),
  ("modify","/ˈmɒdɪfaɪ/","v.","修改；调整","The bill was modified after criticism.","法案在批评后被修改。","新闻高频"),
  ("notion","/ˈnəʊʃn/","n.","观念","The notion of fixed talent was challenged.","天赋固定的观念受到挑战。","熟词僻义"),
  ("objective","/əbˈdʒektɪv/","adj./n.","客观的；目标","The study uses objective measures.","该研究采用客观测量。","学术词"),
  ("obscure","/əbˈskjʊə/","adj./v.","晦涩的；使模糊","The paper is full of obscure references.","论文充满晦涩的参考文献。","熟词僻义"),
  ("offset","/ˈɒfset/","v.","抵消","Higher sales offset rising costs.","销售增长抵消了成本上升。","图表题"),
  ("paradigm","/ˈpærədaɪm/","n.","范式","The discovery triggered a paradigm shift.","这一发现促成了范式转变。","学术词"),
  ("perceive","/pəˈsiːv/","v.","察觉；认为","Consumers perceive the brand as reliable.","消费者认为该品牌可靠。","学术词"),
  ("phenomenon","/fəˈnɒmɪnən/","n.","现象","Urban heat islands are a growing phenomenon.","城市热岛是日益常见的现象。","学术词"),
  ("preliminary","/prɪˈlɪmɪnəri/","adj.","初步的","Preliminary data look promising.","初步数据看起来不错。","学术词"),
  ("prevalent","/ˈprevələnt/","adj.","普遍的","This view is prevalent among economists.","这种观点在经济学家中普遍存在。","学术词"),
  ("profound","/prəˈfaʊnd/","adj.","深刻的","The book had a profound impact on me.","这本书对我影响深远。","评价词"),
  ("prohibit","/prəˈhɪbɪt/","v.","禁止","The law prohibits single-use plastics.","法律禁止一次性塑料。","听力高频"),
  ("prominent","/ˈprɒmɪnənt/","adj.","突出的；著名的","She is a prominent economist.","她是著名经济学家。","写作提分"),
  ("prosperity","/prəˈsperəti/","n.","繁荣","Trade brought decades of prosperity.","贸易带来了数十年的繁荣。","经济学词"),
  ("radical","/ˈrædɪkl/","adj.","根本的；激进的","The company underwent radical change.","公司经历了根本性变革。","熟词僻义"),
  ("reinforce","/ˌriːɪnˈfɔːs/","v.","强化","The results reinforce earlier findings.","结果强化了早期发现。","学术词"),
  ("resilience","/rɪˈzɪliəns/","n.","韧性","The tests measured the material's resilience.","测试测量了材料的韧性。","写作提分"),
  ("rigorous","/ˈrɪɡərəs/","adj.","严格的；严谨的","It passed rigorous clinical trials.","它通过了严格的临床试验。","学术词"),
  ("scarce","/skeəs/","adj.","稀缺的","Fresh water is increasingly scarce.","淡水日益稀缺。","图表题"),
  ("scrutiny","/ˈskruːtəni/","n.","审查","The plan came under public scrutiny.","该计划受到公众审查。","新闻高频"),
  ("skeptical","/ˈskeptɪkl/","adj.","怀疑的","Scientists are skeptical of the claim.","科学家对该说法持怀疑态度。","阅读高频"),
  ("sophisticated","/səˈfɪstɪkeɪtɪd/","adj.","精密的；老练的","They use sophisticated modeling.","他们使用精密的建模。","写作提分"),
  ("speculate","/ˈspekjuleɪt/","v.","推测；投机","It would be wrong to speculate without data.","没有数据就推测是错误的。","学术词"),
  ("stimulate","/ˈstɪmjuleɪt/","v.","刺激；激励","Tax cuts stimulate consumer spending.","减税刺激消费。","经济学词"),
  ("subsequent","/ˈsʌbsɪkwənt/","adj.","随后的","Subsequent trials confirmed the effect.","随后的试验证实了这一效果。","学术词"),
  ("subsidy","/ˈsʌbsədi/","n.","补贴","The government cut agricultural subsidies.","政府削减了农业补贴。","经济学词"),
  ("sustain","/səˈsteɪn/","v.","维持；支撑","The economy can't sustain this growth rate.","经济无法维持这种增速。","写作提分"),
  ("tackle","/ˈtækl/","v.","应对","The city is tackling air pollution.","该市正在应对空气污染。","写作替换"),
  ("tentative","/ˈtentətɪv/","adj.","暂定的","They reached a tentative agreement.","他们达成了初步协议。","学术词"),
  ("thereby","/ˌðeəˈbaɪ/","adv.","从而","Revenue rose, thereby boosting profit.","收入上升，从而提高了利润。","逻辑词"),
  ("threshold","/ˈθreʃhəʊld/","n.","门槛；临界点","Income above this threshold is taxed higher.","高于此门槛的收入税率更高。","图表题"),
  ("transmit","/trænsˈmɪt/","v.","传播；传输","The virus spreads through droplets.","病毒通过飞沫传播。","新闻高频"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱","The scandal undermined public trust.","丑闻削弱了公众信任。","写作提分"),
  ("utilize","/ˈjuːtəlaɪz/","v.","利用","Farmers utilize weather forecasts.","农民利用天气预报。","写作替换"),
  ("verify","/ˈverɪfaɪ/","v.","核实","Journalists must verify claims.","记者必须核实说法。","学术词"),
  ("viable","/ˈvaɪəbl/","adj.","可行的","Solar is now a viable option.","太阳能现在是可行选项。","写作提分"),
  ("vigorous","/ˈvɪɡərəs/","adj.","有力的","She made a vigorous defence of the policy.","她为政策作了有力辩护。","写作提分"),
  ("vulnerable","/ˈvʌlnərəbl/","adj.","脆弱的","The elderly are vulnerable to the flu.","老年人易受流感侵袭。","写作提分"),
  ("yield","/jiːld/","v./n.","产生；产量；屈服","The experiment yielded surprising results.","实验产生了意外结果。","熟词僻义"),
 ]),
 ("翻译与写作高级词", [
  ("abolish","/əˈbɒlɪʃ/","v.","废除","The government abolished the outdated law.","政府废除了过时的法律。","翻译提分"),
  ("advocate","/ˈædvəkeɪt/","v./n.","提倡；支持者","Many advocate raising the minimum wage.","许多人主张提高最低工资。","写作提分"),
  ("aesthetic","/iːsˈθetɪk/","adj.","美学的","The design has aesthetic value.","该设计有美学价值。","学术词"),
  ("alleviate","/əˈliːvieɪt/","v.","缓解","The policy aims to alleviate poverty.","该政策旨在缓解贫困。","翻译提分"),
  ("allocate","/ˈæləkeɪt/","v.","分配","Funds were allocated to preventive care.","资金被分配到预防性护理。","图表题"),
  ("articulate","/ɑːˈtɪkjuleɪt/","v.","清晰表达","Try to articulate your ideas clearly.","试着清晰表达你的想法。","口语高分"),
  ("assimilate","/əˈsɪməleɪt/","v.","吸收；同化","Students must assimilate new information.","学生必须吸收新信息。","学术词"),
  ("bolster","/ˈbəʊlstə/","v.","支持；增强","The data bolstered their argument.","数据加强了他们的论点。","新闻高频"),
  ("circumspect","/ˈsɜːkəmspekt/","adj.","谨慎的","Be circumspect when signing contracts.","签合同时要谨慎。","写作提分"),
  ("coincide","/ˌkəʊɪnˈsaɪd/","v.","同时发生","Their arrival coincided with the crisis.","他们的到来恰逢危机。","翻译提分"),
  ("comply","/kəmˈplaɪ/","v.","遵从","All products must comply with regulations.","所有产品必须遵守规定。","写作提分"),
  ("comprise","/kəmˈpraɪz/","v.","包含","The course comprises ten lectures.","该课程包含十讲。","阅读高频"),
  ("conceive","/kənˈsiːv/","v.","构想","It is hard to conceive of such growth.","很难设想如此的增长。","翻译提分"),
  ("condemn","/kənˈdem/","v.","谴责","The statement condemned the violence.","声明谴责了暴力。","新闻高频"),
  ("confine","/kənˈfaɪn/","v.","限制","Please confine your answer to 200 words.","请将答案限制在 200 词内。","写作提分"),
  ("consecutive","/kənˈsekjətɪv/","adj.","连续的","It rained for five consecutive days.","连续下了五天雨。","图表题"),
  ("considerable","/kənˈsɪdərəbl/","adj.","相当大的","The project required considerable funding.","项目需要相当多资金。","图表题"),
  ("constrain","/kənˈstreɪn/","v.","限制；约束","Budget constrains our options.","预算限制了我们的选择。","学术词"),
  ("contemporary","/kənˈtemprəri/","adj.","当代的","Contemporary society values flexibility.","当代社会重视灵活性。","写作提分"),
  ("contradict","/ˌkɒntrəˈdɪkt/","v.","与…矛盾","The two accounts contradict each other.","两种说法互相矛盾。","写作提分"),
  ("controversy","/ˈkɒntrəvɜːsi/","n.","争议","The policy sparked fierce controversy.","该政策引发了激烈争议。","新闻高频"),
  ("conventional","/kənˈvenʃənl/","adj.","传统的；常规的","Conventional wisdom was overturned.","传统认知被推翻。","学术词"),
  ("correlation","/ˌkɒrəˈleɪʃn/","n.","相关性","There is a correlation but not causation.","存在相关性但非因果。","学术词"),
  ("culminate","/ˈkʌlmɪneɪt/","v.","以…告终","The project culminated in a breakthrough.","该项目以突破告终。","写作提分"),
  ("deter","/dɪˈtɜː/","v.","阻止；威慑","Heavy rain deterred him from going.","大雨阻止了他出门。","熟词僻义"),
  ("differentiate","/ˌdɪfəˈrenʃieɪt/","v.","区分；使不同","Consumers cannot differentiate the two brands.","消费者无法区分这两个品牌。","经济学词"),
  ("diminish","/dɪˈmɪnɪʃ/","v.","削弱","The scandal diminished his reputation.","丑闻削弱了他的声誉。","写作提分"),
  ("discrepancy","/dɪsˈkrepənsi/","n.","不一致","There is a discrepancy between forecast and reality.","预测与现实存在差异。","学术词"),
  ("elicit","/iˈlɪsɪt/","v.","引出；诱出","The study elicited useful responses.","该研究引出了有用的回答。","学术词"),
  ("embrace","/ɪmˈbreɪs/","v.","欣然接受","Firms that embrace change tend to thrive.","勇于接受变化的公司往往蓬勃发展。","写作提分"),
  ("endeavor","/ɪnˈdevə/","n./v.","努力；尽力","They endeavored to finish on time.","他们努力按时完成。","写作提分"),
  ("enhance","/ɪnˈhɑːns/","v.","提升","The reform enhanced public trust.","改革提升了公众信任。","写作提分"),
  ("entail","/ɪnˈteɪl/","v.","需要；使必要","The job entails frequent travel.","这份工作需要经常出差。","翻译高频"),
  ("exemplify","/ɪɡˈzemplɪfaɪ/","v.","举例说明","This case exemplifies the problem.","这个案例很好地例证了该问题。","写作提分"),
  ("exert","/ɪɡˈzɜːt/","v.","施加","Teachers exert lasting influence.","教师施加持久影响。","学术词"),
  ("facilitate","/fəˈsɪlɪteɪt/","v.","促进","The treaty facilitated trade.","该条约促进了贸易。","翻译提分"),
  ("formulate","/ˈfɔːmjuleɪt/","v.","系统阐述","She formulated a clear hypothesis.","她系统阐述了一个清晰的假设。","学术词"),
  ("implement","/ˈɪmplɪment/","v.","实施","The policy will be implemented in stages.","该政策将分阶段实施。","新闻高频"),
  ("incorporate","/ɪnˈkɔːpəreɪt/","v.","纳入","The curriculum incorporates digital literacy.","课程纳入了数字素养。","写作提分"),
  ("indispensable","/ˌɪndɪˈspensəbl/","adj.","不可或缺的","Clean water is indispensable to life.","清洁水对生命不可或缺。","写作提分"),
  ("inherent","/ɪnˈhɪərənt/","adj.","固有的","Risk is inherent in any investment.","投资本身就有内在风险。","学术词"),
  ("initiate","/ɪˈnɪʃieɪt/","v.","发起","The university initiated a mentoring scheme.","该大学发起了一项导师计划。","新闻高频"),
  ("innovative","/ˈɪnəveɪtɪv/","adj.","创新的","They took an innovative approach.","他们采取了创新方法。","写作提分"),
  ("integral","/ˈɪntɪɡrəl/","adj.","不可或缺的","Feedback is integral to learning.","反馈是学习中不可或缺的部分。","学术词"),
  ("integrate","/ˈɪntɪɡreɪt/","v.","整合","The system integrates data from many sources.","系统整合了多种来源数据。","学术词"),
  ("intricate","/ˈɪntrɪkət/","adj.","错综复杂的","The regulations are intricate.","这些规定错综复杂。","写作提分"),
  ("jeopardize","/ˈdʒepədaɪz/","v.","危及","One error could jeopardize the deal.","一个错误可能危及交易。","翻译提分"),
  ("lucrative","/ˈluːkrətɪv/","adj.","获利丰厚的","It proved a lucrative market.","事实证明这是个有利可图的市场。","经济学词"),
  ("mitigate","/ˈmɪtɪɡeɪt/","v.","缓和","Measures were taken to mitigate risk.","采取措施降低风险。","翻译提分"),
  ("notorious","/nəʊˈtɔːriəs/","adj.","臭名昭著的","The company is notorious for poor service.","该公司因服务差而臭名昭著。","熟词僻义"),
  ("perpetual","/pəˈpetʃuəl/","adj.","永久的；持续不断的","The company faces perpetual cash-flow problems.","公司面临持续不断的现金流问题。","写作提分"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","That's plausible, but unproven.","这看似合理但未获证实。","阅读高频"),
  ("preliminary","/prɪˈlɪmɪnəri/","adj.","初步的","Preliminary results are encouraging.","初步结果令人鼓舞。","学术词"),
  ("profound","/prəˈfaʊnd/","adj.","深刻的","The reform had a profound impact.","改革产生了深远影响。","写作提分"),
  ("reciprocal","/rɪˈsɪprəkl/","adj.","互惠的","The agreement is reciprocal.","该协议是互惠的。","翻译提分"),
  ("redundant","/rɪˈdʌndənt/","adj.","多余的；被裁员的","The second paragraph is redundant.","第二段是多余的。","写作提分"),
  ("refute","/rɪˈfjuːt/","v.","驳斥","The data refute his earlier claim.","数据驳斥了他早先的主张。","学术词"),
  ("reluctant","/rɪˈlʌktənt/","adj.","不情愿的","Companies are reluctant to disclose data.","公司不愿披露数据。","新闻高频"),
  ("retain","/rɪˈteɪn/","v.","保留","The soil retains moisture well.","这种土壤保水性好。","学术词"),
  ("retrieve","/rɪˈtriːv/","v.","取回；检索","You can retrieve the file online.","你可以在网上检索该文件。","听力高频"),
  ("rigorous","/ˈrɪɡərəs/","adj.","严谨的","They conducted a rigorous review.","他们进行了严谨的审查。","学术词"),
  ("scrutiny","/ˈskruːtəni/","n.","详细审查","The proposal faced intense scrutiny.","该提案面临严格审查。","新闻高频"),
  ("skeptical","/ˈskeptɪkl/","adj.","怀疑的","Many scientists remain skeptical.","许多科学家仍持怀疑态度。","阅读高频"),
  ("sophisticated","/səˈfɪstɪkeɪtɪd/","adj.","精密的","It's a sophisticated statistical method.","这是一种精密的统计方法。","学术词"),
  ("speculate","/ˈspekjuleɪt/","v.","推测","Analysts speculate on the causes.","分析师推测其原因。","新闻高频"),
  ("subsequent","/ˈsʌbsɪkwənt/","adj.","随后的","Subsequent events confirmed this.","随后的事件证实了这一点。","学术词"),
  ("sustain","/səˈsteɪn/","v.","支撑；承受","The model can sustain extreme heat.","该模型能承受极端高温。","学术词"),
  ("tedious","/ˈtiːdiəs/","adj.","冗长乏味的","Data entry is tedious but necessary.","数据录入枯燥但必要。","听力场景"),
  ("tentative","/ˈtentətɪv/","adj.","试探性的","We reached a tentative conclusion.","我们得出试探性结论。","学术词"),
  ("transparent","/trænsˈpærənt/","adj.","透明的；公开的","The process must be transparent.","流程必须公开透明。","写作提分"),
  ("versatile","/ˈvɜːsətaɪl/","adj.","多才多艺的；多用途的","Bamboo is a versatile material.","竹子是用途广泛的材料。","写作提分"),
  ("viable","/ˈvaɪəbl/","adj.","可行的","It's a commercially viable option.","这是商业上可行的选项。","写作提分"),
  ("vigorous","/ˈvɪɡərəs/","adj.","有力的","She made a vigorous argument.","她作了有力的论证。","写作提分"),
  ("vulnerable","/ˈvʌlnərəbl/","adj.","易受伤害的","Children are vulnerable to exploitation.","儿童易受剥削。","写作提分"),
  ("yield","/jiːld/","v.","产生；屈服","New methods yield better results.","新方法产生更好的结果。","图表题"),
 ]),
 ("听力新闻讲座词", [
  ("anchor","/ˈæŋkə/","n./v.","新闻主播；主持","The news anchor interviewed the minister.","新闻主播采访了部长。","新闻场景"),
  ("bulletin","/ˈbʊlətɪn/","n.","公告；新闻简报","A bulletin was issued at noon.","中午发布了公告。","新闻场景"),
  ("coverage","/ˈkʌvərɪdʒ/","n.","报道；覆盖","The station provides live coverage.","该台提供现场直播报道。","新闻场景"),
  ("deadline","/ˈdedlaɪn/","n.","截止日期","The deadline has been extended.","截止日期已延长。","职场场景"),
  ("department","/dɪˈpɑːtment/","n.","部门；系","She works in the marketing department.","她在市场部工作。","职场场景"),
  ("economy","/ɪˈkɒnəmi/","n.","经济；节约","The economy grew by three percent.","经济增长了百分之三。","新闻场景"),
  ("editorial","/ˌedɪˈtɔːriəl/","adj./n.","社论的；编辑的","The editorial criticized the policy.","该社论批评了这项政策。","新闻场景"),
  ("evidence","/ˈevɪdəns/","n.","证据","There is no evidence to support that claim.","没有证据支持该说法。","学术词"),
  ("expert","/ˈekspɜːt/","n.","专家","An expert analyzed the data.","一位专家分析了数据。","新闻场景"),
  ("forecast","/ˈfɔːkɑːst/","n./v.","预测","The forecast predicts heavy rain.","预报预测有大雨。","新闻场景"),
  ("headline","/ˈhedlaɪn/","n.","头条","The story made headlines worldwide.","该新闻成为全球头条。","新闻场景"),
  ("inflation","/ɪnˈfleɪʃn/","n.","通货膨胀","Inflation reached a five-year high.","通胀达到五年高位。","新闻场景"),
  ("initiative","/ɪˈnɪʃətɪv/","n.","倡议；主动性","The government launched a green initiative.","政府发起了绿色倡议。","新闻场景"),
  ("interview","/ˈɪntəvjuː/","n.","采访","The interview was broadcast live.","采访进行了直播。","新闻场景"),
  ("negotiate","/nɪˈɡəʊʃieɪt/","v.","谈判","The two sides negotiated for hours.","双方谈判了数小时。","新闻场景"),
  ("poll","/pəʊl/","n./v.","民意调查；投票","A recent poll showed strong support.","最新民调显示强烈支持。","新闻场景"),
  ("preliminary","/prɪˈlɪmɪnəri/","adj.","初步的","Preliminary findings will be released Friday.","初步结果周五公布。","新闻场景"),
  ("procedure","/prəˈsiːdʒə/","n.","程序；手续","Please follow the standard procedure.","请遵循标准程序。","职场场景"),
  ("profit","/ˈprɒfɪt/","n.","利润","Quarterly profits exceeded expectations.","季度利润超出预期。","图表题"),
  ("resource","/rɪˈsɔːs/","n.","资源","The country is rich in natural resources.","该国自然资源丰富。","新闻场景"),
  ("statistics","/stəˈtɪstɪks/","n.","统计数字","The statistics cover ten years.","这些统计数据涵盖十年。","图表题"),
  ("subsidy","/ˈsʌbsədi/","n.","补贴","Farmers rely on government subsidies.","农民依赖政府补贴。","新闻场景"),
  ("survey","/ˈsɜːveɪ/","n./v.","调查","The survey covered 5,000 respondents.","调查涵盖 5000 名受访者。","学术词"),
  ("tariff","/ˈtærɪf/","n.","关税","New tariffs were imposed on imports.","对进口商品加征了新关税。","新闻场景"),
  ("threshold","/ˈθreʃhəʊld/","n.","门槛","Income below the threshold is exempt.","低于门槛的收入免税。","图表题"),
  ("unemployment","/ˌʌnɪmˈplɔɪmənt/","n.","失业","Unemployment fell for the third month.","失业率连续第三个月下降。","新闻场景"),
  ("update","/ˌʌpˈdeɪt/","v./n.","更新","Please update us on the progress.","请告知我们最新进展。","职场场景"),
  ("venue","/ˈvenjuː/","n.","场地","The venue can hold 500 people.","该场地可容纳 500 人。","职场场景"),
  ("vice versa","/ˌvaɪs ˈvɜːsə/","adv.","反之亦然","You can start today, or vice versa.","你可以今天开始，反之亦然。","听力场景"),
  ("witness","/ˈwɪtnəs/","v./n.","目击；证人","Two witnesses saw the accident.","两名目击者看到了事故。","新闻场景"),
 ]),
 ("固定搭配", [
  ("account for","/əˈkaʊnt fɔː/","phr.","解释；占（比例）","Online sales account for half of revenue.","线上销售占收入的一半。","高频搭配"),
  ("adapt to","/əˈdæpt tuː/","phr.","适应","It took time to adapt to city life.","适应城市生活花了一些时间。","高频搭配"),
  ("attribute to","/əˈtrɪbjuːt tuː/","phr.","归因于","She attributes her success to hard work.","她把成功归因于努力。","高频搭配"),
  ("be aware of","/bi əˈweə əv/","phr.","意识到","Few are aware of the risks.","很少有人意识到这些风险。","高频搭配"),
  ("be subject to","/bi ˈsʌbdʒekt tuː/","phr.","受制于；易受…影响","Prices are subject to change.","价格可能会有变动。","熟词僻义"),
  ("bring about","/brɪŋ əˈbaʊt/","phr.","导致；引起","The reform brought about lasting change.","改革带来了持久变化。","高频搭配"),
  ("carry out","/ˈkæri aʊt/","phr.","执行；开展","They carried out a nationwide survey.","他们开展了全国调查。","高频搭配"),
  ("come up with","/kʌm ʌp wɪð/","phr.","想出","He came up with an elegant solution.","他想出了一个优雅的解决方案。","口语高频"),
  ("cope with","/kəʊp wɪð/","phr.","应对","Students must cope with pressure.","学生必须应对压力。","高频搭配"),
  ("derive from","/dɪˈraɪv frɒm/","phr.","源自","Many English words derive from Latin.","许多英语单词源自拉丁语。","学术词"),
  ("engage in","/ɪnˈɡeɪdʒ ɪn/","phr.","从事；参与","They engaged in serious discussion.","他们进行了严肃讨论。","高频搭配"),
  ("figure out","/ˈfɪɡə aʊt/","phr.","弄明白","I can't figure out the answer.","我弄不明白答案。","口语高频"),
  ("give rise to","/ɡɪv raɪz tuː/","phr.","引起","The policy gave rise to protests.","该政策引起了抗议。","阅读高频"),
  ("in accordance with","/ɪn əˈkɔːdəns wɪð/","phr.","依照；与…一致","All done in accordance with the rules.","所有操作均依照规定进行。","写作提分"),
  ("in light of","/ɪn laɪt əv/","phr.","鉴于","In light of new evidence, we revise our view.","鉴于新证据，我们修正看法。","写作提分"),
  ("in terms of","/ɪn tɜːmz əv/","phr.","就…而言","In terms of cost, the plan is feasible.","就成本而言，该计划可行。","写作提分"),
  ("keep track of","/kiːp træk əv/","phr.","记录；跟踪","Keep track of your daily spending.","记录你的日常开支。","生活场景"),
  ("lead to","/liːd tuː/","phr.","导致","Stress can lead to poor sleep.","压力可能导致睡眠不佳。","高频搭配"),
  ("on behalf of","/ɒn bɪˈhɑːf əv/","phr.","代表","He signed on behalf of the company.","他代表公司签了字。","职场场景"),
  ("put forward","/pʊt ˈfɔːwəd/","phr.","提出","She put forward a bold proposal.","她提出了大胆的提案。","写作提分"),
  ("regardless of","/rɪˈɡɑːdləs əv/","phr.","不管","Everyone can use it regardless of age.","任何年龄的人都能使用。","熟词僻义"),
  ("result in","/rɪˈzʌlt ɪn/","phr.","导致","Carelessness resulted in the accident.","粗心导致了事故。","高频搭配"),
  ("run out of","/rʌn aʊt əv/","phr.","用完","We've run out of paper.","我们的纸用完了。","生活场景"),
  ("so far","/səʊ fɑː/","phr.","到目前为止","So far everything is going well.","到目前为止一切顺利。","口语高频"),
  ("stem from","/stem frɒm/","phr.","源于","The problem stems from poor planning.","问题源于规划不足。","写作提分"),
  ("subject to","/ˈsʌbdʒekt tuː/","phr.","以…为条件；易受","The offer is subject to approval.","该要约须经批准。","熟词僻义"),
  ("take advantage of","/teɪk ədˈvɑːntɪdʒ əv/","phr.","利用","Take advantage of the discount.","利用这个折扣。","口语高频"),
  ("take into account","/teɪk ɪntuː əˈkaʊnt/","phr.","考虑到","We must take costs into account.","我们必须考虑成本。","写作提分"),
  ("turn down","/tɜːn daʊn/","phr.","拒绝；调低","He turned down the offer.","他拒绝了这个提议。","口语高频"),
  ("undergo","/ˌʌndəˈɡəʊ/","v.","经历","The system underwent major changes.","该系统经历了重大变化。","阅读高频"),
  ("withstand","/wɪðˈstænd/","v.","承受；抵挡","The bridge withstood the earthquake.","桥承受住了地震。","学术词"),
  ("be bound to","/bi baʊnd tuː/","phr.","一定会","He is bound to make mistakes.","他一定会犯错。","口语高频"),
  ("in the long run","/ɪn ðə lɒŋ rʌn/","phr.","长期来看","In the long run, prevention is cheaper.","长期来看，预防更便宜。","写作提分"),
  ("at the expense of","/ət ði ɪkˈspens əv/","phr.","以…为代价","Growth came at the expense of the environment.","增长以环境为代价。","写作提分"),
  ("by no means","/baɪ nəʊ miːnz/","phr.","决不","He is by no means finished.","他远未完成。","翻译高分"),
  ("in essence","/ɪn ˈesns/","phr.","本质上","In essence, the two views agree.","本质上这两种观点一致。","翻译高分"),
  ("to a great extent","/tuː ə ɡreɪt ɪkˈstent/","phr.","在很大程度上","To a great extent, luck matters.","在很大程度上，运气很重要。","翻译高分"),
 ]),
]

# ============ 八级 TEM-8（英美语言文学 + 翻译，词汇少但深）============
TEM8 = [
 ("英美文学词汇", [
  ("aesthetic","/iːsˈθetɪk/","adj.","美学的；审美的","The novel has deep aesthetic value.","这部小说有深厚的美学价值。","文学"),
  ("allegory","/ˈælɪɡəri/","n.","寓言","The story is a political allegory.","这个故事是一则政治寓言。","文学"),
  ("ambiguity","/ˌæmbɪˈɡjuːəti/","n.","歧义","The poem's ambiguity enriches its meaning.","诗的歧义丰富了它的含义。","文学"),
  ("antithesis","/ænˈtɪθəsɪs/","n.","对立面","The ending is the antithesis of the beginning.","结局与开头形成对立。","文学"),
  ("archetype","/ˈɑːkitaɪp/","n.","原型；典型","He is a classic archetype of the hero.","他是典型的英雄原型。","文学"),
  ("catalyst","/ˈkætəlɪst/","n.","催化剂；促成因素","The crisis acted as a catalyst for reform.","危机成为改革的催化因素。","文学"),
  ("chronicle","/ˈkrɒnɪkl/","n./v.","编年史；记录","The novel chronicles a whole decade.","这部小说记录了整整十年。","文学"),
  ("cognitive","/ˈkɒɡnətɪv/","adj.","认知的","Cognitive decline affects memory.","认知衰退影响记忆。","学术"),
  ("consciousness","/ˈkɒnʃəsnəs/","n.","意识","The story explores moral consciousness.","故事探讨道德意识。","文学"),
  ("contemporary","/kənˈtemprəri/","adj.","当代的","Contemporary literature reflects social change.","当代文学反映社会变迁。","文学"),
  ("critique","/krɪˈtiːk/","n./v.","评论；批评","The essay critiques the novel's symbolism.","这篇文章评论了小说象征手法。","文学"),
  ("dialectic","/ˌdaɪəˈlektɪk/","n.","辩证法","The play employs a Hegelian dialectic.","该剧运用了黑格尔式辩证法。","学术"),
  ("discourse","/ˈdɪskɔːs/","n.","话语；论述","Academic discourse shapes public opinion.","学术话语塑造公众舆论。","学术"),
  ("elegy","/ˈelədʒi/","n.","挽歌","The poem is an elegy for lost youth.","这首诗是为逝去青春作的挽歌。","文学"),
  ("epistemology","/ɪˌpɪstɪˈmɒlədʒi/","n.","认识论","The book examines the epistemology of science.","该书审视科学的认识论。","学术"),
  ("genre","/ˈʒɒnrə/","n.","体裁；类型","Science fiction is a popular genre.","科幻是流行体裁。","文学"),
  ("hermeneutic","/ˌhɜːməˈnjuːtɪk/","adj.","解释学的","The article applies hermeneutic methods.","该文运用了解释学方法。","学术"),
  ("idiom","/ˈɪdiəm/","n.","习语；风格","English idioms are hard to translate.","英语习语难以翻译。","文学"),
  ("implication","/ˌɪmplɪˈkeɪʃn/","n.","言外之意；影响","The implication is clear to careful readers.","细心的读者能明白言外之意。","文学"),
  ("irony","/ˈaɪrəni/","n.","反讽；讽刺","The ending is pure irony.","结局是纯粹的反讽。","文学"),
  ("metaphor","/ˈmetəfə/","n.","隐喻","The poem is built on a central metaphor.","这首诗建立在核心隐喻之上。","文学"),
  ("narrative","/ˈnærətɪv/","n./adj.","叙事；叙事的","The novel is a nonlinear narrative.","这部小说是非线性叙事。","文学"),
  ("paradox","/ˈpærədɒks/","n.","悖论","The situation presents a paradox.","这种情形呈现出一个悖论。","文学"),
  ("parody","/ˈpærədi/","n./v.","模仿；戏仿","The novel parodies detective fiction.","这部小说戏仿侦探小说。","文学"),
  ("phenomenon","/fəˈnɒmɪnən/","n.","现象","The author describes this cultural phenomenon.","作者描述了这一文化现象。","文学"),
  ("postmodern","/ˌpəʊstˈmɒdən/","adj.","后现代的","Postmodern narrative rejects linear time.","后现代叙事拒绝线性时间。","文学"),
  ("premise","/ˈpremɪs/","n.","前提；假设","The whole argument rests on a false premise.","整个论证建立在错误前提上。","学术"),
  ("prose","/prəʊz/","n.","散文","He writes elegant prose.","他文笔优雅。","文学"),
  ("rhetoric","/ˈretərɪk/","n.","修辞；言辞","The speech relied on empty rhetoric.","演讲依赖空洞的言辞。","学术"),
  ("satire","/ˈsætaɪə/","n.","讽刺","The novel is a sharp satire of bureaucracy.","这部小说是对官僚体制的尖锐讽刺。","文学"),
  ("sentiment","/ˈsentɪmənt/","n.","情感；情绪","Public sentiment shifted dramatically.","公众情绪发生了剧变。","文学"),
  ("solitude","/ˈsɒlɪtjuːd/","n.","孤独；独处","The poet sought solitude in the hills.","诗人在山中寻求独处。","文学"),
  ("sublime","/səˈblaɪm/","adj.","崇高的；壮丽的","The novel finds the sublime in ordinary life.","这部小说在日常生活中发现崇高。","文学"),
  ("symbolism","/ˈsɪmbəlɪzəm/","n.","象征主义","Symbolism dominated early poetry.","象征主义主导了早期诗歌。","文学"),
  ("synthesis","/ˈsɪnθəsɪs/","n.","综合；合成","The book offers a synthesis of two theories.","该书综合了两种理论。","学术"),
  ("tempo","/ˈtempəʊ/","n.","节奏；速度","The novel's slow tempo builds tension.","小说的慢节奏营造紧张感。","文学"),
  ("theme","/θiːm/","n.","主题","The central theme is alienation.","核心主题是异化。","文学"),
  ("tone","/təʊn/","n.","语气；音调","The tone shifted from irony to pathos.","语气从讽刺转向悲怆。","文学"),
  ("transcend","/trænˈsend/","v.","超越","Art transcends national boundaries.","艺术超越国界。","翻译高分"),
  ("unprecedented","/ʌnˈpresɪdentɪd/","adj.","前所未有的","The event was unprecedented in scale.","该事件规模空前。","写作提分"),
  ("vivid","/ˈvɪvɪd/","adj.","生动的；鲜明的","She gives a vivid description of the city.","她对城市作了生动的描述。","写作提分"),
  ("austere","/ɔːˈstɪə/","adj.","朴素的；严峻的","The prose has an austere beauty.","该散文有朴素的之美。","文学"),
  ("byzantine","/ˈbɪzæntaɪn/","adj.","复杂难懂的","The bureaucracy became byzantine.","官僚体系变得复杂难懂。","学术"),
  ("cathartic","/kəˈθɑːtɪk/","adj.","净化的；宣泄的","The novel offers a cathartic release.","这部小说带来宣泄式释放。","文学"),
  ("equivocal","/ɪˈkwɪvəkl/","adj.","含糊其辞的","His equivocal reply satisfied no one.","他含糊其辞的回答谁都不满意。","写作提分"),
  ("laconic","/ləˈkɒnɪk/","adj.","简洁的；言简意赅的","His laconic style says much in few words.","他言简意赅的风格以少胜多。","文学"),
  ("obdurate","/ˈɒbdjərət/","adj.","固执的","The obdurate manager refused to change.","固执的经理拒绝改变。","写作提分"),
  ("quintessential","/ˌkwɪntɪˈsenʃl/","adj.","典型的","He is the quintessential scholar.","他是典型的学者。","写作提分"),
 ]),
 ("翻译高分词", [
  ("aforementioned","/əˌfɔːˈmenʃənd/","adj.","前述的","The aforementioned policy proved popular.","前述政策证明很受欢迎。","翻译提分"),
  ("arguably","/ˈɑːɡjuəbli/","adv.","可以说；大概","This is arguably the best solution.","这可以说是最好的方案。","翻译提分"),
  ("by and large","/baɪ ənd lɑːdʒ/","phr.","总的来说","By and large, the results are positive.","总的来说，结果是正面的。","翻译高分"),
  ("carry out","/ˈkæri aʊt/","phr.","执行；开展","They carried out a thorough review.","他们进行了彻底审查。","高频搭配"),
  ("come to terms with","/kʌm tuː tɜːmz wɪð/","phr.","接受；妥协","He came to terms with his failure.","他接受了失败。","翻译高分"),
  ("compound","/ˈkɒmpaʊnd/","v./adj.","加剧；复合的","The two factors compound the risk.","这两个因素加剧了风险。","翻译提分"),
  ("conducive","/kənˈdjuːsɪv/","adj.","有助于…的","A quiet room is conducive to study.","安静的房间有助于学习。","写作提分"),
  ("contend","/kənˈtend/","v.","主张；争论","Scholars contend that the theory is flawed.","学者们主张该理论有缺陷。","学术"),
  ("counterpart","/ˈkaʊntəpɑːt/","n.","对应的人/物","Its European counterpart is cheaper.","它的欧洲对应产品更便宜。","写作提分"),
  ("criterion","/kraɪˈtɪəriən/","n.","标准（复 criteria）","Cost is not the only criterion.","成本不是唯一标准。","学术"),
  ("culminating","/ˈkʌlmɪneɪtɪŋ/","adj.","压轴的","The culminating chapter resolves the mystery.","最后无终局的一章解开谜团。","翻译提分"),
  ("discern","/dɪˈsɜːn/","v.","辨别；识别","Few could discern the subtle difference.","很少有人能辨别这细微差别。","学术"),
  ("discrepancy","/dɪsˈkrepənsi/","n.","差异","There is a discrepancy in the accounts.","账目之间存在差异。","学术"),
  ("elicit","/iˈlɪsɪt/","v.","引出","The question elicited useful answers.","这个问题引出了有用的回答。","学术"),
  ("embark","/ɪmˈbɑːk/","v.","着手；登上","They embarked on a five-year study.","他们着手一项五年研究。","翻译提分"),
  ("exemplify","/ɪɡˈzemplɪfaɪ/","v.","例证","This case exemplifies both risks.","这个案例同时例证了两种风险。","写作提分"),
  ("garner","/ˈɡɑːnə/","v.","获得；收集","The plan garnered broad support.","该计划获得广泛支持。","翻译提分"),
  ("herald","/ˈherəld/","v.","预示；宣告","The discovery heralded a new era.","这一发现预示新时代。","翻译提分"),
  ("hierarchical","/ˌhaɪəˈrɑːkɪkl/","adj.","分层的","The data have a hierarchical structure.","数据呈分层结构。","学术"),
  ("inadvertently","/ˌɪnədˈvɜːtəntli/","adv.","无意中","The message was inadvertently sent.","消息无意中发出去了。","翻译提分"),
  ("inherent","/ɪnˈhɪərənt/","adj.","内在的","Risk is inherent in speculation.","投机本身有内在风险。","学术"),
  ("insofar as","/ˌɪnsəʊˈfɑːr əz/","phr.","在…范围内","Valid insofar as the law permits.","在法律允许范围内有效。","翻译高分"),
  ("intricacy","/ˈɪntrɪkəsi/","n.","复杂；错综","He explained the intricacy of the case.","他解释了这个案例的复杂之处。","学术"),
  ("mitigate","/ˈmɪtɪɡeɪt/","v.","减轻","Investment mitigated the risk.","投资降低了风险。","翻译提分"),
  ("notwithstanding","/ˌnɒtwiðˈstændɪŋ/","prep.","尽管","Notwithstanding the delay, it shipped on time.","尽管有延误，它仍按时发货。","翻译高分"),
  ("nuance","/ˈnjuːɑːns/","n.","细微差别","Translation must capture every nuance.","翻译必须捕捉每处细微差别。","翻译提分"),
  ("perpetual","/pəˈpetʃuəl/","adj.","持续不断的","The dispute caused perpetual delay.","纠纷造成持续拖延。","写作提分"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","A plausible but unverified account.","看似合理但未经证实的说法。","阅读高频"),
  ("postulate","/ˈpɒstjuleɪt/","v.","假定；假设","The theory postulates two assumptions.","该理论假定两点。","学术"),
  ("predominant","/prɪˈdɒmɪnənt/","adj.","占主导的","Green is the predominant color.","绿色是主导色调。","学术"),
  ("prerequisite","/prɪˈrekəwəzɪt/","n.","先决条件","A degree is a prerequisite for the job.","学位是该工作的先决条件。","写作提分"),
  ("prevalent","/ˈprevələnt/","adj.","普遍的","The belief remains prevalent.","这一信念依然普遍。","学术"),
  ("rationale","/ˌræʃəˈnɑːl/","n.","理由；依据","He explained the rationale behind the decision.","他解释了决策依据。","学术"),
  ("reciprocal","/rɪˈsɪprəkl/","adj.","互惠的","The two sides reached a reciprocal agreement.","双方达成互惠协议。","翻译提分"),
  ("redundant","/rɪˈdʌndənt/","adj.","多余的","The third paragraph is redundant.","第三段是多余的。","写作提分"),
  ("salient","/ˈseɪliənt/","adj.","显著的；突出的","The salient points are listed first.","显著的要点列在前面。","翻译提分"),
  ("substantiate","/səbˈstænʃieɪt/","v.","证实","We need data to substantiate the claim.","我们需要数据证实该说法。","学术"),
  ("substantive","/ˈsʌbstəntɪv/","adj.","实质的","Let's have a substantive discussion.","我们来一次实质讨论。","口语提分"),
  ("tacit","/ˈtæsɪt/","adj.","心照不宣的","There was a tacit agreement.","有一种默契。","翻译提分"),
  ("tentative","/ˈtentətɪv/","adj.","暂定的","We reached a tentative conclusion.","我们得出暂定结论。","学术"),
  ("thereby","/ˌðeəˈbaɪ/","adv.","从而","The reform cut costs, thereby raising profit.","改革削减成本，从而提高利润。","逻辑词"),
  ("vested","/ˈvestɪd/","adj.","既得的； vest（授予）权益的","Employees have a vested interest in the plan.","员工对该计划享有既得权益。","学术"),
  ("whilst","/waɪlst/","conj.","而；虽然","He stayed whilst others left.","其他人离开时他留下了。","翻译高分"),
  ("wield","/wiːld/","v.","运用；支配","She wields considerable influence.","她运用着相当大的影响力。","写作提分"),
  ("albeit","/ɔːlˈbiːɪt/","conj.","虽然","The plan helped, albeit modestly.","该计划有帮助，尽管有限。","高分词"),
  ("insofar","/ˌɪnsəʊˈfɑː/","adv.","就…而言","So far insofar as I'm concerned.","就我而言，到目前为止。","翻译高分"),
  ("notwithstanding","/ˌnɒtwiðˈstændɪŋ/","prep.","尽管","Notwithstanding these caveats, the trend holds.","尽管有这些保留，趋势依然成立。","翻译高分"),
 ]),
]

# ============ 雅思 IELTS（按四单项分块）============
IELTS = [
 ("阅读同义替换词", [
  ("abundant","/əˈbʌndənt/","adj.","丰富的","The region has abundant natural resources.","该地区自然资源丰富。","阅读"),
  ("adverse","/ˈædvɜːs/","adj.","不利的；有害的","Adverse weather delayed the launch.","恶劣天气推迟了发射。","阅读"),
  ("allocate","/ˈæləkeɪt/","v.","分配","The council allocated funds to housing.","议会将资金分配给住房。","阅读"),
  ("analogous","/əˈnæləɡəs/","adj.","类似的","The two cases are analogous.","这两个案例类似。","阅读"),
  ("coincide","/ˌkəʊɪnˈsaɪd/","v.","同时发生","The festival coincides with the exam.","节日与考试时间重合。","阅读"),
  ("comprise","/kəmˈpraɪz/","v.","包含","The survey comprises 2,000 households.","调查涵盖 2000 户家庭。","阅读"),
  ("constitute","/ˈkɒnstɪtjuːt/","v.","构成","Renewables constitute half the supply.","可再生能源占供应的一半。","阅读"),
  ("discrepancy","/dɪsˈkrepənsi/","n.","差异","There's a discrepancy between the data.","数据之间存在差异。","阅读"),
  ("elaborate","/ɪˈlæbərət/","adj.","精细的","The design is too elaborate for daily use.","该设计过于精细不适合日常使用。","阅读"),
  ("emerge","/iˈmɜːdʒ/","v.","出现","A clear pattern emerged from the data.","数据中呈现出清晰的模式。","阅读"),
  ("equivalent","/ɪˈkwɪvələnt/","adj.","等同的","The two options are not equivalent.","这两个选项并不等同。","阅读"),
  ("exacerbate","/ɪɡˈzæsəbeɪt/","v.","加剧","Scarcity exacerbated the problem.","稀缺加剧了问题。","阅读"),
  ("feasible","/ˈfiːzəbl/","adj.","可行的","The plan is technically feasible.","该计划技术上可行。","阅读"),
  ("fluctuate","/ˈflʌktʃueɪt/","v.","波动","Figures fluctuated between 20 and 40.","数值在 20 到 40 之间波动。","阅读"),
  ("hypothesis","/haɪˈpɒθəsɪs/","n.","假设","The hypothesis was later confirmed.","该假设后来被证实。","阅读"),
  ("implicit","/ɪmˈplɪsɪt/","adj.","含蓄的；隐含的","There is an implicit bias in the design.","设计中存在隐含偏见。","阅读"),
  ("incentive","/ɪnˈsentɪv/","n.","激励","Tax breaks act as an incentive.","减税起到激励作用。","阅读"),
  ("inevitable","/ɪnˈevɪtəbl/","adj.","不可避免的","Change was inevitable.","改变不可避免。","阅读"),
  ("inherent","/ɪnˈhɪərənt/","adj.","固有的","Risk is inherent in any experiment.","任何实验都有内在风险。","阅读"),
  ("integral","/ˈɪntɪɡrəl/","adj.","不可或缺的","Water is integral to farming.","水对农业不可或缺。","阅读"),
  ("interpret","/ɪnˈtɜːprɪt/","v.","解读","How do you interpret this graph?","你如何解读这张图？","阅读"),
  ("legitimate","/lɪˈdʒɪtɪmət/","adj.","合理的；合法的","That's a legitimate concern.","那是个合理的关切。","阅读"),
  ("marginal","/ˈmɑːdʒɪnl/","adj.","微小的；边缘的","The effect was marginal.","影响很微弱。","阅读"),
  ("notion","/ˈnəʊʃn/","n.","观念","The notion that talent is fixed is dated.","天赋固定的观念已过时。","阅读"),
  ("obsolete","/ˈɒbsəliːt/","adj.","过时的","Fax machines became obsolete.","传真机被淘汰了。","阅读"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","That's a plausible explanation.","那是个貌似合理的解释。","阅读"),
  ("predominant","/prɪˈdɒmɪnənt/","adj.","主导的","Cars remain the predominant transport.","汽车仍是主导交通工具。","阅读"),
  ("prevalent","/ˈprevələnt/","adj.","普遍的","The belief is still prevalent.","这一信念仍很普遍。","阅读"),
  ("prominent","/ˈprɒmɪnənt/","adj.","显著的","There's a prominent difference.","存在显著差异。","阅读"),
  ("reluctant","/rɪˈlʌktənt/","adj.","不情愿的","Most firms are reluctant to share data.","多数公司不愿分享数据。","阅读"),
  ("scarce","/skeəs/","adj.","稀缺的","Clean water is scarce in the region.","该地区清洁水稀缺。","阅读"),
  ("scope","/skəʊp/","n.","范围","That falls outside the scope of the study.","那超出研究范围。","阅读"),
  ("skeptical","/ˈskeptɪkl/","adj.","怀疑的","Scientists are skeptical of the claim.","科学家对该说法持怀疑。","阅读"),
  ("substantial","/səbˈstænʃl/","adj.","大量的；实质的","There's substantial evidence.","有大量证据。","阅读"),
  ("subtle","/ˈsʌtl/","adj.","微妙的","There's a subtle distinction.","有一个微妙区别。","阅读"),
  ("threshold","/ˈθreʃhəʊld/","n.","临界点","Income above this threshold is taxed.","高于此临界点的收入需纳税。","阅读"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱","This undermines the whole argument.","这削弱了整个论点。","阅读"),
  ("uniform","/ˈjuːnɪfɔːm/","adj.","一致的","The results were uniform across regions.","结果在各地区一致。","阅读"),
  ("viable","/ˈvaɪəbl/","adj.","可行的","Is this a viable long-term option?","这是长期可行的选项吗？","阅读"),
  ("vulnerable","/ˈvʌlnərəbl/","adj.","脆弱的","The elderly are most vulnerable.","老年人最脆弱。","阅读"),
  ("widespread","/ˈwaɪdspred/","adj.","广泛的","There's widespread support for the plan.","对该计划有广泛支持。","阅读"),
 ]),
 ("写作 Task 1 图表词", [
  ("abrupt","/əˈbrʌpt/","adj.","突然的","There was an abrupt change in 1995.","1995 年出现突然变化。","图表"),
  ("accumulate","/əˈkjuːmjəleɪt/","v.","累积","Sales accumulated over the decade.","销售十年间累积增长。","图表"),
  ("climax","/ˈklaɪmæks/","n.","高潮；峰值","The figure reached a climax in 2008.","数值在 2008 年达到峰值。","图表"),
  ("consistently","/kənˈsɪstəntli/","adv.","持续地","Prices consistently exceeded forecasts.","价格持续超出预测。","图表"),
  ("correlate","/ˈkɒrəleɪt/","v.","相关","Higher income correlates with better health.","更高收入与更好健康相关。","图表"),
  ("dramatically","/drəˈmætɪkli/","adv.","急剧地","Figures dramatically changed after 2010.","2010 年后数值急剧变化。","图表"),
  ("fluctuate","/ˈflʌktʃueɪt/","v.","波动","The rate fluctuated between 5% and 8%","比率在 5% 到 8% 之间波动。","图表"),
  ("gradually","/ˈɡrædʒuəli/","adv.","逐渐地","The line declined gradually.","该线逐渐下降。","图表"),
  ("level off","/ˈlevl ɒf/","phr.","趋于平稳","Growth began to level off in 2012.","增长在 2012 年开始趋平。","图表"),
  ("marginally","/ˈmɑːdʒɪnəli/","adv.","略微地","Output rose marginally.","产出略有上升。","图表"),
  ("peak","/piːk/","n./v.","峰值；达到顶点","Sales peaked at 500 units.","销量峰值达 500 件。","图表"),
  ("plummet","/ˈplʌmɪt/","v.","暴跌","Stocks plummeted after the announcement.","公告后股价暴跌。","图表"),
  ("proportion","/prəˈpɔːʃn/","n.","比例；部分","A large proportion of students agreed.","很大比例的学生同意。","图表"),
  ("roughly","/ˈrʌfli/","adv.","大约","Roughly 30% of the group was chosen.","大约 30% 的人被选中。","图表"),
  ("sharp","/ʃɑːp/","adj.","急剧的","There was a sharp rise in demand.","需求急剧上升。","图表"),
  ("significant","/sɪɡˈnɪfɪkənt/","adj.","显著的","A significant decline followed.","随后出现显著下降。","图表"),
  ("steady","/ˈstedi/","adj.","平稳的","The trend has been steady since 2015.","自 2015 年以来趋势平稳。","图表"),
  ("surge","/sɜːdʒ/","v./n.","激增","Demand surged after the launch.","发布后需求激增。","图表"),
  ("trend","/trend/","n.","趋势","The downward trend continued.","下降趋势持续。","图表"),
  ("turnout","/ˈtɜːnaʊt/","n.","出席率；产量","Voter turnout was record high.","投票出席率创历史新高。","图表"),
  ("upward","/ˈʌpwəd/","adj.","向上的","There was an upward trend.","存在上升趋势。","图表"),
  ("vast","/vɑːst/","adj.","广大的","The vast majority agreed.","绝大多数人同意。","图表"),
  ("virtually","/ˈvɜːtʃuəli/","adv.","几乎；实际上","Virtually all participants improved.","几乎所有参与者都有进步。","图表"),
  ("yield","/jiːld/","n./v.","产量；产生","The crop yield doubled.","作物产量翻倍。","图表"),
  ("decline","/dɪˈklaɪn/","v./n.","下降","Figures declined steadily.","数值稳步下降。","图表"),
  ("double","/ˈdʌbl/","adj./v.","翻倍","The figure doubled in five years.","该数值五年内翻倍。","图表"),
  ("halve","/hɑːv/","v.","减半","Sales halved after the recall.","召回后销量减半。","图表"),
  ("triple","/ˈtrɪpl/","v.","增至三倍","Users tripled in two years.","用户两年增至三倍。","图表"),
  ("fluctuation","/ˌflʌktʃuˈeɪʃn/","n.","波动","There were seasonal fluctuations.","存在季节性波动。","图表"),
  ("proportionate","/prəˈpɔːʃənət/","adj.","成比例的","The increase was proportionate to demand.","增长与需求成比例。","图表"),
 ]),
 ("写作 Task 2 论证词", [
  ("advocate","/ˈædvəkeɪt/","v.","提倡","I advocate raising taxes on sugary drinks.","我提倡对含糖饮料加税。","论证"),
  ("argue","/ˈɑːɡjuː/","v.","主张；论证","Some argue that homework is harmful.","有人主张作业有害。","论证"),
  ("coherent","/kəʊˈhɪərənt/","adj.","连贯的","A coherent argument is easy to follow.","连贯的论证容易理解。","论证"),
  ("compelling","/kəmˈpelɪŋ/","adj.","令人信服的","She made a compelling case.","她提出了令人信服的理由。","论证"),
  ("consequently","/ˈkɒnsɪkwəntli/","adv.","因此","The policy failed; consequently, support dropped.","政策失败，因此支持率下降。","论证"),
  ("considerable","/kənˈsɪdərəbl/","adj.","相当大的","The plan requires considerable investment.","该计划需要相当大的投资。","论证"),
  ("contradict","/ˌkɒntrəˈdɪkt/","v.","与…矛盾","This contradicts earlier research.","这与早期研究矛盾。","论证"),
  ("crucial","/ˈkruːʃl/","adj.","关键的","This distinction is crucial.","这一区分至关重要。","论证"),
  ("debatable","/dɪˈbeɪtəbl/","adj.","有争议的","It's debatable whether this works.","这是否有效有争议。","论证"),
  ("dispel","/dɪˈspel/","v.","消除","The study dispels common myths.","该研究消除了常见迷思。","论证"),
  ("elucidate","/iˈluːsɪdeɪt/","v.","阐明","The author elucidates the theory clearly.","作者清晰地阐明了该理论。","论证"),
  ("enhance","/ɪnˈhɑːns/","v.","增强","Exams enhance learning motivation.","考试增强学习动力。","论证"),
  ("entrenched","/ɪnˈtrentʃt/","adj.","根深蒂固的","These habits are deeply entrenched.","这些习惯根深蒂固。","论证"),
  ("exacerbate","/ɪɡˈzæsəbeɪt/","v.","加剧","The problem was exacerbated by the crisis.","危机加剧了问题。","论证"),
  ("foster","/ˈfɒstə/","v.","培养；促进","Schools foster creativity.","学校培养创造力。","论证"),
  ("fundamentally","/ˌfʌndəˈmentəli/","adv.","根本上","The situation has fundamentally changed.","情况已根本改变。","论证"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明","This case illustrates the point.","该案例说明了这一点。","论证"),
  ("implication","/ˌɪmplɪˈkeɪʃn/","n.","含义","The implications are far-reaching.","其影响深远。","论证"),
  ("incontrovertible","/ˌɪnkənˈtrɜːvɜːtəbl/","adj.","无可辩驳的","The evidence is incontrovertible.","证据无可辩驳。","高分论证"),
  ("inevitably","/ɪnˈevɪtəbli/","adv.","不可避免地","Change will inevitably follow.","改变将不可避免地随之而来。","论证"),
  ("legitimate","/lɪˈdʒɪtɪmət/","adj.","合理的","They raised legitimate concerns.","他们提出了合理的关切。","论证"),
  ("mitigate","/ˈmɪtɪɡeɪt/","v.","缓解","Such measures mitigate the risk.","此类措施可缓解风险。","论证"),
  ("moreover","/mɔːrˈəʊvə/","adv.","而且","Moreover, it is cost-effective.","而且它划算。","论证"),
  ("nonetheless","/ˌnʌnðəˈles/","adv.","尽管如此","Nonetheless, the risk remains.","尽管如此，风险依然存在。","论证"),
  ("notwithstanding","/ˌnɒtwiðˈstændɪŋ/","prep.","尽管","Notwithstanding these limits, the trend holds.","尽管有这些局限，趋势依然成立。","高分论证"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","That's a plausible counterargument.","那是个貌似合理的反驳。","论证"),
  ("premise","/ˈpremɪs/","n.","前提","The argument rests on a weak premise.","该论证建立在薄弱前提上。","论证"),
  ("profound","/prəˈfaʊnd/","adj.","深刻的","It had a profound impact on policy.","它对政策有深远影响。","论证"),
  ("rationale","/ˌræʃəˈnɑːl/","n.","理由","Explain the rationale behind your choice.","说明你选择该方案的理由。","论证"),
  ("robust","/rəʊˈbʌst/","adj.","强健的；稳健的","The findings are robust across studies.","研究结果稳健一致。","论证"),
  ("sceptical","/ˈskeptɪkl/","adj.","怀疑的","I'm sceptical about these claims.","我对这些说法持怀疑。","论证"),
  ("substantiate","/səbˈstænʃieɪt/","v.","证实","Evidence substantiates the hypothesis.","证据证实了该假设。","论证"),
  ("thereby","/ˌðeəˈbaɪ/","adv.","从而","The reform raised income, thereby cutting poverty.","改革提高收入，从而减少贫困。","论证"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱","Misinformation undermines trust.","错误信息削弱信任。","论证"),
  ("unwarranted","/ʌnˈwɒrəntɪd/","adj.","无根据的","The panic was largely unwarranted.","这种恐慌大多没有根据。","论证"),
  ("viable","/ˈvaɪəbl/","adj.","可行的","We need a viable alternative.","我们需要可行的替代方案。","论证"),
  ("warrant","/ˈwɒrənt/","v.","使有必要；保证","The evidence warrants further study.","证据值得进一步研究。","高分论证"),
  ("whereas","/weərˈæz/","conj.","然而；而","Some praised it, whereas others criticized.","有人称赞，然而有人批评。","论证"),
  ("while acknowledging","/waɪl əkˈnɒlɪdʒɪŋ/","phr.","在承认……的同时","While acknowledging risks, I support the plan.","在承认风险的同时，我支持该计划。","高分论证"),
  ("insofar as","/ˌɪnsəʊˈfɑːr əz/","phr.","就…而言","It works insofar as users cooperate.","只要用户配合就有效。","高分论证"),
 ]),
 ("口语高分词与短语", [
  ("absolutely","/ˈæbsəluːtli/","adv.","绝对地；完全","I'd absolutely recommend it.","我绝对推荐。","口语"),
  ("actually","/ˈæktʃuəli/","adv.","其实；实际上","Actually, I'd rather stay home.","其实我更想待在家。","口语"),
  ("apparently","/əˈpærəntli/","adv.","据说；显然","Apparently the meeting is cancelled.","据说会议取消了。","口语"),
  ("basically","/ˈbeɪsɪkli/","adv.","基本上","Basically, I agree with you.","基本上我同意你。","口语"),
  ("definitely","/ˈdefɪnətli/","adv.","肯定地","I'll definitely come tonight.","今晚我一定来。","口语"),
  ("fairly","/ˈfeəli/","adv.","相当；公平地","It's fairly expensive.","它相当贵。","口语"),
  ("genuinely","/ˈdʒenjuɪnli/","adv.","真诚地；确实","I genuinely enjoyed the course.","我确实很享受这门课。","口语高分"),
  ("obviously","/ˈɒbviəsli/","adv.","显然","Obviously, that was a mistake.","那显然是个错误。","口语"),
  ("presumably","/prɪˈzjuːməbli/","adv.","大概；推测","Presumably you already know.","想必你已经知道了。","口语"),
  ("rather","/ˈrɑːðə/","adv.","相当；宁愿","It's rather cold outside.","外面相当冷。","口语"),
  ("slightly","/ˈslaɪtli/","adv.","略微","The results are slightly better.","结果略好一些。","口语"),
  ("to be honest","/tuː biː ˈɒnɪst/","phr.","老实说","To be honest, I didn't enjoy it.","老实说，我不太喜欢。","口语加分"),
  ("off the top of my head","/ɒf ðə tɒp əv maɪ hed/","phr.","凭记忆","Off the top of my head, about 30.","凭记忆，大约 30。","口语加分"),
  ("I'd say","/aɪd seɪ/","phr.","我认为","I'd say it's worth trying.","我认为值得一试。","口语加分"),
  ("the thing is","/ðə θɪŋ ɪz/","phr.","问题在于","The thing is, I can't afford it.","问题在于我负担不起。","口语加分"),
  ("at the end of the day","/ət ðə end əv ðə deɪ/","phr.","归根结底","At the end of the day, health matters most.","归根结底，健康最重要。","口语加分"),
  ("get the hang of","/ɡet ðə hæŋ əv/","phr.","掌握窍门","It took me a month to get the hang of it.","我花了一个月才掌握窍门。","口语加分"),
  ("run out of","/rʌn aʊt əv/","phr.","用完","We've run out of time.","我们时间用完了。","口语"),
  ("look forward to","/lʊk ˈfɔːwəd tuː/","phr.","期待","I look forward to hearing from you.","我期待你的回复。","口语"),
  ("put up with","/pʊt ʌp wɪð/","phr.","忍受","I can't put up with the noise.","我无法忍受噪音。","口语"),
  ("get along with","/ɡet əˈlɒŋ wɪð/","phr.","与…相处","We get along well.","我们相处得很好。","口语"),
  ("be keen on","/bi kiːn ɒn/","phr.","热衷于","She's keen on outdoor sports.","她热衷于户外运动。","口语"),
  ("have a soft spot for","/hæv ə sɒft spɒt fə/","phr.","偏爱","I have a soft spot for Italian food.","我偏爱意大利菜。","口语加分"),
  ("no sooner...than","/nəʊ ˈsuːə ðæn/","phr.","一……就……","No sooner did I arrive than it rained.","我一到就下雨了。","口语加分"),
  ("the last straw","/ðə lɑːst strɔː/","phr.","最后一根稻草","It was the last straw for me.","这成了压垮我的最后一根稻草。","口语加分"),
  ("hit the nail on the head","/hɪt ðə neɪl ɒn ðə hed/","phr.","正中要害","You hit the nail on the head.","你说到点子上了。","口语加分"),
  ("piece of cake","/piːs əv keɪk/","phr.","小菜一碟","The test was a piece of cake.","这次考试是小菜一碟。","口语"),
  ("break the ice","/breɪk ðaɪs/","phr.","打破僵局","He told a joke to break the ice.","他讲了个笑话打破僵局。","口语"),
  ("on the whole","/ɒn ðə həʊl/","phr.","总的来说","On the whole, it was rewarding.","总的来说，很有收获。","口语"),
  ("by the way","/baɪ ðə weɪ/","phr.","顺便说","By the way, thanks for your help.","顺便说，谢谢你的帮助。","口语"),
 ]),
 ("听力场景与话题词", [
  ("accommodation","/əˌkɒməˈdeɪʃn/","n.","住宿","Accommodation is included in the fee.","费用含住宿。","听力"),
  ("agenda","/əˈdʒendə/","n.","议程","Let's move to the next agenda item.","我们进入下一个议程事项。","会议"),
  ("announcement","/əˈnaʊnsmənt/","n.","通知；公告","The announcement surprised everyone.","公告让每个人惊讶。","听力"),
  ("campus","/ˈkæmpəs/","n.","校园","The university has a beautiful campus.","这所大学校园很美。","听力"),
  ("certificate","/səˈtɪfɪkət/","n.","证书","You'll receive a certificate after the course.","课程结束后你会拿到证书。","听力"),
  ("collaborate","/kəˈlæbəreɪt/","v.","合作","The two departments collaborate closely.","两个院系密切合作。","听力"),
  ("commence","/kəˈmens/","v.","开始","The course commences in September.","课程九月开始。","学术"),
  ("complaint","/kəmˈpleɪnt/","n.","投诉；抱怨","We received a formal complaint.","我们收到正式投诉。","听力"),
  ("confer","/kənˈfɜː/","v.","授予；商议","The university conferred honorary degrees.","大学授予荣誉学位。","学术"),
  ("convene","/kənˈviːn/","v.","召集；开会","The panel convened at nine.","评审团九点开会。","会议"),
  ("curriculum","/kəˈrɪkjələm/","n.","课程；课程表","The curriculum was redesigned.","课程体系被重新设计。","教育"),
  ("deadline","/ˈdedlaɪn/","n.","截止日期","The deadline is next Monday.","截止日期是下周一。","教育"),
  ("dormitory","/ˈdɔːmətri/","n.","宿舍","The dormitory has shared kitchens.","宿舍有共用厨房。","听力"),
  ("enrol","/ɪnˈrəʊl/","v.","注册；入学","Over 200 students enrolled in the course.","超过 200 名学生注册了该课程。","教育"),
  ("faculty","/ˈfæklti/","n.","全体教师；院系","The faculty approved the new syllabus.","教师们批准了新教学大纲。","教育"),
  ("grant","/ɡrɑːnt/","n./v.","拨款；授予","The university received a research grant.","大学获得一笔研究拨款。","教育"),
  ("internship","/ˈɪntɜːnʃɪp/","n.","实习","A three-month internship counts as experience.","三个月实习算作经验。","职场"),
  ("lecture","/ˈlektʃə/","n.","讲座；课","Attendance is compulsory for lectures.","讲座必须出席。","教育"),
  ("matriculate","/məˈtrɪkjuleɪt/","v.","录取入学","She matriculated at Oxford.","她被牛津大学录取。","学术"),
  ("prerequisite","/prɪˈrekəwəzɪt/","n.","先修要求","Math is a prerequisite for this course.","数学是这门课的先修要求。","教育"),
  ("semester","/sɪˈmestə/","n.","学期","The semester begins in late September.","学期九月下旬开始。","教育"),
  ("syllabus","/ˈsɪləbəs/","n.","教学大纲","The syllabus lists twelve topics.","大纲列出十二个主题。","教育"),
  ("transcript","/ˈtrænskrɪpt/","n.","成绩单","Please attach your transcript.","请附上你的成绩单。","教育"),
  ("tuition","/tjuˈɪʃn/","n.","学费；教学","Tuition has risen this year.","今年学费上涨了。","教育"),
  ("vaccination","/ˌvæksɪˈneɪʃn/","n.","疫苗接种","Bring your vaccination record.","带上你的疫苗接种记录。","健康"),
  ("allergy","/ˈælədʒi/","n.","过敏","He has a pollen allergy.","他有花粉过敏。","健康"),
  ("symptom","/ˈsɪmptəm/","n.","症状","Describe any symptoms you have.","描述你有的任何症状。","健康"),
  ("prescription","/prɪˈskrɪpʃn/","n.","处方","You'll need a prescription.","你需要处方。","健康"),
  ("physician","/fɪˈzɪʃn/","n.","内科医生","Consult a physician before starting.","开始前请咨询内科医生。","健康"),
  ("pharmacy","/ˈfɑːməsi/","n.","药房","The pharmacy opens at nine.","药房九点开门。","健康"),
  ("ambulance","/ˈæmbjələns/","n.","救护车","Call an ambulance immediately.","立即叫救护车。","紧急"),
  ("emergency","/iˈmɜːdʒənsi/","n.","紧急情况","In an emergency, dial 999.","紧急情况下拨 999。","紧急"),
  ("insurance","/ɪnˈʃʊərəns/","n.","保险","Travel insurance is strongly advised.","强烈建议购买旅行保险。","安全"),
 ]),
]

# ============ 托福 TOEFL（按学科分块）============
TOEFL = [
 ("学术通用词", [
  ("abstract","/ˈæbstrækt/","adj./n.","抽象的；摘要","Abstract concepts are hard to test.","抽象概念难以测试。","学术"),
  ("adhere","/ədˈhɪə/","v.","坚持","Researchers must adhere to ethical standards.","研究者必须遵守伦理标准。","学术"),
  ("allocate","/ˈæləkeɪt/","v.","分配","The lab allocated funds to equipment.","实验室拨款购置设备。","学术"),
  ("analogy","/əˈnælədʒi/","n.","类比","He drew an analogy between the systems.","他对两个系统作了类比。","学术"),
  ("assess","/əˈses/","v.","评估","We assess performance annually.","我们每年评估表现。","学术"),
  ("attribute","/əˈtrɪbjuːt/","v.","归因于","She attributes the growth to policy.","她把增长归因于政策。","学术"),
  ("coherent","/kəʊˈhɪərənt/","adj.","连贯的","A coherent framework guides the study.","连贯的框架指导研究。","学术"),
  ("comprehensive","/ˌkɒmprɪˈhensɪv/","adj.","全面的","It offers a comprehensive review.","它提供了全面综述。","学术"),
  ("derive","/dɪˈraɪv/","v.","源自；获得","The method derives from earlier work.","该方法源自早期工作。","学术"),
  ("empirical","/ɪmˈpɪrɪkl/","adj.","实证的","The theory needs empirical support.","该理论需要实证支持。","学术"),
  ("evaluate","/ɪˈvæljueɪt/","v.","评估","Evaluate the results carefully.","仔细评估结果。","学术"),
  ("formulate","/ˈfɔːmjuleɪt/","v.","制定","They formulated a new hypothesis.","他们提出了新假设。","学术"),
  ("fundamental","/ˌfʌndəˈmentl/","adj.","根本的","This is a fundamental limitation.","这是一个根本限制。","学术"),
  ("hypothesis","/haɪˈpɒθəsɪs/","n.","假设","The hypothesis was supported by data.","假设得到了数据支持。","学术"),
  ("implication","/ˌɪmplɪˈkeɪʃn/","n.","含义","The implications extend to other fields.","其含义延伸到其他领域。","学术"),
  ("interpret","/ɪnˈtɜːprɪt/","v.","解释","How do you interpret these results?","你如何解释这些结果？","学术"),
  ("methodology","/ˌmeθəˈdɒlədʒi/","n.","方法论","The methodology is clearly described.","方法论描述清晰。","学术"),
  ("phenomenon","/fəˈnɒmɪnən/","n.","现象","The phenomenon is well documented.","该现象有充分记载。","学术"),
  ("principle","/ˈprɪnsəpl/","n.","原理；原则","The experiment follows basic principles.","该实验遵循基本原理。","学术"),
  ("rigorous","/ˈrɪɡərəs/","adj.","严谨的","Rigorous testing is essential.","严格测试必不可少。","学术"),
  ("synthesize","/ˈsɪnθəsaɪz/","v.","综合","The paper synthesizes two approaches.","该论文综合了两种方法。","学术"),
  ("theoretical","/ˌθɪəˈretɪkl/","adj.","理论的","The theoretical model matches observations.","理论模型与观测相符。","学术"),
  ("valid","/ˈvælɪd/","adj.","有效的","The conclusion is logically valid.","该结论逻辑上有效。","学术"),
  ("variable","/ˈveəriəbl/","n./adj.","变量；可变的","Temperature is the key variable.","温度是关键变量。","学术"),
  ("verify","/ˈverɪfaɪ/","v.","核实","Verify each citation before submitting.","提交前核实每条引文。","学术"),
  ("acquisition","/ˌækwɪˈzɪʃn/","n.","习得；获得","Second-language acquisition varies widely.","二语习得差异很大。","语言学"),
  ("bilingual","/ˌbaɪˈlɪŋɡwəl/","adj.","双语的","Bilingual children switch languages easily.","双语儿童能轻松切换语言。","语言学"),
  ("cognition","/kɒɡˈnɪʃn/","n.","认知","Cognition is affected by sleep.","睡眠影响认知。","语言学"),
  ("fluency","/ˈfluːənsi/","n.","流利","Fluency matters more than accuracy.","流利度比准确度更重要。","语言学"),
  ("heuristic","/hjʊəˈrɪstɪk/","n./adj.","启发法；直觉的","Learners develop a heuristic for guessing.","学习者形成猜测的启发法。","语言学"),
  ("phonetic","/fəˈnetɪk/","adj.","语音的","Phonetic drills improve pronunciation.","语音操练能改善发音。","语言学"),
  ("proficiency","/prəˈfɪʃnsi/","n.","熟练度","Test proficiency at three levels.","测试三个水平的熟练度。","语言学"),
  ("syntax","/ˈsɪntæks/","n.","句法","Syntax errors reveal second-language influence.","句法错误显示二语影响。","语言学"),
  ("verbal","/ˈvɜːbl/","adj.","言语的","The test measures verbal reasoning.","该测试衡量言语推理。","语言学"),
  ("vestibule","/ˈvestɪbjuːl/","n.","前庭；过渡","The vestibule course smooths the transition.","过渡课程平滑了转变。","语言学"),
  ("ameliorate","/əˈmiːliəreɪt/","v.","改善","The reform helped ameliorate conditions.","改革帮助改善了状况。","高分词"),
  ("anomaly","/əˈnɒməli/","n.","异常","The data contain an anomaly.","数据中含一个异常值。","学术"),
  ("assimilate","/əˈsɪməleɪt/","v.","吸收","Students assimilate new vocabulary.","学生吸收新词汇。","学术"),
  ("chronological","/ˌkrɒnəˈlɒdʒɪkl/","adj.","按时间顺序的","Arrange the events chronologically.","按时间顺序安排事件。","学术"),
  ("coincide","/ˌkəʊɪnˈsaɪd/","v.","同时发生","The publication coincided with the discovery.","出版物与发现同时出现。","学术"),
  ("constitute","/ˈkɒnstɪtjuːt/","v.","构成","These cases constitute a clear pattern.","这些案例构成清晰的模式。","学术"),
  ("convergence","/kənˈvɜːdʒəns/","n.","趋同；汇合","The convergence of trends is striking.","多种趋势的趋同很引人注目。","学术"),
  ("delineate","/dɪˈlɪnieɪt/","v.","勾勒；阐明","The study delineates causal pathways.","该研究阐明了因果路径。","学术"),
  ("empirical","/ɪmˈpɪrɪkl/","adj.","实证的","More empirical work is needed.","需要更多实证研究。","学术"),
  ("extrapolate","/ɪkˈstræpəleɪt/","v.","外推","Don't extrapolate beyond the data.","不要超出数据外推。","学术"),
  ("fluctuate","/ˈflʌktʃueɪt/","v.","波动","Measurements fluctuated throughout.","测量值全程波动。","学术"),
  ("hierarchy","/ˈhaɪərɑːki/","n.","层级","The data reveal a social hierarchy.","数据揭示了社会层级。","学术"),
  ("imminent","/ˈɪmɪnənt/","adj.","迫在眉睫的","A crisis seems imminent.","危机似乎迫在眉睫。","学术"),
  ("inherent","/ɪnˈhɪərənt/","adj.","固有的","The risk is inherent in the method.","该方法有固有风险。","学术"),
  ("latent","/ˈleɪtnt/","adj.","潜在的","Latent demand remains unexplored.","潜在需求仍未挖掘。","学术"),
  ("magnitude","/ˈmæɡnɪtjuːd/","n.","量级；重要性","Estimate the magnitude of the effect.","估计效应量级。","学术"),
  ("nuanced","/ˈnjuːɑːnst/","adj.","细致入微的","The analysis is nuanced.","该分析细致入微。","学术"),
  ("paradigm","/ˈpærədaɪm/","n.","范式","It caused a paradigm shift.","它促成了范式转变。","学术"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","Several explanations are plausible.","若干解释都说得通。","学术"),
  ("preliminary","/prɪˈlɪmɪnəri/","adj.","初步的","These are preliminary findings.","这些是初步结果。","学术"),
  ("prevalent","/ˈprevələnt/","adj.","普遍的","The trait is prevalent in the population.","该特征在人群中普遍。","学术"),
  ("salient","/ˈseɪliənt/","adj.","显著的","Focus on the salient differences.","关注显著的差异。","学术"),
  ("synthesize","/ˈsɪnθəsaɪz/","v.","综合","Synthesize the literature in the review.","在综述中综合文献。","学术"),
  ("threshold","/ˈθreʃhəʊld/","n.","阈值","Values below the threshold are excluded.","低于阈值的数值被排除。","学术"),
  ("trajectory","/trəˈdʒektəri/","n.","轨迹；发展路径","The field's trajectory has changed.","该领域的发展轨迹已变。","学术"),
  ("undermine","/ˌʌndəˈmaɪn/","v.","削弱","Replication failures undermine confidence.","重复实验失败削弱信心。","学术"),
  ("versatile","/ˈvɜːsətaɪl/","adj.","多用途的","Enzymes are versatile catalysts.","酶是多用途催化剂。","学术"),
  ("viable","/ˈvaɪəbl/","adj.","可行的","The method is not commercially viable.","该方法商业上不可行。","学术"),
  ("warrant","/ˈwɒrənt/","v.","使有必要","The findings warrant further study.","这些发现值得进一步研究。","学术"),
 ]),
 ("自然科学词汇", [
  ("antibiotic","/ˌæntibaɪˈɒtɪk/","n.","抗生素","Antibiotics are useless against viruses.","抗生素对病毒无效。","生物"),
  ("biodiversity","/ˌbaɪəʊdaɪˈvɜːsəti/","n.","生物多样性","Biodiversity is under threat.","生物多样性正受威胁。","生物"),
  ("carbon","/ˈkɑːbən/","n.","碳","Carbon emissions reached a record.","碳排放创纪录。","环境"),
  ("catalyst","/ˈkætəlɪst/","n.","催化剂","Iron acts as a catalyst.","铁起催化作用。","化学"),
  ("cell","/sel/","n.","细胞；电池","Each cell contains genetic material.","每个细胞都含有遗传物质。","生物"),
  ("chromosome","/ˈkrəʊməsəʊm/","n.","染色体","Humans have 46 chromosomes.","人类有 46 条染色体。","生物"),
  ("compound","/ˈkɒmpaʊnd/","n.","化合物","The compound reacts with water.","该化合物与水反应。","化学"),
  ("convection","/kənˈvekʃn/","n.","对流","Heat is transferred by convection.","热通过对流传递。","物理"),
  ("dioxide","/daɪˈɒksaɪd/","n.","二氧化物","Carbon dioxide traps heat.","二氧化碳困住热量。","环境"),
  ("ecology","/iˈkɒlədʒi/","n.","生态","The dam altered local ecology.","大坝改变了当地生态。","环境"),
  ("ecosystem","/ˈiːkəʊsɪstəm/","n.","生态系统","The forest ecosystem recovered.","森林生态系统恢复了。","环境"),
  ("emission","/ɪˈmɪʃn/","n.","排放","Emissions fell by 12 percent.","排放下降了百分之十二。","环境"),
  ("enzyme","/ˈenzaɪm/","n.","酶","The enzyme breaks down glucose.","该酶分解葡萄糖。","生物"),
  ("fossil","/ˈfɒsl/","n.","化石","The fossil is 50 million years old.","该化石有五千万年历史。","地质"),
  ("genome","/ˈdʒiːnəʊm/","n.","基因组","The human genome was mapped in 2003.","人类基因组于 2003 年被绘制。","生物"),
  ("glacier","/ˈɡlæsiə/","n.","冰川","The glacier is retreating rapidly.","冰川正在快速后退。","地质"),
  ("habitat","/ˈhæbɪtæt/","n.","栖息地","Logging destroyed the habitat.","伐木破坏了这个栖息地。","生物"),
  ("hydrogen","/ˈhaɪdrədʒən/","n.","氢","Hydrogen fuel may replace petrol.","氢燃料可能取代汽油。","化学"),
  ("inertia","/ɪˈnɜːʃə/","n.","惯性","Inertia keeps the object moving.","惯性使物体继续运动。","物理"),
  ("isotope","/ˈaɪsətəʊp/","n.","同位素","Scientists dated the rock using isotopes.","科学家用同位素测定了岩石年代。","地质"),
  ("larva","/ˈlɑːvə/","n.","幼虫","The larva feeds on leaves.","幼虫以树叶为食。","生物"),
  ("molecule","/ˈmɒlɪkjuːl/","n.","分子","A water molecule has two hydrogen atoms.","一个水分子含两个氢原子。","化学"),
  ("neutron","/ˈnjuːtrɒn/","n.","中子","Neutrons have no electric charge.","中子不带电。","物理"),
  ("nutrient","/ˈnjuːtriənt/","n.","养分；营养素","Floods wash away nutrients.","洪水冲走养分。","环境"),
  ("organism","/ˈɔːɡənɪzəm/","n.","生物体","Each organism adapts to its habitat.","每个生物都适应其栖息地。","生物"),
  ("particle","/ˈpɑːtɪkl/","n.","微粒；粒子","Particles cluster into clouds.","微粒聚集成云。","物理"),
  ("photosynthesis","/ˌfəʊtəʊˈsɪnθəsɪs/","n.","光合作用","Photosynthesis converts light into energy.","光合作用把光转化为能量。","生物"),
  ("pollutant","/pəˈluːtənt/","n.","污染物","Industrial pollutants entered the river.","工业污染物进入河流。","环境"),
  ("precipitation","/prɪˌsɪpɪˈteɪʃn/","n.","降水","Precipitation increased after the dam.","大坝建成后降水增加。","地理"),
  ("protein","/ˈprəʊtiːn/","n.","蛋白质","The body needs protein to repair tissue.","身体需要蛋白质修复组织。","生物"),
  ("radiation","/ˌreɪdiˈeɪʃn/","n.","辐射","The ozone layer blocks harmful radiation.","臭氧层阻挡有害辐射。","物理"),
  ("sediment","/ˈsedɪmənt/","n.","沉积物","River sediment buried the ruins.","河流沉积物掩埋了遗迹。","地质"),
  ("solar","/ˈsəʊlə/","adj.","太阳的","Solar power costs keep falling.","太阳能成本持续下降。","环境"),
  ("species","/ˈspiːʃiːz/","n.","物种","Many species face extinction.","许多物种面临灭绝。","生物"),
  ("sphere","/sfɪə/","n.","球体；领域","Ozone is a layer in the upper sphere.","臭氧是高层大气中的层。","地理"),
  ("stagnant","/ˈstæɡnənt/","adj.","停滞的","Stagnant water breeds mosquitoes.","死水滋生蚊虫。","环境"),
  ("stimulus","/ˈstɪmjələs/","n.","刺激；刺激物","Plants respond to the stimulus of light.","植物对光的刺激作出反应。","生物"),
  ("tectonic","/tekˈtɒnɪk/","adj.","构造的","Tectonic shifts cause earthquakes.","构造运动导致地震。","地质"),
  ("thermal","/ˈθɜːml/","adj.","热的；热量的","Thermal insulation reduces costs.","隔热可降低成本。","物理"),
  ("turbine","/ˈtɜːbaɪn/","n.","涡轮机","The turbine generates electricity.","该涡轮机发电。","工程"),
  ("vegetation","/ˌvedʒəˈteɪʃn/","n.","植被","Vegetation returned after the fire.","火灾后植被恢复了。","环境"),
  ("velocity","/vəˈlɒsəti/","n.","速度","The object gained velocity.","该物体获得了速度。","物理"),
  ("viscosity","/vɪˈskɒsəti/","n.","粘度","Viscosity rises with temperature.","粘度随温度上升。","物理"),
  ("voltage","/ˈvəʊltɪdʒ/","n.","电压","Higher voltage increases risk.","更高电压增加风险。","物理"),
 ]),
 ("人文社科词汇", [
  ("anthropology","/ˌænθrəˈpɒlədʒi/","n.","人类学","Anthropology studies human cultures.","人类学研究人类文化。","人文"),
  ("archaeology","/ˌɑːkiˈɒlədʒi/","n.","考古学","Archaeology reveals ancient trade routes.","考古学揭示古代贸易路线。","人文"),
  ("aesthetic","/iːsˈθetɪk/","adj.","审美的","The museum has aesthetic value.","博物馆有审美价值。","人文"),
  ("artifact","/ˈɑːtɪfækt/","n.","人工制品；文物","The artifacts date to the Bronze Age.","这些文物可追溯至青铜时代。","人文"),
  ("assimilation","/əˌsɪməˈleɪʃn/","n.","同化；吸收","Language assimilation can be rapid.","语言同化可能很快。","人文"),
  ("capitalism","/ˈkæpɪtəlɪzəm/","n.","资本主义","Critiques of capitalism are centuries old.","对资本主义的批评已有数百年。","人文"),
  ("census","/ˈsensəs/","n.","人口普查","The census counts residents.","人口普查统计居民。","人文"),
  ("colonial","/kəˈləʊniəl/","adj.","殖民地的","Colonial rule reshaped the economy.","殖民统治重塑了经济。","人文"),
  ("constitution","/ˌkɒnstɪˈtjuːʃn/","n.","宪法；构成","The constitution guarantees free speech.","宪法保障言论自由。","人文"),
  ("democracy","/dɪˈmɒkrəsi/","n.","民主","The country became a democracy.","该国成为民主国家。","人文"),
  ("dialect","/ˈdaɪəlekt/","n.","方言","The dialect is dying out.","这种方言正在消亡。","语言"),
  ("discourse","/ˈdɪskɔːs/","n.","话语；论述","Political discourse shifted after the crisis.","危机后政治话语转变。","人文"),
  ("ecology","/iˈkɒlədʒi/","n.","生态","The ecology of the region changed.","该地区生态发生了变化。","人文"),
  ("ethnicity","/eθˈnɪsəti/","n.","族裔","The census asked about ethnicity.","人口普查询问族裔。","人文"),
  ("geography","/dʒiˈɒɡrəfi/","n.","地理","Geography shaped trade routes.","地理塑造了贸易路线。","人文"),
  ("heritage","/ˈherɪtɪdʒ/","n.","遗产","The site is a world heritage landmark.","该地是世界遗产地标。","人文"),
  ("hierarchy","/ˈhaɪərɑːki/","n.","等级制度","The social hierarchy was rigid.","社会等级制度很僵化。","人文"),
  ("ideology","/ˌaɪdiˈɒlədʒi/","n.","意识形态","Ideology shaped the interpretation.","意识形态影响了阐释。","人文"),
  ("indigenous","/ɪnˈdɪdʒənəs/","adj.","本土的；原住民的","Indigenous knowledge was disregarded.","本土知识曾被忽视。","人文"),
  ("institution","/ˌɪnstɪˈtjuːʃn/","n.","机构；制度","The institution has changed over time.","该机构随时间发生了变化。","人文"),
  ("legitimacy","/lɪˈdʒɪtɪməsi/","n.","合法性；正统性","The crisis questioned the regime's legitimacy.","危机质疑了政权的合法性。","人文"),
  ("linguistics","/lɪŋˈɡwɪstɪks/","n.","语言学","Linguistics studies language structure.","语言学研究语言结构。","语言"),
  ("migration","/maɪˈɡreɪʃn/","n.","迁移","Migration changed the city's demographics.","迁移改变了城市人口结构。","人文"),
  ("monument","/ˈmɒnjumənt/","n.","纪念碑；遗迹","The monument commemorates a battle.","该纪念碑纪念一场战役。","人文"),
  ("mythology","/mɪˈθɒlədʒi/","n.","神话","The story comes from ancient mythology.","这个故事源自古代神话。","人文"),
  ("nomadic","/nəʊˈmædɪk/","adj.","游牧的","Nomadic tribes followed the herds.","游牧部落追随牧群。","人文"),
  ("paradox","/ˈpærədɒks/","n.","悖论","It's a paradox that more choice reduces satisfaction.","选择越多满意度越低是个悖论。","人文"),
  ("prejudice","/ˈpredʒudɪs/","n.","偏见","The study examined racial prejudice.","该研究考察了种族偏见。","人文"),
  ("ritual","/ˈrɪtʃuəl/","n.","仪式","The ritual takes place annually.","该仪式每年举行。","人文"),
  ("sociology","/ˌsəʊsiˈɒlədʒi/","n.","社会学","Sociology examines social structures.","社会学研究社会结构。","人文"),
  ("sovereignty","/ˈsɒvrənti/","n.","主权","The treaty respected sovereignty.","该条约尊重主权。","人文"),
  ("stereotype","/ˈsteriətaɪp/","n.","刻板印象","The film challenges stereotypes.","这部电影挑战刻板印象。","人文"),
  ("taboo","/təˈbuː/","n./adj.","禁忌","The topic remains a taboo.","这个话题仍是禁忌。","人文"),
  ("anthropological","/ˌænθrəˈpɒlədʒɪkl/","adj.","人类学的","The findings have anthropological significance.","这些发现具有人类学意义。","人文"),
  ("archaeological","/ˌɑːkiəˈlɒdʒɪkl/","adj.","考古学的","Archaeological evidence contradicts the text.","考古证据与文本矛盾。","人文"),
  ("demographic","/ˌdeməˈɡræfɪk/","adj.","人口统计的","Demographic change reshaped demand.","人口变化重塑了需求。","人文"),
  ("ideological","/ˌaɪdiəˈlɒdʒɪkl/","adj.","意识形态的","The dispute was partly ideological.","这场争论部分是意识形态的。","人文"),
  ("linguistic","/lɪŋˈɡwɪstɪk/","adj.","语言的","Linguistic change spread rapidly.","语言变化传播很快。","语言"),
  ("monumental","/ˌmɒnjuˈmentl/","adj.","纪念性的；重大的","It was a monumental achievement.","这是项重大成就。","人文"),
  ("paradoxical","/ˌpærəˈdɒksɪkl/","adj.","矛盾的","The result seems paradoxical.","结果看似矛盾。","人文"),
  ("ritualistic","/ˌrɪtʃuəˈlɪstɪk/","adj.","仪式的","The practice became ritualistic.","这种做法变得仪式化。","人文"),
  ("structural","/ˈstrʌktʃərəl/","adj.","结构的","Structural change was needed.","需要结构性改变。","人文"),
  ("symbolize","/ˈsɪmbəlaɪz/","v.","象征","The dove symbolizes peace.","鸽子象征和平。","人文"),
  ("synthesis","/ˈsɪnθəsɪs/","n.","综合","The book offers a synthesis of views.","该书综合了多种观点。","人文"),
  ("unprecedented","/ʌnˈpresɪdentɪd/","adj.","空前的","The scale was unprecedented.","规模空前。","人文"),
  ("verifiable","/ˈverɪfaɪəbl/","adj.","可验证的","Claims must be verifiable.","说法必须可验证。","人文"),
 ]),
 ("讲座信号词与口语", [
  ("allude","/əˈluːd/","v.","暗指；提及","The author alluded to earlier work.","作者提及了早期工作。","讲座信号"),
  ("alternatively","/ɔːlˈtɜːnətɪvli/","adv.","或者；作为替代","Alternatively, we could expand it.","或者我们可以扩展它。","讲座信号"),
  ("assume","/əˈsjuːm/","v.","假定","Let us assume the premise is true.","让我们假定该前提成立。","讲座信号"),
  ("briefly","/ˈbriːfli/","adv.","简要地","Let me briefly summarize the findings.","我简要总结一下发现。","讲座信号"),
  ("clarify","/ˈklærɪfaɪ/","v.","澄清","Let me clarify that point.","让我澄清那一点。","讲座信号"),
  ("conclude","/kənˈkluːd/","v.","总结；断定","To conclude, evidence is essential.","总之，证据必不可少。","讲座信号"),
  ("consequently","/ˈkɒnsɪkwəntli/","adv.","因此","Consequently, costs rose.","因此成本上升了。","讲座信号"),
  ("contrast","/ˈkɒntrɑːst/","n./v.","对比；对照","In contrast, the other group improved.","相比之下，另一组有所改善。","讲座信号"),
  ("elaborate","/ɪˈlæbərət/","v.","详述","Could you elaborate on the second point?","你能详细说第二点吗？","讲座信号"),
  ("emphasize","/ˈemfəsaɪz/","v.","强调","I want to emphasize one caveat.","我想强调一点需要注意的。","讲座信号"),
  ("exemplify","/ɪɡˈzemplɪfaɪ/","v.","举例说明","Let me exemplify with a case.","我用一个案例举例说明。","讲座信号"),
  ("illustrate","/ˈɪləstreɪt/","v.","说明","This diagram illustrates the process.","这张图说明了流程。","讲座信号"),
  ("imply","/ɪmˈplaɪ/","v.","暗示","This implies a causal relationship.","这暗示存在因果关系。","讲座信号"),
  ("namely","/ˈneɪmli/","adv.","即；也就是","Three factors matter, namely cost, time and risk.","三个因素重要，即成本、时间与风险。","讲座信号"),
  ("notwithstanding","/ˌnɒtwiðˈstændɪŋ/","prep.","尽管","Notwithstanding the limitations, the study is valuable.","尽管有局限，这研究仍有价值。","讲座信号"),
  ("overall","/ˌəʊvərˈɔːl/","adv./adj.","总体上；总体的","Overall, the results were promising.","总体而言，结果令人鼓舞。","讲座信号"),
  ("presumably","/prɪˈzjuːməbli/","adv.","大概","Presumably that's the main point.","大概那就是要点。","讲座信号"),
  ("provided that","/prəˈvaɪdɪd ðæt/","phr.","假如","It works provided that conditions are met.","若条件满足则有效。","讲座信号"),
  ("qualify","/ˈkwɒlɪfaɪ/","v.","限定；使合格","Let me qualify that statement.","让我对那个说法加个限定。","讲座信号"),
  ("recall","/rɪˈkɔːl/","v.","回想；召回","As I recall, she opposed it.","据我回忆，她反对。","讲座信号"),
  ("that is to say","/ðæt ɪz tuː seɪ/","phr.","也就是说","It is costly, that is to say beyond our means.","它很贵，也就是说超出我们负担。","讲座信号"),
  ("to sum up","/tuː sʌm ʌp/","phr.","总而言之","To sum up, three points emerged.","总而言之，浮现出三点。","讲座信号"),
  ("whereby","/weəˈbaɪ/","adv.","凭借；借此","A system whereby errors are logged.","一种记录错误的系统。","讲座信号"),
  ("accordingly","/əˈkɔːdɪŋli/","adv.","因此；相应地","Accordingly, the budget was cut.","因此预算被削减。","讲座信号"),
  ("conversely","/ˈkɒnvɜːsli/","adv.","相反地","Conversely, small firms benefited.","相反，小公司受益了。","讲座信号"),
  ("furthermore","/ˌfɜːðəˈmɔː/","adv.","此外","Furthermore, costs remain low.","此外，成本仍然较低。","讲座信号"),
  ("nevertheless","/ˌnevəðəˈles/","adv.","尽管如此","Nevertheless, the evidence is weak.","尽管如此，证据仍薄弱。","讲座信号"),
  ("plausible","/ˈplɔːzəbl/","adj.","貌似合理的","That's a plausible interpretation.","那是个貌似合理的解读。","讲座信号"),
  ("albeit","/ɔːlˈbiːɪt/","conj.","尽管","Cheap, albeit less effective.","便宜，尽管效果较差。","讲座信号"),
  ("in a nutshell","/ɪn ə nʌtˈʃel/","phr.","简言之","In a nutshell, cost is the issue.","简言之，问题在于成本。","口语"),
  ("that being said","/ðæt ˈbiːɪŋ sɛd/","phr.","话虽如此","That being said, the method works.","话虽如此，这方法有效。","口语"),
  ("if anything","/ɪf ˈeniθɪŋ/","phr.","如果有什么不同的话","If anything, it got better.","要说什么的话，反而变好了。","口语"),
  ("come down to","/kʌm daʊn tuː/","phr.","归结为","It comes down to funding.","归根结底是资金问题。","口语"),
  ("rule out","/ruːl aʊt/","phr.","排除","We can't rule out other causes.","我们无法排除其他原因。","口语"),
  ("account for","/əˈkaʊnt fɔː/","phr.","解释；占比","Genetics account for part of it.","遗传因素占部分原因。","口语"),
  ("bring up","/brɪŋ ʌp/","phr.","提出；抚养","She brought up a valid concern.","她提出了一个合理的关切。","口语"),
  ("figure out","/ˈfɪɡə aʊt/","phr.","弄明白","We finally figured it out.","我们最终弄明白了。","口语"),
  ("point out","/pɔɪnt aʊt/","phr.","指出","The professor pointed out a flaw.","教授指出了一个缺陷。","口语"),
  ("take into consideration","/teɪk ɪntuː kənˌsɪdəˈreɪʃn/","phr.","考虑","We must take cost into consideration.","我们必须考虑成本。","口语"),
  ("draw a conclusion","/drɔː ə kənˈkluːʒn/","phr.","得出结论","It's too early to draw a conclusion.","下结论还为时过早。","口语"),
  ("shed light on","/ʃed laɪt ɒn/","phr.","阐明","The study shed light on the issue.","该研究阐明了这一问题。","口语加分"),
  ("bear in mind","/beər ɪn maɪnd/","phr.","记住","Bear in mind the time limit.","记住时间限制。","口语加分"),
 ]),
]

# ============ 出国生活流水英语（最强调"能用"）============
ORAL = [
 ("租房与居住", [
  ("accommodation","/əˌkɒməˈdeɪʃn/","n.","住宿","Accommodation is included.","住宿已包含在内。","租房"),
  ("apartment","/əˈpɑːtmənt/","n.","公寓","The apartment has two bedrooms.","这套公寓有两个卧室。","租房"),
  ("deposit","/dɪˈpɒzɪt/","n.","押金","The deposit is one month's rent.","押金是一个月房租。","租房"),
  ("furnished","/ˈfɜːnɪʃt/","adj.","带家具的","It's a furnished flat.","这是带家具的公寓。","租房"),
  ("landlord","/ˈlændlɔːd/","n.","房东","The landlord raised the rent.","房东涨了房租。","租房"),
  ("lease","/liːs/","n./v.","租约；出租","The lease runs for twelve months.","租约为期十二个月。","租房"),
  ("mortgage","/ˈmɔːɡɪdʒ/","n.","按揭","They pay a monthly mortgage.","他们每月付按揭。","租房"),
  ("neighbourhood","/ˈneɪbəhʊd/","n.","街区","It's a quiet neighbourhood.","这是安静的街区。","租房"),
  ("rent","/rent/","n./v.","租金；出租","The rent includes bills.","租金包含水电费。","租房"),
  ("utilities","/juːˈtɪlətiz/","n.","水电煤费","Utilities are quite expensive.","水电费相当贵。","租房"),
  ("view","/vjuː/","n.","景观；看法","The flat has a good view.","这套公寓景观很好。","租房"),
  ("agency","/ˈeɪdʒənsi/","n.","中介","The agency charged a fee.","中介收了费用。","租房"),
  ("application","/ˌæplɪˈkeɪʃn/","n.","申请","I submitted an application online.","我在线提交了申请。","租房"),
  ("spacious","/ˈspeɪʃəs/","adj.","宽敞的","The kitchen is quite spacious.","厨房相当宽敞。","租房"),
  ("basement","/ˈbeɪsmənt/","n.","地下室","The laundry is in the basement.","洗衣房在地下室。","租房"),
 ]),
 ("银行与支付", [
  ("account","/əˈkaʊnt/","n.","账户","I opened a bank account.","我开了银行账户。","银行"),
  ("atm","/ˌeɪ tiː ˈem/","n.","自动取款机","There's an ATM around the corner.","拐角处有取款机。","银行"),
  ("balance","/ˈbæləns/","n.","余额","Check your account balance.","查看你的账户余额。","银行"),
  ("branch","/brɑːntʃ/","n.","分行","The bank has a branch nearby.","附近有一家分行。","银行"),
  ("deposit","/dɪˈpɒzɪt/","n./v.","存款；存入","I'd like to make a deposit.","我想存一笔款。","银行"),
  ("exchange rate","/ɪksˈtʃeɪndʒ reɪt/","n.","汇率","The exchange rate fluctuates daily.","汇率每日波动。","银行"),
  ("interest","/ˈɪntrəst/","n.","利息","The account pays little interest.","该账户利息很低。","银行"),
  ("loan","/ləʊn/","n.","贷款","They applied for a mortgage loan.","他们申请了按揭贷款。","银行"),
  ("overdraft","/ˈəʊvədrɑːft/","n.","透支","Avoid using an overdraft.","避免使用透支。","银行"),
  ("receipt","/rɪˈsiːt/","n.","收据","Keep the receipt for your records.","保留收据备查。","银行"),
  ("transaction","/trænˈzækʃn/","n.","交易","Check your recent transactions.","查看你近期的交易。","银行"),
  ("transfer","/trænsˈfɜː/","v./n.","转账","I transferred money this morning.","我今早转了账。","银行"),
  ("withdraw","/wɪðˈdrɔː/","v.","取款","I need to withdraw some cash.","我需要取些现金。","银行"),
  ("cheque","/tʃek/","n.","支票","She wrote a cheque.","她开了一张支票。","银行"),
  ("debt","/det/","n.","债务","He paid off his debt.","他还清了债务。","银行"),
  ("insurance","/ɪnˈʃʊərəns/","n.","保险","Do you have health insurance?","你有医疗保险吗？","银行"),
 ]),
 ("就医与健康", [
  ("appointment","/əˈpɔɪntmənt/","n.","预约","I'd like to make an appointment.","我想预约。","就医"),
  ("symptom","/ˈsɪmptəm/","n.","症状","Describe your symptoms.","描述你的症状。","就医"),
  ("prescription","/prɪˈskrɪpʃn/","n.","处方","The doctor wrote a prescription.","医生开了处方。","就医"),
  ("pharmacy","/ˈfɑːməsi/","n.","药房","The pharmacy is next door.","药房在隔壁。","就医"),
  ("physician","/fɪˈzɪʃn/","n.","内科医生","See a physician first.","先看内科医生。","就医"),
  ("allergy","/ˈælədʒi/","n.","过敏","I'm allergic to peanuts.","我对花生过敏。","就医"),
  ("fever","/ˈfiːvə/","n.","发烧","He has a high fever.","他发高烧。","就医"),
  ("cough","/kɒf/","n./v.","咳嗽","I have a bad cough.","我咳嗽得厉害。","就医"),
  ("painkiller","/ˈpeɪnkɪlə/","n.","止痛药","Take a painkiller if needed.","需要时可服止痛药。","就医"),
  ("insurance","/ɪnˈʃʊərəns/","n.","保险","Is it covered by insurance?","保险涵盖吗？","就医"),
  ("referral","/rɪˈfɜːrəl/","n.","转诊","You'll need a referral.","你需要转诊。","就医"),
  ("clinic","/ˈklɪnɪk/","n.","诊所","The clinic opens at eight.","诊所八点开门。","就医"),
  ("immunization","/ɪˌmjuːnɪˈzeɪʃn/","n.","免疫接种","Check your immunization record.","查看你的接种记录。","就医"),
  ("chronic","/ˈkrɒnɪk/","adj.","慢性的","It turned out to be chronic.","结果是慢性的。","就医"),
  ("acute","/əˈkjuːt/","adj.","急性的；严重的","It could be an acute infection.","可能是急性感染。","就医"),
  ("anxiety","/æŋˈzaɪəti/","n.","焦虑","He suffers from anxiety.","他患有焦虑症。","健康"),
  ("nutrition","/njuˈtrɪʃn/","n.","营养","Balanced nutrition is important.","均衡营养很重要。","健康"),
  ("exercise","/ˈeksəsaɪz/","n./v.","锻炼；练习","Regular exercise reduces stress.","规律锻炼减轻压力。","健康"),
  ("diet","/ˈdaɪət/","n.","饮食","A balanced diet boosts energy.","均衡饮食提升精力。","健康"),
  ("insomnia","/ɪnˈsɒmniə/","n.","失眠","She suffers from insomnia.","她受失眠困扰。","健康"),
 ]),
 ("交通与出行", [
  ("boarding pass","/ˈbɔːdɪŋ pɑːs/","n.","登机牌","Please show your boarding pass.","请出示登机牌。","交通"),
  ("itinerary","/aɪˈtɪnərəri/","n.","行程","Send me your itinerary.","把你的行程发我。","交通"),
  ("platform","/ˈplætfɔːm/","n.","站台","The train departs from platform six.","列车从六号站台发车。","交通"),
  ("transfer","/trænsˈfɜː/","v.","转乘","You need a transfer at the next stop.","你需在下一站换乘。","交通"),
  ("terminal","/ˈtɜːmɪnl/","n.","航站楼；终点站","Your terminal is three.","你的航站楼在三号。","交通"),
  ("delay","/dɪˈleɪ/","n./v.","延误","There was a two-hour delay.","延误了两小时。","交通"),
  ("departure","/dɪˈpɑːtʃə/","n.","出发","Check the departure gate.","查看登机口。","交通"),
  ("arrival","/əˈraɪvl/","n.","到达","The arrival time is 6 pm.","到达时间是下午六点。","交通"),
  ("reservation","/ˌrezəˈveɪʃn/","n.","预订","I have a reservation under Lee.","我用李的名字订了位。","交通"),
  ("one-way","/wʌn weɪ/","adj.","单程的","I'd like a one-way ticket.","我想要一张单程票。","交通"),
  ("round-trip","/raʊnd trɪp/","adj.","往返的","A round-trip ticket is cheaper.","往返票更便宜。","交通"),
  ("rush hour","/rʌʃ aʊə/","n.","高峰期","Avoid travelling at rush hour.","避免在高峰期出行。","交通"),
  ("commute","/kəˈmjuːt/","n./v.","通勤","My commute takes 40 minutes.","我通勤需 40 分钟。","交通"),
  ("traffic","/ˈtræfɪk/","n.","交通（拥堵）","Traffic is terrible at eight.","八点交通糟透了。","交通"),
  ("subway","/ˈsʌbweɪ/","n.","地铁","Take the subway; it's faster.","坐地铁更快。","交通"),
  ("fare","/feə/","n.","车费","What's the bus fare?","公交车费多少？","交通"),
  ("schedule","/ˈʃedjuːl/","n.","时刻表","According to the schedule…","根据时刻表……","交通"),
 ]),
 ("购物与消费", [
  ("receipt","/rɪˈsiːt/","n.","收据","Can I have the receipt?","能给我收据吗？","购物"),
  ("refund","/ˈriːfʌnd/","n./v.","退款","They offered a full refund.","他们提供全额退款。","购物"),
  ("exchange","/ɪksˈtʃeɪndʒ/","v.","交换；换货","Can I exchange this shirt?","我能换这件衬衫吗？","购物"),
  ("discount","/ˈdɪskaʊnt/","n.","折扣","Is there a student discount?","有学生折扣吗？","购物"),
  ("warranty","/ˈwɒrənti/","n.","保修","It comes with a two-year warranty.","它有两年保修。","购物"),
  ("receipt","/rɪˈsiːt/","n.","收据","Keep your receipts for returns.","退货请保留收据。","购物"),
  ("cash","/kæʃ/","n.","现金","Do you take cash?","你们收现金吗？","购物"),
  ("debit card","/ˈdebɪt kɑːd/","n.","借记卡","I'll pay by debit card.","我用借记卡付。","购物"),
  ("queue","/kjuː/","n./v.","队列；排队","There was a long queue.","队伍很长。","购物"),
  ("trolley","/ˈtrɒli/","n.","购物车","I need a trolley.","我需要一辆购物车。","购物"),
  ("checkout","/ˈtʃekaʊt/","n.","收银台","The checkout is over there.","收银台在那边。","购物"),
  ("bargain","/ˈbɑːɡɪn/","n.","便宜货","It's a real bargain.","真是划算的便宜货。","购物"),
  ("expensive","/ɪkˈspensɪv/","adj.","贵的","It's too expensive for me.","对我来说太贵了。","购物"),
  ("affordable","/əˈfɔːdəbl/","adj.","负担得起的","We need affordable housing.","我们需要负担得起的住房。","购物"),
  ("guarantee","/ˌɡærənˈtiː/","n./v.","保修；保证","The phone has a one-year guarantee.","手机有一年保修。","购物"),
  ("size","/saɪz/","n.","尺码","Do you have this in a larger size?","这个有大一号的吗？","购物"),
 ]),
 ("社交与沟通", [
  ("apologize","/əˈpɒlədʒaɪz/","v.","道歉","He apologized for being late.","他为迟到道歉。","社交"),
  ("appreciate","/əˈpriːʃieɪt/","v.","感激","I really appreciate your help.","我非常感激你的帮助。","社交"),
  ("blame","/bleɪm/","v./n.","责备","Don't blame yourself.","不要责怪自己。","社交"),
  ("complain","/kəmˈpleɪn/","v.","抱怨","He complained about the noise.","他抱怨噪音。","社交"),
  ("criticize","/ˈkrɪtɪsaɪz/","v.","批评","She criticized the proposal.","她批评了这个提案。","社交"),
  ("confess","/kənˈfes/","v.","承认；坦白","He confessed his mistake.","他承认了错误。","社交"),
  ("conversation","/ˌkɒnvəˈseɪʃn/","n.","交谈","We had a long conversation.","我们长谈了。","社交"),
  ("gossip","/ˈɡɒsɪp/","n./v.","八卦","I don't like office gossip.","我不喜欢办公室八卦。","社交"),
  ("honest","/ˈɒnɪst/","adj.","诚实的","To be honest, I disagree.","老实说，我不同意。","社交"),
  ("interrupt","/ˌɪntəˈrʌpt/","v.","打断","Sorry to interrupt you.","抱歉打断你。","社交"),
  ("misunderstand","/ˌmɪsʌndəˈstænd/","v.","误解","I think I misunderstood.","我想我误解了。","社交"),
  ("opinion","/əˈpɪnjən/","n.","看法","In my opinion, it's fine.","在我看来没问题。","社交"),
  ("polite","/pəˈlaɪt/","adj.","礼貌的","He was always polite to staff.","他对员工总是很礼貌。","社交"),
  ("apologise","/əˈpɒlədʒaɪz/","v.","道歉（英式）","She apologised for the delay.","她为延误道歉。","社交"),
  ("grateful","/ˈɡreɪtfl/","adj.","感激的","I'm really grateful for your help.","我真的很感激你的帮助。","社交"),
  ("conflict","/ˈkɒnflɪkt/","n.","冲突","The conflict was resolved calmly.","冲突被冷静解决。","社交"),
  ("rumour","/ˈruːmə/","n.","谣言","Don't spread rumours.","不要传播谣言。","社交"),
  ("greeting","/ˈɡriːtɪŋ/","n.","问候","Send him my greetings.","代我向他问好。","社交"),
  ("hesitate","/ˈhezɪteɪt/","v.","犹豫","Don't hesitate to ask.","有问题尽管问。","社交"),
  ("interrupt politely","/ˌɪntəˈrʌpt pəˈlaɪtli/","phr.","礼貌打断","She interrupted politely.","她礼貌地打断。","社交"),
 ]),
 ("求职与职场", [
  ("application","/ˌæplɪˈkeɪʃn/","n.","申请","I submitted my application yesterday.","我昨天提交了申请。","求职"),
  ("appointment","/əˈpɔɪntmənt/","n.","面试；约会","I have an appointment on Monday.","我周一有个面试。","求职"),
  ("career","/kəˈrɪə/","n.","职业生涯","She's building a career in design.","她在设计领域发展事业。","求职"),
  ("colleague","/ˈkɒliːɡ/","n.","同事","My colleagues are supportive.","我的同事很支持。","职场"),
  ("contract","/ˈkɒntrækt/","n.","合同","Please read the contract carefully.","请仔细阅读合同。","职场"),
  ("deadline","/ˈdedlaɪn/","n.","截止日期","The deadline is this Friday.","截止日期是本周五。","职场"),
  ("department","/dɪˈpɑːtment/","n.","部门","He works in the marketing department.","他在市场部工作。","职场"),
  ("experience","/ɪkˈspɪəriəns/","n.","经验；经历","Do you have relevant experience?","你有相关经验吗？","求职"),
  ("flexible","/ˈfleksəbl/","adj.","灵活的","My hours are flexible.","我的时间灵活。","职场"),
  ("interview","/ˈɪntəvjuː/","n.","面试","Thanks for coming to the interview.","感谢来参加面试。","求职"),
  ("overtime","/ˈəʊvətaɪm/","n.","加班","I've been working overtime.","我一直在加班。","职场"),
  ("probation","/prəˈbeɪʃn/","n.","试用期","The probation lasts three months.","试用期为三个月。","职场"),
  ("qualification","/ˌkwɒlɪfɪˈkeɪʃn/","n.","资历；资格","What qualifications do you have?","你有什么资历？","求职"),
  ("reference","/ˈrefrəns/","n.","推荐信；推荐人","Could I have a reference?","能给我一封推荐信吗？","求职"),
  ("resign","/rɪˈzaɪn/","v.","辞职","He resigned last Friday.","他上周五辞职了。","职场"),
  ("salary","/ˈsæləri/","n.","薪水","The salary is negotiable.","薪水可面议。","求职"),
  ("shift","/ʃɪft/","n.","轮班","I work the night shift this week.","我这周上夜班。","职场"),
  ("supervisor","/ˈsuːpəvaɪzə/","n.","主管","Speak to your supervisor.","和你的主管谈谈。","职场"),
  ("teamwork","/ˈtiːmwɜːk/","n.","团队合作","The role requires teamwork.","该职位需要团队合作。","职场"),
  ("promotion","/prəˈməʊʃn/","n.","晋升","She got a promotion last year.","她去年升职了。","职场"),
 ]),
]

BOOKS = [
    {"key": "cet6", "name": "大学英语六级 CET-6", "stage": "四六级", "mod": "cet6",
     "note": "六级核心约 6000 词，难点不在词量而在「一词多义与熟词僻义」。本词书按：抽象高频词 / 翻译与写作高级词 / 听力新闻讲座词 / 固定搭配 四块编排，例句取自真题风格。",
     "groups": CET6},
    {"key": "tem8", "name": "大学英语八级 TEM-8", "stage": "四六级", "mod": "tem8",
     "note": "TEM-8 考英美语言文学与翻译，词汇量小但深度要求高。本词书聚焦英美文学词汇与翻译高分词，适合英美文学方向与高阶翻译备考。",
     "groups": TEM8},
    {"key": "ielts", "name": "雅思 IELTS", "stage": "出国考", "mod": "ielts",
     "note": "雅思无官方大纲词表，按四个单项分块：阅读同义替换 / 写作 Task 1 图表 / 写作 Task 2 论证 / 口语与听力场景。每块均配该单项高频词与地道表达。",
     "groups": IELTS},
    {"key": "toefl", "name": "托福 TOEFL iBT", "stage": "出国考", "mod": "toefl",
     "note": "托福材料来自固定本科学科池，认学科比认生词管用。本词书按：学术通用词 / 自然科学 / 人文社科 / 讲座信号词与口语 四块编排。",
     "groups": TOEFL},
    {"key": "oral", "name": "出国生活流水英语", "stage": "出国考", "mod": "oral",
     "note": "以「到国外真能用」为目标，覆盖租房、银行支付、就医健康、交通出行、购物消费、社交沟通、求职职场七大生活场景的实用高频词与句型。",
     "groups": ORAL},
]


def build():
    out = {}
    for bk in BOOKS:
        books = []
        total = 0
        for gi, (gname, words) in enumerate(bk["groups"], 1):
            ws = []
            for wi, w in enumerate(words, 1):
                word, phonetic, pos, meaning, sent, sentcn, tag = w
                ws.append({
                    "id": "%s-g%d-w%d" % (bk["key"], gi, wi),
                    "word": word,
                    "phonetic": phonetic,
                    "pos": pos,
                    "meaning": meaning,
                    "tag": tag,
                    "freq": "high",
                    "sentence": sent,
                    "sentenceCn": sentcn,
                    "audio": "",
                })
            total += len(ws)
            books.append({"id": "%s-g%d" % (bk["key"], gi), "title": gname, "words": ws})
        out[bk["key"]] = {
            "product": "%s · 词汇记忆" % bk["name"],
            "version": "1.0",
            "schema_version": "1.0",
            "note": bk["note"] + " 内容由 AI 整理，待人工校对。",
            "level": bk["key"],
            "stage": bk["stage"],
            "mod": bk["mod"],
            "books": [{"id": bk["key"], "title": bk["name"], "units": books}],
        }
        print("%-8s %-22s %2d 组 %4d 词" % (bk["key"], bk["name"], len(bk["groups"]), total))
    return out


def main():
    out = build()
    print()
    for key, data in out.items():
        p = os.path.join(DATA, "vocab_%s.json" % key)
        with io.open(p, "w", encoding="utf-8") as f:
            f.write(json.dumps(data, ensure_ascii=False, indent=1))
        with io.open(p, encoding="utf-8") as f:
            d = json.load(f)
        units = d["books"][0]["units"]
        n = sum(len(u["words"]) for u in units)
        ids = [w["id"] for u in units for w in u["words"]]
        noex = [w["word"] for u in units for w in u["words"] if not w["sentence"]]
        noph = [w["word"] for u in units for w in u["words"] if not w["phonetic"]]
        print("  -> vocab_%s.json (%.0f KB)  词 %d  缺例句 %d  缺音标 %d  id 唯一 %s"
              % (key, os.path.getsize(p) / 1024.0, n, len(noex), len(noph),
                 "是" if len(set(ids)) == len(ids) else "否"))
        if noex: print("     缺例句: %s" % noex[:5])
        if noph: print("     缺音标: %s" % noph[:5])


if __name__ == "__main__":
    main()
