# -*- coding: utf-8 -*-
"""生成高中英语课本章节同步训练数据（人教版 2019 版·必修+选择性必修）。

产出: data/senior_textbook.json
结构对齐 junior_textbook.json:
  books[].units[] = { id, title, topic, words[], grammars[], questions[] }
  word = { word, phonetic, pos, meaning, audio, sentence, sentenceCn }
  grammar = { point, example, exampleCn }
  question = { stem, options[], answer(int), analysis }

内容策略:
  - 必修第一册(b1): Welcome Unit + Unit1~5 共 6 单元全部充实
  - 必修二/三、选必一~四(b2,b3,x1,x2,x3,x4): 仅首单元(Unit1)充实
  - 其余单元仅留 title+topic，words/grammars/questions 为空 -> 前端显示"整理中"
"""
import json, os

AUDIO = "/audio/sw/{}.mp3"  # 高中词汇音频约定路径（暂无则优雅降级）

def w(word, phonetic, pos, meaning, sentence="", sentenceCn=""):
    return {
        "word": word, "phonetic": phonetic, "pos": pos, "meaning": meaning,
        "audio": AUDIO.format(word.lower()), "sentence": sentence, "sentenceCn": sentenceCn,
    }

def g(point, example, exampleCn):
    return {"point": point, "example": example, "exampleCn": exampleCn}

def q(stem, options, answer, analysis):
    return {"stem": stem, "options": options, "answer": answer, "analysis": analysis}

# ===================== 必修第一册 b1 =====================
b1_welcome = {
    "id": "b1w", "title": "Welcome Unit", "topic": "高中生活启航 · 基础交际与校园词汇",
    "words": [
        w("freshman", "ˈfreʃmən", "n.", "（中学或大学的）一年级新生",
          "As a freshman, he felt both excited and nervous.", "作为高一新生，他既兴奋又紧张。"),
        w("campus", "ˈkæmpəs", "n.", "校园；校区",
          "The campus is beautiful in autumn.", "秋天的校园很美。"),
        w("challenge", "ˈtʃælɪndʒ", "n./v.", "挑战；向…挑战",
          "Learning a new language is a real challenge.", "学习一门新语言是真正的挑战。"),
        w("confident", "ˈkɒnfɪdənt", "adj.", "自信的；有把握的",
          "She is confident about the coming exam.", "她对即将到来的考试很有信心。"),
        w("concentrate", "ˈkɒnsntreɪt", "v.", "集中（注意力）；专注",
          "Please concentrate on your homework.", "请专心做作业。"),
        w("lecture", "ˈlektʃə(r)", "n.", "讲座；讲课",
          "We attended a lecture on science.", "我们听了一场关于科学的讲座。"),
        w("register", "ˈredʒɪstə(r)", "v.", "登记；注册",
          "You must register for the new course.", "你必须注册这门新课。"),
        w("volunteer", "ˌvɒlənˈtɪə(r)", "n./v.", "志愿者；做志愿工作",
          "He volunteers at the local library.", "他在当地图书馆做志愿工作。"),
        w("goal", "ɡəʊl", "n.", "目标；球门",
          "My goal is to study abroad.", "我的目标是出国留学。"),
        w("independent", "ˌɪndɪˈpendənt", "adj.", "独立的；自主的",
          "University life makes students more independent.", "大学生活让学生更独立。"),
        w("responsible", "rɪˈspɒnsəbl", "adj.", "有责任的；可靠的",
          "We should be responsible for our own study.", "我们应该对自己的学习负责。"),
        w("explore", "ɪkˈsplɔː(r)", "v.", "探索；探究",
          "Let's explore different clubs.", "我们来了解一下不同的社团吧。"),
    ],
    "grammars": [
        g("用情态动词 can / should / must 表达能力与建议：can 表能力，should 表建议，must 表必须。",
          "You should join a club to make friends.", "你应该加入一个社团来交朋友。"),
        g("祈使句用于提出请求或建议，常以动词原形开头；否定式在句首加 Don't。",
          "Don't be late for the first class.", "第一节课不要迟到。"),
    ],
    "questions": [
        q("新学期你鼓励同学加入社团，最恰当的建议是：___",
          ["You should join a club.", "You must sleep all day.", "Don't go to school."], 0,
          "should 用于给出建议，加入社团是积极建议。"),
        q("\"大一新生\" 对应的英文是：___", ["freshman", "teacher", "worker"], 0,
          "freshman 指中学或大学一年级新生。"),
        q("— Can you concentrate on the lecture? — ___, it is very interesting.",
          ["Yes, I can", "No, I must", "Don't"], 0,
          "can 提问用 can 回答，表示能做到。"),
        q("We should be ___ for our own learning.", ["responsible", "responsibility", "respond"], 0,
          "be 动词后接形容词 responsible（有责任的）。"),
        q("He ___ at the school library every weekend.", ["volunteers", "volunteer", "volunteering"], 0,
          "主语 he 为第三人称单数，动词加 -s。"),
        q("___ late for the meeting.", ["Don't be", "Not be", "Be not"], 0,
          "祈使句否定式以 Don't 开头。"),
    ],
}

b1u1 = {
    "id": "b101", "title": "Unit 1 Teenage Life", "topic": "青少年生活 · 学习与社团",
    "words": [
        w("teenager", "ˈtiːneɪdʒə(r)", "n.", "青少年（13–19 岁）",
          "Many teenagers like playing sports.", "许多青少年喜欢运动。"),
        w("prefer", "prɪˈfɜː(r)", "v.", "更喜欢；宁愿",
          "I prefer reading to watching TV.", "比起看电视，我更喜欢阅读。"),
        w("suitable", "ˈsuːtəbl", "adj.", "合适的；适宜的",
          "This club is suitable for beginners.", "这个社团适合初学者。"),
        w("pressure", "ˈpreʃə(r)", "n.", "压力",
          "Students often face study pressure.", "学生常面临学习压力。"),
        w("debate", "dɪˈbeɪt", "n./v.", "辩论；讨论",
          "We had a debate about school rules.", "我们就校规进行了一场辩论。"),
        w("attend", "əˈtend", "v.", "参加；出席",
          "She will attend the music club.", "她将参加音乐社团。"),
        w("extra", "ˈekstrə", "adj.", "额外的；额外的",
          "He needs extra practice.", "他需要额外的练习。"),
        w("quit", "kwɪt", "v.", "停止；放弃；离开",
          "He quit the team last month.", "他上个月退出了团队。"),
        w("survive", "səˈvaɪv", "v.", "幸存；挺过",
          "We must learn to survive stress.", "我们必须学会扛过压力。"),
        w("generation", "ˌdʒenəˈreɪʃn", "n.", "一代（人）；世代",
          "There is a gap between two generations.", "两代人之间存在代沟。"),
        w("actually", "ˈæktʃuəli", "adv.", "实际上；事实上",
          "Actually, it is not difficult.", "实际上，这并不难。"),
        w("obviously", "ˈɒbviəsli", "adv.", "显然；明显地",
          "Obviously, he needs help.", "显然，他需要帮助。"),
    ],
    "grammars": [
        g("宾语从句：由 that / whether / what 等引导，作动词的宾语；that 常可省略。",
          "I think (that) this club is fun.", "我认为这个社团很有趣。"),
        g("一般现在时与一般过去时：描述常态用一般现在时，描述过去动作用一般过去时。",
          "He joins the club. / He joined it last year.", "他加入社团。/ 他去年加入的。"),
    ],
    "questions": [
        q("I ___ reading books to playing games.", ["prefer", "prefers", "preferring"], 0,
          "主语 I 后用动词原形 prefer。"),
        q("This activity is ___ for new students.", ["suitable", "suit", "suited"], 0,
          "be suitable for 为固定搭配，意为\"适合…\"。"),
        q("— Do you think ___ we should join the team? — Yes.",
          ["that", "what", "who"], 0,
          "think 后接 that 引导的宾语从句，that 可省略。"),
        q("Teenagers often feel ___ from exams.", ["pressure", "press", "pressed"], 0,
          "feel 后接名词 pressure（压力）。"),
        q("He ___ the club because he was too busy.", ["quit", "quits", "quitting"], 0,
          "由 was 可知用一般过去时 quit（quit 过去式同形）。"),
        q("___, the homework is not so hard.", ["Actually", "Act", "Active"], 0,
          "actually 作状语，意为\"实际上\"。"),
    ],
}
b1u2 = {
    "id": "b102", "title": "Unit 2 Travelling Around", "topic": "旅行计划 · 交通与预订",
    "words": [
        w("journey", "ˈdʒɜːni", "n.", "旅行；旅程",
          "We had a long journey by train.", "我们乘火车进行了一次长途旅行。"),
        w("transport", "trænˈspɔːt", "n./v.", "交通；运输",
          "Public transport is convenient.", "公共交通很方便。"),
        w("destination", "ˌdestɪˈneɪʃn", "n.", "目的地；终点",
          "Paris is our destination.", "巴黎是我们的目的地。"),
        w("brochure", "brəʊˈʃʊə(r)", "n.", "小册子；指南",
          "Take a travel brochure with you.", "带一本旅行指南吧。"),
        w("rent", "rent", "v.", "租用；出租",
          "We can rent a car there.", "我们可以在那儿租一辆车。"),
        w("hike", "haɪk", "v./n.", "徒步旅行；远足",
          "They hiked in the mountains.", "他们在山里徒步。"),
        w("credit", "ˈkredɪt", "n.", "信用；赊账；学分",
          "I paid by credit card.", "我用信用卡付款。"),
        w("contact", "ˈkɒntækt", "v./n.", "联系；联络",
          "Please contact us by email.", "请通过邮件联系我们。"),
        w("budget", "ˈbʌdʒɪt", "n.", "预算",
          "We should plan a travel budget.", "我们应该规划旅行预算。"),
        w("flight", "flaɪt", "n.", "航班；飞行",
          "The flight was delayed.", "航班延误了。"),
        w("luggage", "ˈlʌɡɪdʒ", "n.", "行李",
          "Check your luggage at the counter.", "在柜台托运你的行李。"),
        w("accommodation", "əˌkɒməˈdeɪʃn", "n.", "住宿；膳宿",
          "The hotel offers good accommodation.", "这家酒店住宿条件很好。"),
    ],
    "grammars": [
        g("将来时态：be going to 表计划，will 表意愿或预测，现在进行时表已确定的近期安排。",
          "I am going to visit Beijing.", "我打算去北京游玩。"),
        g("疑问词引导的宾语从句：what / where / how 等疑问词可引导宾语从句。",
          "Could you tell me where the station is?", "你能告诉我车站在哪儿吗？"),
    ],
    "questions": [
        q("We are ___ to take a trip next week.", ["going", "go", "went"], 0,
          "be going to 表计划中的将来。"),
        q("Could you tell me ___ the museum is?", ["where", "that", "what"], 0,
          "where 引导宾语从句，询问地点。"),
        q("We can ___ a car at the airport.", ["rent", "rents", "renting"], 0,
          "can 后接动词原形 rent。"),
        q("The train ___ was cancelled because of the storm.", ["journey", "journeys", "journeying"], 0,
          "train journey 意为\"火车旅程\"，用名词原形。"),
        q("Don't forget to pack your ___.", ["luggage", "lug", "lugged"], 0,
          "luggage 为不可数行李。"),
        q("I paid for the ticket by ___ card.", ["credit", "credits", "crediting"], 0,
          "credit card 信用卡。"),
    ],
}
b1u3 = {
    "id": "b103", "title": "Unit 3 Sports and Fitness", "topic": "运动与健康",
    "words": [
        w("fitness", "ˈfɪtnəs", "n.", "健康；健壮",
          "Daily exercise improves fitness.", "每天锻炼增强体质。"),
        w("sweat", "swet", "n./v.", "汗；出汗",
          "He was covered in sweat.", "他满身是汗。"),
        w("marathon", "ˈmærəθən", "n.", "马拉松赛跑",
          "She finished the marathon.", "她跑完了马拉松。"),
        w("compete", "kəmˈpiːt", "v.", "竞争；比赛",
          "They compete in the match.", "他们在比赛中竞争。"),
        w("cheer", "tʃɪə(r)", "v.", "欢呼；加油",
          "Fans cheered for the team.", "球迷为球队欢呼。"),
        w("jog", "dʒɒɡ", "v.", "慢跑",
          "I jog in the park every morning.", "我每天早晨在公园慢跑。"),
        w("athletic", "æθˈletɪk", "adj.", "运动的；运动员的",
          "He has an athletic build.", "他体格健壮。"),
        w("injury", "ˈɪndʒəri", "n.", "伤害；损伤",
          "He suffered a knee injury.", "他膝盖受了伤。"),
        w("strengthen", "ˈstreŋθn", "v.", "加强；增强",
          "Yoga can strengthen your body.", "瑜伽能增强体质。"),
        w("workout", "ˈwɜːkaʊt", "n.", "锻炼；训练",
          "A daily workout keeps you fit.", "每天锻炼让你保持健康。"),
        w("diet", "ˈdaɪət", "n.", "日常饮食；节食",
          "A balanced diet is important.", "均衡饮食很重要。"),
        w("determination", "dɪˌtɜːmɪˈneɪʃn", "n.", "决心；决定",
          "She won with great determination.", "她凭着极大的决心获胜。"),
    ],
    "grammars": [
        g("现在完成时：have/has + 过去分词，表示过去发生并持续到现在的动作或影响。",
          "He has trained for two years.", "他已经训练两年了。"),
        g("形容词、副词的比较级与最高级：单音节加 -er/-est，多音节用 more/most。",
          "Running is healthier than sitting.", "跑步比久坐更健康。"),
    ],
    "questions": [
        q("He has ___ every morning this month.", ["jogged", "jog", "jogs"], 0,
          "has + 过去分词 jogged 构成现在完成时。"),
        q("Cycling is ___ than driving for short trips.", ["healthier", "healthy", "healthiest"], 0,
          "than 提示用比较级 healthier。"),
        q("The players ___ for their team loudly.", ["cheered", "cheer", "cheering"], 0,
          "描述已发生的比赛用一般过去时 cheered。"),
        q("You should keep a balanced ___ to stay fit.", ["diet", "die", "dieting"], 0,
          "balanced diet 均衡饮食。"),
        q("She showed great ___ to finish the race.", ["determination", "determine", "determined"], 0,
          "great 后接名词 determination（决心）。"),
        q("To ___ your body, try swimming twice a week.",
          ["strengthen", "strength", "strong"], 0,
          "不定式 to 后接动词原形 strengthen（增强）。"),
    ],
}
b1u4 = {
    "id": "b104", "title": "Unit 4 Natural Disasters", "topic": "自然灾害 · 应急与报道",
    "words": [
        w("disaster", "dɪˈzɑːstə(r)", "n.", "灾难；灾害",
          "The earthquake was a terrible disaster.", "那场地震是可怕的灾难。"),
        w("earthquake", "ˈɜːθkweɪk", "n.", "地震",
          "The earthquake destroyed many houses.", "地震摧毁了许多房屋。"),
        w("flood", "flʌd", "n./v.", "洪水；淹没",
          "The flood washed away the bridge.", "洪水冲走了桥梁。"),
        w("hurricane", "ˈhʌrɪkən", "n.", "飓风",
          "A hurricane hit the coast.", "飓风袭击了海岸。"),
        w("shelter", "ˈʃeltə(r)", "n.", "避难处；庇护",
          "They found shelter in a school.", "他们在学校找到了避难所。"),
        w("rescue", "ˈreskjuː", "v./n.", "营救；救援",
          "Soldiers rescued the survivors.", "士兵营救了幸存者。"),
        w("damage", "ˈdæmɪdʒ", "n./v.", "损害；毁坏",
          "The storm damaged the crops.", "暴风雨毁坏了庄稼。"),
        w("destroy", "dɪˈstrɔɪ", "v.", "摧毁；毁灭",
          "The fire destroyed the building.", "大火烧毁了大楼。"),
        w("survivor", "səˈvaɪvə(r)", "n.", "幸存者",
          "The survivors were sent to hospital.", "幸存者被送医。"),
        w("buried", "ˈberid", "adj./v.", "被掩埋的（bury 的过去分词）",
          "Many houses were buried by the mud.", "许多房屋被泥石流掩埋。"),
        w("effort", "ˈefət", "n.", "努力；尽力",
          "We should make an effort to help.", "我们应尽力相助。"),
        w("supply", "səˈplaɪ", "n./v.", "供应；供给",
          "Food supplies were sent to the area.", "食物补给被送往该地区。"),
    ],
    "grammars": [
        g("一般过去时被动语态：was/were + 过去分词，强调动作的承受者。",
          "The bridge was destroyed by the flood.", "桥被洪水冲毁了。"),
        g("定语从句：that / which 指物，who 指人，在从句中作主语或宾语。",
          "The soldiers who helped us were brave.", "帮助我们的士兵很勇敢。"),
    ],
    "questions": [
        q("The old house ___ by the earthquake last night.", ["was destroyed", "destroyed", "destroys"], 0,
          "last night 用一般过去时；house 作主语用被动 was destroyed。"),
        q("The man ___ saved the child was a firefighter.", ["who", "which", "what"], 0,
          "先行词 man 指人，用 who 引导定语从句。"),
        q("After the flood, food ___ were sent to the village.", ["supplies", "supply", "supplying"], 0,
          "food supplies 意为\"食物补给\"，用复数。"),
        q("The rescue team made every ___ to find survivors.", ["effort", "efforts", "effect"], 0,
          "make an effort / make every effort 努力。"),
        q("Many people lost their homes in the ___.", ["disaster", "disastrous", "destroy"], 0,
          "in the disaster 在灾难中。"),
        q("They found ___ in a nearby school.", ["shelter", "sheltered", "sheltering"], 0,
          "find shelter 找到避难处。"),
    ],
}
b1u5 = {
    "id": "b105", "title": "Unit 5 Languages Around the World", "topic": "世界语言 · 文化与沟通",
    "words": [
        w("command", "kəˈmɑːnd", "n./v.", "掌握；命令",
          "He has a good command of English.", "他英语掌握得很好。"),
        w("request", "rɪˈkwest", "n./v.", "请求；要求",
          "She made a polite request.", "她提出了一个礼貌的请求。"),
        w("communicate", "kəˈmjuːnɪkeɪt", "v.", "交流；沟通",
          "We communicate by email.", "我们通过邮件沟通。"),
        w("variety", "vəˈraɪəti", "n.", "多样；种类",
          "English has a variety of accents.", "英语有各种各样的口音。"),
        w("unique", "juˈniːk", "adj.", "独特的；唯一的",
          "Each language is unique.", "每种语言都是独特的。"),
        w("civilization", "ˌsɪvəlaɪˈzeɪʃn", "n.", "文明",
          "Language carries civilization.", "语言承载文明。"),
        w("barrier", "ˈbæriə(r)", "n.", "障碍；屏障",
          "Language can be a barrier.", "语言可能成为障碍。"),
        w("fluent", "ˈfluːənt", "adj.", "流利的；流畅的",
          "She is fluent in French.", "她法语很流利。"),
        w("accent", "ˈæksent", "n.", "口音；重音",
          "He speaks with a British accent.", "他说话带英国口音。"),
        w("dialect", "ˈdaɪəlekt", "n.", "方言",
          "People there speak a local dialect.", "那里的人说当地方言。"),
        w("transmit", "trænzˈmɪt", "v.", "传播；传递",
          "Stories transmit culture.", "故事传播文化。"),
        w("trend", "trend", "n.", "趋势；倾向",
          "English is a global trend.", "英语是一种全球趋势。"),
    ],
    "grammars": [
        g("现在分词作定语或状语：表示主动、进行，如 speaking English（说英语的）。",
          "The boy speaking English is my cousin.", "那个说英语的男孩是我表弟。"),
        g("主谓一致：集合名词或单数主语用单数动词，并列主语用复数。",
          "English is useful. / Tom and Jerry are friends.", "英语很有用。/ 汤姆和杰瑞是朋友。"),
    ],
    "questions": [
        q("The girl ___ French fluently is from Paris.", ["speaking", "spoken", "speak"], 0,
          "现在分词 speaking 作定语，表主动。"),
        q("He has a good ___ of three languages.", ["command", "commanded", "commanding"], 0,
          "have a good command of 熟练掌握。"),
        q("English, Chinese and Arabic ___ widely used.", ["are", "is", "was"], 0,
          "三个并列主语用复数 are。"),
        q("A strong accent can be a communication ___.", ["barrier", "barriers", "barring"], 0,
          "barrier 障碍。"),
        q("She is ___ in both English and Japanese.", ["fluent", "fluency", "fluid"], 0,
          "be fluent in 在…方面流利。"),
        q("Each culture is ___ and worth respecting.", ["unique", "uniquely", "union"], 0,
          "unique 独特的，作表语。"),
    ],
}

# ===================== 其余各册首单元 =====================
b2u1 = {
    "id": "b201", "title": "Unit 1 Cultural Heritage", "topic": "文化遗产 · 保护与交流",
    "words": [
        w("heritage", "ˈherɪtɪdʒ", "n.", "遗产（文化、历史）",
          "The Great Wall is a world heritage.", "长城是世界遗产。"),
        w("preserve", "prɪˈzɜːv", "v.", "保护；保存",
          "We must preserve old buildings.", "我们必须保护老建筑。"),
        w("promote", "prəˈməʊt", "v.", "促进；推广",
          "The event promotes culture.", "该活动推广文化。"),
        w("balance", "ˈbæləns", "n./v.", "平衡；权衡",
          "We need a balance between work and rest.", "我们需要工作与休息的平衡。"),
        w("committee", "kəˈmɪti", "n.", "委员会",
          "A committee was set up.", "成立了一个委员会。"),
        w("worthy", "ˈwɜːði", "adj.", "值得的；有价值的",
          "The site is worthy of protection.", "该遗址值得保护。"),
        w("recommend", "ˌrekəˈmend", "v.", "推荐；建议",
          "I recommend this museum.", "我推荐这家博物馆。"),
        w("contribute", "kənˈtrɪbjuːt", "v.", "贡献；捐献",
          "Tourists contribute to the local economy.", "游客为当地经济做贡献。"),
        w("prevent", "prɪˈvent", "v.", "阻止；防止",
          "We should prevent damage.", "我们应防止破坏。"),
        w("establish", "ɪˈstæblɪʃ", "v.", "建立；设立",
          "They established a fund.", "他们设立了一个基金。"),
    ],
    "grammars": [
        g("介词 + which / whom 引导的定语从句：表物用 which，表人用 whom。",
          "The temple in which they prayed is old.", "他们祈祷的那座庙很古老。"),
        g("被动语态：be + 过去分词，强调承受者或动作本身。",
          "The site was protected by law.", "该遗址受法律保护。"),
    ],
    "questions": [
        q("We must ___ our cultural heritage for the future.", ["preserve", "preserves", "preserving"], 0,
          "must 后接动词原形 preserve。"),
        q("The museum ___ in 1950 is famous.", ["established", "establishes", "establishing"], 0,
          "过去分词 established 作定语，表被动完成。"),
        q("This place is ___ of a visit.", ["worthy", "worth", "worship"], 0,
          "worthy of 值得…。"),
        q("I ___ the local food to every visitor.", ["recommend", "recommends", "recommending"], 0,
          "主语 I 后用动词原形 recommend。"),
        q("Tourists ___ a lot to the economy.", ["contribute", "contributes", "contributing"], 0,
          "复数主语用动词原形 contribute。"),
        q("The old bridge was ___ by the flood.", ["destroyed", "destroy", "destroying"], 0,
          "被动语态 was destroyed。"),
    ],
}
b3u1 = {
    "id": "b301", "title": "Unit 1 Festivals and Celebrations", "topic": "节日与庆典",
    "words": [
        w("festival", "ˈfestɪvl", "n.", "节日；节庆",
          "The Spring Festival is important.", "春节很重要。"),
        w("celebrate", "ˈselɪbreɪt", "v.", "庆祝；庆贺",
          "We celebrate it with a big meal.", "我们吃大餐庆祝。"),
        w("gather", "ˈɡæðə(r)", "v.", "聚集；集合",
          "Families gather at festivals.", "节日里家人团聚。"),
        w("decorate", "ˈdekəreɪt", "v.", "装饰；布置",
          "They decorate the house with lights.", "他们用彩灯装饰房子。"),
        w("feast", "fiːst", "n.", "盛宴；宴会",
          "We had a feast at night.", "我们晚上吃了一顿盛宴。"),
        w("gratitude", "ˈɡrætɪtjuːd", "n.", "感激；感恩",
          "We show gratitude to guests.", "我们向客人表达感激。"),
        w("origin", "ˈɒrɪdʒɪn", "n.", "起源；起因",
          "What is the origin of this festival?", "这个节日的起源是什么？"),
        w("custom", "ˈkʌstəm", "n.", "习俗；习惯",
          "It is a local custom.", "这是当地习俗。"),
        w("harvest", "ˈhɑːvɪst", "n./v.", "收获；收割",
          "The harvest festival thanks the land.", "丰收节感谢大地。"),
        w("lantern", "ˈlæntən", "n.", "灯笼；提灯",
          "Children carry lanterns.", "孩子们提着灯笼。"),
    ],
    "grammars": [
        g("情态动词表推测：must 表肯定推测，can't 表否定推测，may 表可能。",
          "He must be tired after the trip.", "旅途后他一定累了。"),
        g("名词性从句：what 引导主语/宾语/表语从句，表示\"…的事物\"。",
          "What we need is time.", "我们需要的是时间。"),
    ],
    "questions": [
        q("Families ___ together during the Spring Festival.", ["gather", "gathers", "gathering"], 0,
          "复数主语用动词原形 gather。"),
        q("He ___ be the owner — I saw him leave.", ["can't", "must", "may"], 0,
          "can't 表否定推测，意为\"不可能\"。"),
        q("They ___ the street with red flags.", ["decorated", "decorate", "decorating"], 0,
          "描述已发生用过去时 decorated。"),
        q("___ we need most is a plan.", ["What", "That", "Which"], 0,
          "what 引导主语从句，表\"…的事物\"。"),
        q("The ___ of the festival is a harvest thanks.", ["origin", "original", "originate"], 0,
          "origin 起源。"),
        q("We show ___ to our teachers.", ["gratitude", "grateful", "grade"], 0,
          "show gratitude 表达感激。"),
    ],
}
x1u1 = {
    "id": "x101", "title": "Unit 1 People of Achievement", "topic": "杰出人物 · 传记与成就",
    "words": [
        w("achieve", "əˈtʃiːv", "v.", "实现；达成",
          "She achieved her dream.", "她实现了梦想。"),
        w("contribution", "ˌkɒntrɪˈbjuːʃn", "n.", "贡献",
          "His contribution was great.", "他的贡献很大。"),
        w("devote", "dɪˈvəʊt", "v.", "致力于；奉献",
          "He devoted his life to science.", "他毕生奉献于科学。"),
        w("exceptional", "ɪkˈsepʃənl", "adj.", "杰出的；异常的",
          "She has exceptional talent.", "她才华出众。"),
        w("determined", "dɪˈtɜːmɪnd", "adj.", "下定决心的；坚定的",
          "He was determined to win.", "他下定决心要赢。"),
        w("intelligent", "ɪnˈtelɪdʒənt", "adj.", "聪明的；有智力的",
          "The child is highly intelligent.", "这孩子非常聪明。"),
        w("generous", "ˈdʒenərəs", "adj.", "慷慨的；大方的",
          "He is generous with his time.", "他慷慨地付出时间。"),
        w("acquire", "əˈkwaɪə(r)", "v.", "获得；习得",
          "She acquired many skills.", "她习得了许多技能。"),
        w("inspire", "ɪnˈspaɪə(r)", "v.", "激励；启发",
          "His story inspired us.", "他的故事激励了我们。"),
        w("outstanding", "aʊtˈstændɪŋ", "adj.", "杰出的；出色的",
          "She is an outstanding scientist.", "她是位杰出的科学家。"),
    ],
    "grammars": [
        g("非谓语动词：不定式 to do、动名词 doing、分词作状语/定语，使句子更简洁。",
          "To succeed, you must work hard.", "要成功，你必须努力。"),
        g("定语从句：who / whom / whose 指人，在从句中分别作主、宾、定语。",
          "The scientist whose theory changed the world was Einstein.", "改变世界的那位科学家是爱因斯坦。"),
    ],
    "questions": [
        q("He ___ his life to helping others.", ["devoted", "devotes", "devoting"], 0,
          "devote...to... 奉献于…；此处作谓语用过去时 devoted。"),
        q("___ succeed, you need to keep trying.", ["To", "For", "Of"], 0,
          "不定式 To succeed 作目的状语。"),
        q("The writer ___ book won a prize is my friend.", ["whose", "who", "which"], 0,
          "whose 在定语从句中作定语，表\"…的\"。"),
        q("She is an ___ student in every way.", ["outstanding", "outstand", "outstood"], 0,
          "outstanding 杰出的，作定语。"),
        q("His ___ to medicine saved many lives.", ["contribution", "contribute", "contributing"], 0,
          "his 后接名词 contribution（贡献）。"),
        q("We were ___ by her brave story.", ["inspired", "inspire", "inspiring"], 0,
          "被动语态 were inspired（被激励）。"),
    ],
}
x2u1 = {
    "id": "x201", "title": "Unit 1 Science and Scientists", "topic": "科学家与科学精神",
    "words": [
        w("scientific", "ˌsaɪənˈtɪfɪk", "adj.", "科学的",
          "We need a scientific method.", "我们需要科学的方法。"),
        w("theory", "ˈθɪəri", "n.", "理论；学说",
          "His theory changed physics.", "他的理论改变了物理学。"),
        w("discover", "dɪˈskʌvə(r)", "v.", "发现",
          "They discovered a new planet.", "他们发现了一颗新行星。"),
        w("phenomenon", "fəˈnɒmɪnən", "n.", "现象",
          "This is a natural phenomenon.", "这是一种自然现象。"),
        w("evidence", "ˈevɪdəns", "n.", "证据；证明",
          "We need solid evidence.", "我们需要确凿的证据。"),
        w("hypothesis", "haɪˈpɒθəsɪs", "n.", "假说；假设",
          "The hypothesis was tested.", "该假说经过了检验。"),
        w("conduct", "kənˈdʌkt", "v.", "进行；实施",
          "They conducted an experiment.", "他们做了一项实验。"),
        w("publish", "ˈpʌblɪʃ", "v.", "出版；发表",
          "She published a paper.", "她发表了一篇论文。"),
        w("breakthrough", "ˈbreɪkθruː", "n.", "突破；重大进展",
          "The research made a breakthrough.", "研究取得了突破。"),
        w("conclude", "kənˈkluːd", "v.", "得出结论；总结",
          "We concluded the test was valid.", "我们得出结论：测试有效。"),
    ],
    "grammars": [
        g("现在完成时被动语态：have/has been + 过去分词，强调已完成且影响延续。",
          "The theory has been proved.", "该理论已被证实。"),
        g("名词性从句作主语/宾语：what / that 引导，如 What he said is true.",
          "That he was right has been shown.", "他是对的这一点已被证明。"),
    ],
    "questions": [
        q("The experiment has ___ successfully.", ["been conducted", "conducted", "conducting"], 0,
          "现在完成时被动 has been conducted。"),
        q("They ___ a new way to treat the disease.", ["discovered", "discovers", "discovering"], 0,
          "描述已发生用过去时 discovered。"),
        q("We need more ___ to support the claim.", ["evidence", "evident", "evidently"], 0,
          "more 后接名词 evidence（证据）。"),
        q("His ___ changed how we see the universe.", ["theory", "theoretical", "theorize"], 0,
          "his 后接名词 theory（理论）。"),
        q("The team ___ the study last year.", ["conducted", "conduct", "conducts"], 0,
          "last year 用过去时 conducted。"),
        q("She ___ her findings in a journal.", ["published", "publishes", "publishing"], 0,
          "她发表了发现，用过去时 published。"),
    ],
}
x3u1 = {
    "id": "x301", "title": "Unit 1 Art", "topic": "艺术形式与欣赏",
    "words": [
        w("gallery", "ˈɡæləri", "n.", "画廊；美术馆",
          "We visited an art gallery.", "我们参观了一家美术馆。"),
        w("sculpture", "ˈskʌlptʃə(r)", "n.", "雕塑；雕刻",
          "The sculpture is made of stone.", "这座雕塑由石头制成。"),
        w("portrait", "ˈpɔːtreɪt", "n.", "肖像；画像",
          "He painted a portrait of his mother.", "他画了一幅母亲的肖像。"),
        w("exhibit", "ɪɡˈzɪbɪt", "v./n.", "展览；展品",
          "The museum exhibits old coins.", "博物馆展出了古币。"),
        w("contemporary", "kənˈtemprəri", "adj.", "当代的；同时代的",
          "I like contemporary art.", "我喜欢当代艺术。"),
        w("masterpiece", "ˈmɑːstəpiːs", "n.", "杰作；名著",
          "This is a masterpiece.", "这是一件杰作。"),
        w("convey", "kənˈveɪ", "v.", "传达；表达",
          "Art conveys feelings.", "艺术传达情感。"),
        w("abstract", "ˈæbstrækt", "adj.", "抽象的",
          "The painting is abstract.", "这幅画是抽象的。"),
        w("realistic", "ˌriːəˈlɪstɪk", "adj.", "现实的；写实主义的",
          "The drawing is very realistic.", "这幅画非常写实。"),
        w("perspective", "pəˈspektɪv", "n.", "视角；透视",
          "The artist changed perspective.", "艺术家改变了视角。"),
    ],
    "grammars": [
        g("定语从句：that / which / who 引导，修饰名词，使描述更紧凑。",
          "The painting which won the prize is famous.", "获奖的那幅画很有名。"),
        g("非谓语动词作定语：现在分词表主动，过去分词表被动。",
          "The exhibited works attracted many visitors.", "展出的作品吸引了许多观众。"),
    ],
    "questions": [
        q("The museum ___ works by local artists.", ["exhibits", "exhibit", "exhibiting"], 0,
          "主语 museum 单数，动词用 exhibits。"),
        q("The painting ___ won a prize is by Picasso.", ["which", "who", "what"], 0,
          "先行词 painting 指物，用 which 引导定语从句。"),
        q("Art can ___ deep feelings.", ["convey", "conveys", "conveying"], 0,
          "can 后接动词原形 convey（传达）。"),
        q("This is a ___ of modern architecture.", ["masterpiece", "master", "mastery"], 0,
          "a masterpiece 杰作。"),
        q("I prefer ___ art to classical art.", ["contemporary", "contemporaries", "contemporarily"], 0,
          "contemporary art 当代艺术。"),
        q("The ___ works were painted in the 19th century.", ["exhibited", "exhibit", "exhibiting"], 0,
          "过去分词 exhibited 作定语，表被动。"),
    ],
}
x4u1 = {
    "id": "x401", "title": "Unit 1 Science Fiction", "topic": "科幻文学与想象",
    "words": [
        w("fiction", "ˈfɪkʃn", "n.", "小说；虚构",
          "Science fiction is popular.", "科幻小说很受欢迎。"),
        w("alien", "ˈeɪliən", "n./adj.", "外星人；外国的",
          "The film is about aliens.", "这部电影关于外星人。"),
        w("spacecraft", "ˈspeɪskrɑːft", "n.", "航天器；宇宙飞船",
          "The spacecraft landed safely.", "航天器安全着陆。"),
        w("dimension", "daɪˈmenʃn", "n.", "维度；方面",
          "The story has another dimension.", "这个故事另有维度。"),
        w("artificial", "ˌɑːtɪˈfɪʃl", "adj.", "人工的；人造的",
          "AI is artificial intelligence.", "AI 是人工智能。"),
        w("consciousness", "ˈkɒnʃəsnəs", "n.", "意识；知觉",
          "The robot gained consciousness.", "机器人获得了意识。"),
        w("evolve", "ɪˈvɒlv", "v.", "进化；发展",
          "Humans evolved over millions of years.", "人类历经数百万年进化。"),
        w("narrative", "ˈnærətɪv", "n.", "叙事；叙述",
          "The narrative is complex.", "叙事很复杂。"),
        w("premise", "ˈpremɪs", "n.", "前提；假设",
          "The story's premise is interesting.", "这个故事的前提很有趣。"),
        w("speculative", "ˈspekjələtɪv", "adj.", "推测的；思辨的",
          "Sci-fi is speculative fiction.", "科幻是思辨性小说。"),
    ],
    "grammars": [
        g("虚拟语气：if 引导的非真实条件句，表示与现在/过去事实相反的假设。",
          "If I were an alien, I would explore Earth.", "如果我是外星人，我会探索地球。"),
        g("定语从句：that / which 修饰物，who 修饰人，在从句中作成分。",
          "A world which has no war is our hope.", "没有战争的世界是我们的希望。"),
    ],
    "questions": [
        q("If I ___ an alien, I would visit another planet.", ["were", "am", "be"], 0,
          "与现在事实相反的虚拟语气，be 用 were。"),
        q("The ___ landed on a distant planet.", ["spacecraft", "space", "spaceship's"], 0,
          "spacecraft 航天器，单复数同形。"),
        q("AI means ___ intelligence.", ["artificial", "artifice", "artist"], 0,
          "artificial intelligence 人工智能。"),
        q("The novel's ___ is about time travel.", ["premise", "premises", "premising"], 0,
          "premise 前提。"),
        q("Humans ___ from ancient apes.", ["evolved", "evolve", "evolving"], 0,
          "描述已发生用过去时 evolved。"),
        q("A story ___ makes us think is good sci-fi.", ["which", "who", "what"], 0,
          "先行词 story 指物，用 which 引导定语从句。"),
    ],
}

# ===================== 册与单元骨架 =====================
def outline(uid, title, topic):
    return {"id": uid, "title": title, "topic": topic, "words": [], "grammars": [], "questions": []}

BOOKS = [
    {"code": "b1", "title": "必修第一册", "units": [b1_welcome, b1u1, b1u2, b1u3, b1u4, b1u5]},
    {"code": "b2", "title": "必修第二册", "units": [
        b2u1,
        outline("b202", "Unit 2 Wildlife Protection", "野生动物保护"),
        outline("b203", "Unit 3 The Internet", "互联网与数字生活"),
        outline("b204", "Unit 4 History and Traditions", "历史与传统"),
        outline("b205", "Unit 5 Music", "音乐与情感"),
    ]},
    {"code": "b3", "title": "必修第三册", "units": [
        b3u1,
        outline("b302", "Unit 2 Healthy Eating", "健康饮食"),
        outline("b303", "Unit 3 Diverse Cultures", "多元文化"),
        outline("b304", "Unit 4 Space Exploration", "太空探索"),
        outline("b305", "Unit 5 The Value of Money", "金钱的价值"),
    ]},
    {"code": "x1", "title": "选择性必修第一册", "units": [
        x1u1,
        outline("x102", "Unit 2 Looking into the Future", "展望未来"),
        outline("x103", "Unit 3 Fascinating Parks", "迷人的公园"),
        outline("x104", "Unit 4 Body Language", "肢体语言"),
        outline("x105", "Unit 5 Working the Land", "耕耘土地"),
    ]},
    {"code": "x2", "title": "选择性必修第二册", "units": [
        x2u1,
        outline("x202", "Unit 2 Bridging Cultures", "文化桥梁"),
        outline("x203", "Unit 3 Food and Culture", "饮食与文化"),
        outline("x204", "Unit 4 Journey Across a Vast Land", "穿越广袤大地"),
        outline("x205", "Unit 5 First Aid", "急救常识"),
    ]},
    {"code": "x3", "title": "选择性必修第三册", "units": [
        x3u1,
        outline("x302", "Unit 2 Healthy Lifestyle", "健康生活方式"),
        outline("x303", "Unit 3 Environmental Protection", "环境保护"),
        outline("x304", "Unit 4 Adversity and Courage", "逆境与勇气"),
        outline("x305", "Unit 5 Poems", "诗歌欣赏"),
    ]},
    {"code": "x4", "title": "选择性必修第四册", "units": [
        x4u1,
        outline("x402", "Unit 2 Iconic Attractions", "标志性景点"),
        outline("x403", "Unit 3 Sea Exploration", "海洋探索"),
        outline("x404", "Unit 4 Sharing", "分享与互助"),
        outline("x405", "Unit 5 Launching Your Career", "职业生涯启航"),
    ]},
]

DATA = {
    "product": "高中英语课本章节同步训练",
    "version": "1.0",
    "schema_version": "1.0",
    "note": "人教版（2019 版）必修第一/二/三册 + 选择性必修第一~四册共 7 册 36 单元；每单元含重点词汇、语法要点与同步练习；词汇音频约定路径 /audio/sw/<word>.mp3（暂无则优雅降级）。必修第一册与各校首单元已充实，其余单元内容整理中。",
    "books": BOOKS,
}

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.normpath(os.path.join(here, "..", "data", "senior_textbook.json"))
    with open(out, "w", encoding="utf-8") as f:
        json.dump(DATA, f, ensure_ascii=False, indent=2)
    n_units = sum(len(b["units"]) for b in BOOKS)
    n_words = sum(len(u["words"]) for b in BOOKS for u in b["units"])
    n_q = sum(len(u["questions"]) for b in BOOKS for u in b["units"])
    print(f"written -> {out}")
    print(f"books={len(BOOKS)} units={n_units} words={n_words} questions={n_q}")
